// ==============================================================
// File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2015.4
// Copyright (C) 2015 Xilinx Inc. All rights reserved.
// ==============================================================

extern void fire2 (
hls::stream<short > matrix_i[96],
short kernel_s1x1[16],
short kernel_e1x1[64],
short kernel_e3x3[3][3][64],
hls::stream<short > matrix_o[128]);
