// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2015.4
// Copyright (C) 2015 Xilinx Inc. All rights reserved.
// 
// ===========================================================

#include "fire2_expand1x1.h"
#include "AESL_pkg.h"

using namespace std;

namespace ap_rtl {

const sc_logic fire2_expand1x1::ap_const_logic_1 = sc_dt::Log_1;
const sc_logic fire2_expand1x1::ap_const_logic_0 = sc_dt::Log_0;
const sc_lv<4> fire2_expand1x1::ap_ST_st1_fsm_0 = "1";
const sc_lv<4> fire2_expand1x1::ap_ST_st2_fsm_1 = "10";
const sc_lv<4> fire2_expand1x1::ap_ST_st3_fsm_2 = "100";
const sc_lv<4> fire2_expand1x1::ap_ST_st4_fsm_3 = "1000";
const sc_lv<32> fire2_expand1x1::ap_const_lv32_0 = "00000000000000000000000000000000";
const sc_lv<1> fire2_expand1x1::ap_const_lv1_1 = "1";
const sc_lv<32> fire2_expand1x1::ap_const_lv32_1 = "1";
const sc_lv<32> fire2_expand1x1::ap_const_lv32_2 = "10";
const sc_lv<32> fire2_expand1x1::ap_const_lv32_3 = "11";
const sc_lv<1> fire2_expand1x1::ap_const_lv1_0 = "0";
const sc_lv<4> fire2_expand1x1::ap_const_lv4_E = "1110";
const sc_lv<4> fire2_expand1x1::ap_const_lv4_D = "1101";
const sc_lv<4> fire2_expand1x1::ap_const_lv4_C = "1100";
const sc_lv<4> fire2_expand1x1::ap_const_lv4_B = "1011";
const sc_lv<4> fire2_expand1x1::ap_const_lv4_A = "1010";
const sc_lv<4> fire2_expand1x1::ap_const_lv4_9 = "1001";
const sc_lv<4> fire2_expand1x1::ap_const_lv4_8 = "1000";
const sc_lv<4> fire2_expand1x1::ap_const_lv4_7 = "111";
const sc_lv<4> fire2_expand1x1::ap_const_lv4_6 = "110";
const sc_lv<4> fire2_expand1x1::ap_const_lv4_5 = "101";
const sc_lv<4> fire2_expand1x1::ap_const_lv4_4 = "100";
const sc_lv<4> fire2_expand1x1::ap_const_lv4_3 = "11";
const sc_lv<4> fire2_expand1x1::ap_const_lv4_2 = "10";
const sc_lv<4> fire2_expand1x1::ap_const_lv4_1 = "1";
const sc_lv<4> fire2_expand1x1::ap_const_lv4_0 = "0000";
const sc_lv<6> fire2_expand1x1::ap_const_lv6_0 = "000000";
const sc_lv<5> fire2_expand1x1::ap_const_lv5_0 = "00000";
const sc_lv<6> fire2_expand1x1::ap_const_lv6_37 = "110111";
const sc_lv<6> fire2_expand1x1::ap_const_lv6_1 = "1";
const sc_lv<5> fire2_expand1x1::ap_const_lv5_10 = "10000";
const sc_lv<5> fire2_expand1x1::ap_const_lv5_1 = "1";

fire2_expand1x1::fire2_expand1x1(sc_module_name name) : sc_module(name), mVcdFile(0) {

    SC_METHOD(thread_ap_clk_no_reset_);
    dont_initialize();
    sensitive << ( ap_clk.pos() );

    SC_METHOD(thread_ap_done);
    sensitive << ( ap_done_reg );
    sensitive << ( ap_sig_cseq_ST_st2_fsm_1 );
    sensitive << ( exitcond4_fu_231_p2 );

    SC_METHOD(thread_ap_idle);
    sensitive << ( ap_start );
    sensitive << ( ap_sig_cseq_ST_st1_fsm_0 );

    SC_METHOD(thread_ap_ready);
    sensitive << ( ap_sig_cseq_ST_st2_fsm_1 );
    sensitive << ( exitcond4_fu_231_p2 );

    SC_METHOD(thread_ap_sig_bdd_101);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_sig_bdd_110);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_sig_bdd_119);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_sig_bdd_23);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_sig_bdd_247);
    sensitive << ( matrix_e1x1_i_0_V_empty_n );
    sensitive << ( matrix_e1x1_i_1_V_empty_n );
    sensitive << ( matrix_e1x1_i_2_V_empty_n );
    sensitive << ( matrix_e1x1_i_3_V_empty_n );
    sensitive << ( matrix_e1x1_i_4_V_empty_n );
    sensitive << ( matrix_e1x1_i_5_V_empty_n );
    sensitive << ( matrix_e1x1_i_6_V_empty_n );
    sensitive << ( matrix_e1x1_i_7_V_empty_n );
    sensitive << ( matrix_e1x1_i_8_V_empty_n );
    sensitive << ( matrix_e1x1_i_9_V_empty_n );
    sensitive << ( matrix_e1x1_i_10_V_empty_n );
    sensitive << ( matrix_e1x1_i_11_V_empty_n );
    sensitive << ( matrix_e1x1_i_12_V_empty_n );
    sensitive << ( matrix_e1x1_i_13_V_empty_n );
    sensitive << ( matrix_e1x1_i_14_V_empty_n );
    sensitive << ( matrix_e1x1_i_15_V_empty_n );
    sensitive << ( exitcond2_fu_255_p2 );
    sensitive << ( tmp_122_fu_267_p1 );

    SC_METHOD(thread_ap_sig_bdd_260);
    sensitive << ( ap_start );
    sensitive << ( ap_done_reg );

    SC_METHOD(thread_ap_sig_cseq_ST_st1_fsm_0);
    sensitive << ( ap_sig_bdd_23 );

    SC_METHOD(thread_ap_sig_cseq_ST_st2_fsm_1);
    sensitive << ( ap_sig_bdd_101 );

    SC_METHOD(thread_ap_sig_cseq_ST_st3_fsm_2);
    sensitive << ( ap_sig_bdd_110 );

    SC_METHOD(thread_ap_sig_cseq_ST_st4_fsm_3);
    sensitive << ( ap_sig_bdd_119 );

    SC_METHOD(thread_c_1_fu_249_p2);
    sensitive << ( c_reg_209 );

    SC_METHOD(thread_d_4_fu_261_p2);
    sensitive << ( d_reg_220 );

    SC_METHOD(thread_exitcond2_fu_255_p2);
    sensitive << ( ap_sig_cseq_ST_st4_fsm_3 );
    sensitive << ( ap_sig_bdd_247 );
    sensitive << ( d_reg_220 );

    SC_METHOD(thread_exitcond3_fu_243_p2);
    sensitive << ( ap_sig_cseq_ST_st3_fsm_2 );
    sensitive << ( c_reg_209 );

    SC_METHOD(thread_exitcond4_fu_231_p2);
    sensitive << ( ap_sig_cseq_ST_st2_fsm_1 );
    sensitive << ( r_reg_198 );

    SC_METHOD(thread_matrix_e1x1_i_0_V_read);
    sensitive << ( ap_sig_cseq_ST_st4_fsm_3 );
    sensitive << ( exitcond2_fu_255_p2 );
    sensitive << ( tmp_122_fu_267_p1 );
    sensitive << ( ap_sig_bdd_247 );

    SC_METHOD(thread_matrix_e1x1_i_10_V_read);
    sensitive << ( ap_sig_cseq_ST_st4_fsm_3 );
    sensitive << ( exitcond2_fu_255_p2 );
    sensitive << ( tmp_122_fu_267_p1 );
    sensitive << ( ap_sig_bdd_247 );

    SC_METHOD(thread_matrix_e1x1_i_11_V_read);
    sensitive << ( ap_sig_cseq_ST_st4_fsm_3 );
    sensitive << ( exitcond2_fu_255_p2 );
    sensitive << ( tmp_122_fu_267_p1 );
    sensitive << ( ap_sig_bdd_247 );

    SC_METHOD(thread_matrix_e1x1_i_12_V_read);
    sensitive << ( ap_sig_cseq_ST_st4_fsm_3 );
    sensitive << ( exitcond2_fu_255_p2 );
    sensitive << ( tmp_122_fu_267_p1 );
    sensitive << ( ap_sig_bdd_247 );

    SC_METHOD(thread_matrix_e1x1_i_13_V_read);
    sensitive << ( ap_sig_cseq_ST_st4_fsm_3 );
    sensitive << ( exitcond2_fu_255_p2 );
    sensitive << ( tmp_122_fu_267_p1 );
    sensitive << ( ap_sig_bdd_247 );

    SC_METHOD(thread_matrix_e1x1_i_14_V_read);
    sensitive << ( ap_sig_cseq_ST_st4_fsm_3 );
    sensitive << ( exitcond2_fu_255_p2 );
    sensitive << ( tmp_122_fu_267_p1 );
    sensitive << ( ap_sig_bdd_247 );

    SC_METHOD(thread_matrix_e1x1_i_15_V_read);
    sensitive << ( ap_sig_cseq_ST_st4_fsm_3 );
    sensitive << ( exitcond2_fu_255_p2 );
    sensitive << ( tmp_122_fu_267_p1 );
    sensitive << ( ap_sig_bdd_247 );

    SC_METHOD(thread_matrix_e1x1_i_1_V_read);
    sensitive << ( ap_sig_cseq_ST_st4_fsm_3 );
    sensitive << ( exitcond2_fu_255_p2 );
    sensitive << ( tmp_122_fu_267_p1 );
    sensitive << ( ap_sig_bdd_247 );

    SC_METHOD(thread_matrix_e1x1_i_2_V_read);
    sensitive << ( ap_sig_cseq_ST_st4_fsm_3 );
    sensitive << ( exitcond2_fu_255_p2 );
    sensitive << ( tmp_122_fu_267_p1 );
    sensitive << ( ap_sig_bdd_247 );

    SC_METHOD(thread_matrix_e1x1_i_3_V_read);
    sensitive << ( ap_sig_cseq_ST_st4_fsm_3 );
    sensitive << ( exitcond2_fu_255_p2 );
    sensitive << ( tmp_122_fu_267_p1 );
    sensitive << ( ap_sig_bdd_247 );

    SC_METHOD(thread_matrix_e1x1_i_4_V_read);
    sensitive << ( ap_sig_cseq_ST_st4_fsm_3 );
    sensitive << ( exitcond2_fu_255_p2 );
    sensitive << ( tmp_122_fu_267_p1 );
    sensitive << ( ap_sig_bdd_247 );

    SC_METHOD(thread_matrix_e1x1_i_5_V_read);
    sensitive << ( ap_sig_cseq_ST_st4_fsm_3 );
    sensitive << ( exitcond2_fu_255_p2 );
    sensitive << ( tmp_122_fu_267_p1 );
    sensitive << ( ap_sig_bdd_247 );

    SC_METHOD(thread_matrix_e1x1_i_6_V_read);
    sensitive << ( ap_sig_cseq_ST_st4_fsm_3 );
    sensitive << ( exitcond2_fu_255_p2 );
    sensitive << ( tmp_122_fu_267_p1 );
    sensitive << ( ap_sig_bdd_247 );

    SC_METHOD(thread_matrix_e1x1_i_7_V_read);
    sensitive << ( ap_sig_cseq_ST_st4_fsm_3 );
    sensitive << ( exitcond2_fu_255_p2 );
    sensitive << ( tmp_122_fu_267_p1 );
    sensitive << ( ap_sig_bdd_247 );

    SC_METHOD(thread_matrix_e1x1_i_8_V_read);
    sensitive << ( ap_sig_cseq_ST_st4_fsm_3 );
    sensitive << ( exitcond2_fu_255_p2 );
    sensitive << ( tmp_122_fu_267_p1 );
    sensitive << ( ap_sig_bdd_247 );

    SC_METHOD(thread_matrix_e1x1_i_9_V_read);
    sensitive << ( ap_sig_cseq_ST_st4_fsm_3 );
    sensitive << ( exitcond2_fu_255_p2 );
    sensitive << ( tmp_122_fu_267_p1 );
    sensitive << ( ap_sig_bdd_247 );

    SC_METHOD(thread_r_1_fu_237_p2);
    sensitive << ( r_reg_198 );

    SC_METHOD(thread_tmp_122_fu_267_p1);
    sensitive << ( d_reg_220 );

    SC_METHOD(thread_ap_NS_fsm);
    sensitive << ( ap_CS_fsm );
    sensitive << ( exitcond2_fu_255_p2 );
    sensitive << ( ap_sig_bdd_247 );
    sensitive << ( exitcond3_fu_243_p2 );
    sensitive << ( ap_sig_bdd_260 );
    sensitive << ( exitcond4_fu_231_p2 );

    ap_done_reg = SC_LOGIC_0;
    ap_CS_fsm = "0001";
    static int apTFileNum = 0;
    stringstream apTFilenSS;
    apTFilenSS << "fire2_expand1x1_sc_trace_" << apTFileNum ++;
    string apTFn = apTFilenSS.str();
    mVcdFile = sc_create_vcd_trace_file(apTFn.c_str());
    mVcdFile->set_time_unit(1, SC_PS);
    if (1) {
#ifdef __HLS_TRACE_LEVEL_PORT_HIER__
    sc_trace(mVcdFile, ap_clk, "(port)ap_clk");
    sc_trace(mVcdFile, ap_rst, "(port)ap_rst");
    sc_trace(mVcdFile, ap_start, "(port)ap_start");
    sc_trace(mVcdFile, ap_done, "(port)ap_done");
    sc_trace(mVcdFile, ap_continue, "(port)ap_continue");
    sc_trace(mVcdFile, ap_idle, "(port)ap_idle");
    sc_trace(mVcdFile, ap_ready, "(port)ap_ready");
    sc_trace(mVcdFile, matrix_e1x1_i_0_V_dout, "(port)matrix_e1x1_i_0_V_dout");
    sc_trace(mVcdFile, matrix_e1x1_i_0_V_empty_n, "(port)matrix_e1x1_i_0_V_empty_n");
    sc_trace(mVcdFile, matrix_e1x1_i_0_V_read, "(port)matrix_e1x1_i_0_V_read");
    sc_trace(mVcdFile, matrix_e1x1_i_1_V_dout, "(port)matrix_e1x1_i_1_V_dout");
    sc_trace(mVcdFile, matrix_e1x1_i_1_V_empty_n, "(port)matrix_e1x1_i_1_V_empty_n");
    sc_trace(mVcdFile, matrix_e1x1_i_1_V_read, "(port)matrix_e1x1_i_1_V_read");
    sc_trace(mVcdFile, matrix_e1x1_i_2_V_dout, "(port)matrix_e1x1_i_2_V_dout");
    sc_trace(mVcdFile, matrix_e1x1_i_2_V_empty_n, "(port)matrix_e1x1_i_2_V_empty_n");
    sc_trace(mVcdFile, matrix_e1x1_i_2_V_read, "(port)matrix_e1x1_i_2_V_read");
    sc_trace(mVcdFile, matrix_e1x1_i_3_V_dout, "(port)matrix_e1x1_i_3_V_dout");
    sc_trace(mVcdFile, matrix_e1x1_i_3_V_empty_n, "(port)matrix_e1x1_i_3_V_empty_n");
    sc_trace(mVcdFile, matrix_e1x1_i_3_V_read, "(port)matrix_e1x1_i_3_V_read");
    sc_trace(mVcdFile, matrix_e1x1_i_4_V_dout, "(port)matrix_e1x1_i_4_V_dout");
    sc_trace(mVcdFile, matrix_e1x1_i_4_V_empty_n, "(port)matrix_e1x1_i_4_V_empty_n");
    sc_trace(mVcdFile, matrix_e1x1_i_4_V_read, "(port)matrix_e1x1_i_4_V_read");
    sc_trace(mVcdFile, matrix_e1x1_i_5_V_dout, "(port)matrix_e1x1_i_5_V_dout");
    sc_trace(mVcdFile, matrix_e1x1_i_5_V_empty_n, "(port)matrix_e1x1_i_5_V_empty_n");
    sc_trace(mVcdFile, matrix_e1x1_i_5_V_read, "(port)matrix_e1x1_i_5_V_read");
    sc_trace(mVcdFile, matrix_e1x1_i_6_V_dout, "(port)matrix_e1x1_i_6_V_dout");
    sc_trace(mVcdFile, matrix_e1x1_i_6_V_empty_n, "(port)matrix_e1x1_i_6_V_empty_n");
    sc_trace(mVcdFile, matrix_e1x1_i_6_V_read, "(port)matrix_e1x1_i_6_V_read");
    sc_trace(mVcdFile, matrix_e1x1_i_7_V_dout, "(port)matrix_e1x1_i_7_V_dout");
    sc_trace(mVcdFile, matrix_e1x1_i_7_V_empty_n, "(port)matrix_e1x1_i_7_V_empty_n");
    sc_trace(mVcdFile, matrix_e1x1_i_7_V_read, "(port)matrix_e1x1_i_7_V_read");
    sc_trace(mVcdFile, matrix_e1x1_i_8_V_dout, "(port)matrix_e1x1_i_8_V_dout");
    sc_trace(mVcdFile, matrix_e1x1_i_8_V_empty_n, "(port)matrix_e1x1_i_8_V_empty_n");
    sc_trace(mVcdFile, matrix_e1x1_i_8_V_read, "(port)matrix_e1x1_i_8_V_read");
    sc_trace(mVcdFile, matrix_e1x1_i_9_V_dout, "(port)matrix_e1x1_i_9_V_dout");
    sc_trace(mVcdFile, matrix_e1x1_i_9_V_empty_n, "(port)matrix_e1x1_i_9_V_empty_n");
    sc_trace(mVcdFile, matrix_e1x1_i_9_V_read, "(port)matrix_e1x1_i_9_V_read");
    sc_trace(mVcdFile, matrix_e1x1_i_10_V_dout, "(port)matrix_e1x1_i_10_V_dout");
    sc_trace(mVcdFile, matrix_e1x1_i_10_V_empty_n, "(port)matrix_e1x1_i_10_V_empty_n");
    sc_trace(mVcdFile, matrix_e1x1_i_10_V_read, "(port)matrix_e1x1_i_10_V_read");
    sc_trace(mVcdFile, matrix_e1x1_i_11_V_dout, "(port)matrix_e1x1_i_11_V_dout");
    sc_trace(mVcdFile, matrix_e1x1_i_11_V_empty_n, "(port)matrix_e1x1_i_11_V_empty_n");
    sc_trace(mVcdFile, matrix_e1x1_i_11_V_read, "(port)matrix_e1x1_i_11_V_read");
    sc_trace(mVcdFile, matrix_e1x1_i_12_V_dout, "(port)matrix_e1x1_i_12_V_dout");
    sc_trace(mVcdFile, matrix_e1x1_i_12_V_empty_n, "(port)matrix_e1x1_i_12_V_empty_n");
    sc_trace(mVcdFile, matrix_e1x1_i_12_V_read, "(port)matrix_e1x1_i_12_V_read");
    sc_trace(mVcdFile, matrix_e1x1_i_13_V_dout, "(port)matrix_e1x1_i_13_V_dout");
    sc_trace(mVcdFile, matrix_e1x1_i_13_V_empty_n, "(port)matrix_e1x1_i_13_V_empty_n");
    sc_trace(mVcdFile, matrix_e1x1_i_13_V_read, "(port)matrix_e1x1_i_13_V_read");
    sc_trace(mVcdFile, matrix_e1x1_i_14_V_dout, "(port)matrix_e1x1_i_14_V_dout");
    sc_trace(mVcdFile, matrix_e1x1_i_14_V_empty_n, "(port)matrix_e1x1_i_14_V_empty_n");
    sc_trace(mVcdFile, matrix_e1x1_i_14_V_read, "(port)matrix_e1x1_i_14_V_read");
    sc_trace(mVcdFile, matrix_e1x1_i_15_V_dout, "(port)matrix_e1x1_i_15_V_dout");
    sc_trace(mVcdFile, matrix_e1x1_i_15_V_empty_n, "(port)matrix_e1x1_i_15_V_empty_n");
    sc_trace(mVcdFile, matrix_e1x1_i_15_V_read, "(port)matrix_e1x1_i_15_V_read");
#endif
#ifdef __HLS_TRACE_LEVEL_INT__
    sc_trace(mVcdFile, ap_done_reg, "ap_done_reg");
    sc_trace(mVcdFile, ap_CS_fsm, "ap_CS_fsm");
    sc_trace(mVcdFile, ap_sig_cseq_ST_st1_fsm_0, "ap_sig_cseq_ST_st1_fsm_0");
    sc_trace(mVcdFile, ap_sig_bdd_23, "ap_sig_bdd_23");
    sc_trace(mVcdFile, r_1_fu_237_p2, "r_1_fu_237_p2");
    sc_trace(mVcdFile, r_1_reg_274, "r_1_reg_274");
    sc_trace(mVcdFile, ap_sig_cseq_ST_st2_fsm_1, "ap_sig_cseq_ST_st2_fsm_1");
    sc_trace(mVcdFile, ap_sig_bdd_101, "ap_sig_bdd_101");
    sc_trace(mVcdFile, c_1_fu_249_p2, "c_1_fu_249_p2");
    sc_trace(mVcdFile, c_1_reg_282, "c_1_reg_282");
    sc_trace(mVcdFile, ap_sig_cseq_ST_st3_fsm_2, "ap_sig_cseq_ST_st3_fsm_2");
    sc_trace(mVcdFile, ap_sig_bdd_110, "ap_sig_bdd_110");
    sc_trace(mVcdFile, d_4_fu_261_p2, "d_4_fu_261_p2");
    sc_trace(mVcdFile, ap_sig_cseq_ST_st4_fsm_3, "ap_sig_cseq_ST_st4_fsm_3");
    sc_trace(mVcdFile, ap_sig_bdd_119, "ap_sig_bdd_119");
    sc_trace(mVcdFile, exitcond2_fu_255_p2, "exitcond2_fu_255_p2");
    sc_trace(mVcdFile, tmp_122_fu_267_p1, "tmp_122_fu_267_p1");
    sc_trace(mVcdFile, ap_sig_bdd_247, "ap_sig_bdd_247");
    sc_trace(mVcdFile, r_reg_198, "r_reg_198");
    sc_trace(mVcdFile, exitcond3_fu_243_p2, "exitcond3_fu_243_p2");
    sc_trace(mVcdFile, ap_sig_bdd_260, "ap_sig_bdd_260");
    sc_trace(mVcdFile, c_reg_209, "c_reg_209");
    sc_trace(mVcdFile, exitcond4_fu_231_p2, "exitcond4_fu_231_p2");
    sc_trace(mVcdFile, d_reg_220, "d_reg_220");
    sc_trace(mVcdFile, ap_NS_fsm, "ap_NS_fsm");
#endif

    }
}

fire2_expand1x1::~fire2_expand1x1() {
    if (mVcdFile) 
        sc_close_vcd_trace_file(mVcdFile);

}

void fire2_expand1x1::thread_ap_clk_no_reset_() {
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_CS_fsm = ap_ST_st1_fsm_0;
    } else {
        ap_CS_fsm = ap_NS_fsm.read();
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_done_reg = ap_const_logic_0;
    } else {
        if (esl_seteq<1,1,1>(ap_const_logic_1, ap_continue.read())) {
            ap_done_reg = ap_const_logic_0;
        } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st2_fsm_1.read()) && 
                    !esl_seteq<1,1,1>(ap_const_lv1_0, exitcond4_fu_231_p2.read()))) {
            ap_done_reg = ap_const_logic_1;
        }
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st4_fsm_3.read()) && 
         !ap_sig_bdd_247.read() && 
         !esl_seteq<1,1,1>(exitcond2_fu_255_p2.read(), ap_const_lv1_0))) {
        c_reg_209 = c_1_reg_282.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st2_fsm_1.read()) && 
                esl_seteq<1,1,1>(ap_const_lv1_0, exitcond4_fu_231_p2.read()))) {
        c_reg_209 = ap_const_lv6_0;
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st4_fsm_3.read()) && 
         esl_seteq<1,1,1>(exitcond2_fu_255_p2.read(), ap_const_lv1_0) && 
         !ap_sig_bdd_247.read())) {
        d_reg_220 = d_4_fu_261_p2.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st3_fsm_2.read()) && 
                esl_seteq<1,1,1>(ap_const_lv1_0, exitcond3_fu_243_p2.read()))) {
        d_reg_220 = ap_const_lv5_0;
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st1_fsm_0.read()) && 
         !ap_sig_bdd_260.read())) {
        r_reg_198 = ap_const_lv6_0;
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st3_fsm_2.read()) && 
                !esl_seteq<1,1,1>(ap_const_lv1_0, exitcond3_fu_243_p2.read()))) {
        r_reg_198 = r_1_reg_274.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st3_fsm_2.read())) {
        c_1_reg_282 = c_1_fu_249_p2.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st2_fsm_1.read())) {
        r_1_reg_274 = r_1_fu_237_p2.read();
    }
}

void fire2_expand1x1::thread_ap_done() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_done_reg.read()) || 
         (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st2_fsm_1.read()) && 
          !esl_seteq<1,1,1>(ap_const_lv1_0, exitcond4_fu_231_p2.read())))) {
        ap_done = ap_const_logic_1;
    } else {
        ap_done = ap_const_logic_0;
    }
}

void fire2_expand1x1::thread_ap_idle() {
    if ((!esl_seteq<1,1,1>(ap_const_logic_1, ap_start.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st1_fsm_0.read()))) {
        ap_idle = ap_const_logic_1;
    } else {
        ap_idle = ap_const_logic_0;
    }
}

void fire2_expand1x1::thread_ap_ready() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st2_fsm_1.read()) && 
         !esl_seteq<1,1,1>(ap_const_lv1_0, exitcond4_fu_231_p2.read()))) {
        ap_ready = ap_const_logic_1;
    } else {
        ap_ready = ap_const_logic_0;
    }
}

void fire2_expand1x1::thread_ap_sig_bdd_101() {
    ap_sig_bdd_101 = esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm.read().range(1, 1));
}

void fire2_expand1x1::thread_ap_sig_bdd_110() {
    ap_sig_bdd_110 = esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm.read().range(2, 2));
}

void fire2_expand1x1::thread_ap_sig_bdd_119() {
    ap_sig_bdd_119 = esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm.read().range(3, 3));
}

void fire2_expand1x1::thread_ap_sig_bdd_23() {
    ap_sig_bdd_23 = esl_seteq<1,1,1>(ap_CS_fsm.read().range(0, 0), ap_const_lv1_1);
}

void fire2_expand1x1::thread_ap_sig_bdd_247() {
    ap_sig_bdd_247 = ((esl_seteq<1,1,1>(matrix_e1x1_i_14_V_empty_n.read(), ap_const_logic_0) && 
  esl_seteq<1,1,1>(exitcond2_fu_255_p2.read(), ap_const_lv1_0) && 
  esl_seteq<1,4,4>(tmp_122_fu_267_p1.read(), ap_const_lv4_E)) || (esl_seteq<1,1,1>(exitcond2_fu_255_p2.read(), ap_const_lv1_0) && 
  esl_seteq<1,1,1>(matrix_e1x1_i_13_V_empty_n.read(), ap_const_logic_0) && 
  esl_seteq<1,4,4>(tmp_122_fu_267_p1.read(), ap_const_lv4_D)) || (esl_seteq<1,1,1>(exitcond2_fu_255_p2.read(), ap_const_lv1_0) && 
  esl_seteq<1,1,1>(matrix_e1x1_i_12_V_empty_n.read(), ap_const_logic_0) && 
  esl_seteq<1,4,4>(tmp_122_fu_267_p1.read(), ap_const_lv4_C)) || (esl_seteq<1,1,1>(exitcond2_fu_255_p2.read(), ap_const_lv1_0) && 
  esl_seteq<1,1,1>(matrix_e1x1_i_11_V_empty_n.read(), ap_const_logic_0) && 
  esl_seteq<1,4,4>(tmp_122_fu_267_p1.read(), ap_const_lv4_B)) || (esl_seteq<1,1,1>(exitcond2_fu_255_p2.read(), ap_const_lv1_0) && 
  esl_seteq<1,1,1>(matrix_e1x1_i_10_V_empty_n.read(), ap_const_logic_0) && 
  esl_seteq<1,4,4>(tmp_122_fu_267_p1.read(), ap_const_lv4_A)) || (esl_seteq<1,1,1>(exitcond2_fu_255_p2.read(), ap_const_lv1_0) && 
  esl_seteq<1,1,1>(matrix_e1x1_i_9_V_empty_n.read(), ap_const_logic_0) && 
  esl_seteq<1,4,4>(tmp_122_fu_267_p1.read(), ap_const_lv4_9)) || (esl_seteq<1,1,1>(exitcond2_fu_255_p2.read(), ap_const_lv1_0) && 
  esl_seteq<1,1,1>(matrix_e1x1_i_8_V_empty_n.read(), ap_const_logic_0) && 
  esl_seteq<1,4,4>(tmp_122_fu_267_p1.read(), ap_const_lv4_8)) || (esl_seteq<1,1,1>(exitcond2_fu_255_p2.read(), ap_const_lv1_0) && 
  esl_seteq<1,1,1>(matrix_e1x1_i_7_V_empty_n.read(), ap_const_logic_0) && 
  esl_seteq<1,4,4>(tmp_122_fu_267_p1.read(), ap_const_lv4_7)) || (esl_seteq<1,1,1>(exitcond2_fu_255_p2.read(), ap_const_lv1_0) && 
  esl_seteq<1,1,1>(matrix_e1x1_i_6_V_empty_n.read(), ap_const_logic_0) && 
  esl_seteq<1,4,4>(tmp_122_fu_267_p1.read(), ap_const_lv4_6)) || (esl_seteq<1,1,1>(exitcond2_fu_255_p2.read(), ap_const_lv1_0) && 
  esl_seteq<1,1,1>(matrix_e1x1_i_5_V_empty_n.read(), ap_const_logic_0) && 
  esl_seteq<1,4,4>(tmp_122_fu_267_p1.read(), ap_const_lv4_5)) || (esl_seteq<1,1,1>(exitcond2_fu_255_p2.read(), ap_const_lv1_0) && 
  esl_seteq<1,1,1>(matrix_e1x1_i_4_V_empty_n.read(), ap_const_logic_0) && 
  esl_seteq<1,4,4>(tmp_122_fu_267_p1.read(), ap_const_lv4_4)) || (esl_seteq<1,1,1>(exitcond2_fu_255_p2.read(), ap_const_lv1_0) && 
  esl_seteq<1,1,1>(matrix_e1x1_i_3_V_empty_n.read(), ap_const_logic_0) && 
  esl_seteq<1,4,4>(tmp_122_fu_267_p1.read(), ap_const_lv4_3)) || (esl_seteq<1,1,1>(exitcond2_fu_255_p2.read(), ap_const_lv1_0) && 
  esl_seteq<1,1,1>(matrix_e1x1_i_2_V_empty_n.read(), ap_const_logic_0) && 
  esl_seteq<1,4,4>(tmp_122_fu_267_p1.read(), ap_const_lv4_2)) || (esl_seteq<1,1,1>(exitcond2_fu_255_p2.read(), ap_const_lv1_0) && 
  esl_seteq<1,1,1>(matrix_e1x1_i_1_V_empty_n.read(), ap_const_logic_0) && 
  esl_seteq<1,4,4>(tmp_122_fu_267_p1.read(), ap_const_lv4_1)) || (esl_seteq<1,1,1>(exitcond2_fu_255_p2.read(), ap_const_lv1_0) && 
  esl_seteq<1,1,1>(matrix_e1x1_i_0_V_empty_n.read(), ap_const_logic_0) && 
  esl_seteq<1,4,4>(tmp_122_fu_267_p1.read(), ap_const_lv4_0)) || (esl_seteq<1,1,1>(exitcond2_fu_255_p2.read(), ap_const_lv1_0) && 
  esl_seteq<1,1,1>(matrix_e1x1_i_15_V_empty_n.read(), ap_const_logic_0) && 
  !esl_seteq<1,4,4>(tmp_122_fu_267_p1.read(), ap_const_lv4_E) && 
  !esl_seteq<1,4,4>(tmp_122_fu_267_p1.read(), ap_const_lv4_D) && 
  !esl_seteq<1,4,4>(tmp_122_fu_267_p1.read(), ap_const_lv4_C) && 
  !esl_seteq<1,4,4>(tmp_122_fu_267_p1.read(), ap_const_lv4_B) && 
  !esl_seteq<1,4,4>(tmp_122_fu_267_p1.read(), ap_const_lv4_A) && 
  !esl_seteq<1,4,4>(tmp_122_fu_267_p1.read(), ap_const_lv4_9) && 
  !esl_seteq<1,4,4>(tmp_122_fu_267_p1.read(), ap_const_lv4_8) && 
  !esl_seteq<1,4,4>(tmp_122_fu_267_p1.read(), ap_const_lv4_7) && 
  !esl_seteq<1,4,4>(tmp_122_fu_267_p1.read(), ap_const_lv4_6) && 
  !esl_seteq<1,4,4>(tmp_122_fu_267_p1.read(), ap_const_lv4_5) && 
  !esl_seteq<1,4,4>(tmp_122_fu_267_p1.read(), ap_const_lv4_4) && 
  !esl_seteq<1,4,4>(tmp_122_fu_267_p1.read(), ap_const_lv4_3) && 
  !esl_seteq<1,4,4>(tmp_122_fu_267_p1.read(), ap_const_lv4_2) && 
  !esl_seteq<1,4,4>(tmp_122_fu_267_p1.read(), ap_const_lv4_1) && 
  !esl_seteq<1,4,4>(tmp_122_fu_267_p1.read(), ap_const_lv4_0)));
}

void fire2_expand1x1::thread_ap_sig_bdd_260() {
    ap_sig_bdd_260 = (esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_0) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1));
}

void fire2_expand1x1::thread_ap_sig_cseq_ST_st1_fsm_0() {
    if (ap_sig_bdd_23.read()) {
        ap_sig_cseq_ST_st1_fsm_0 = ap_const_logic_1;
    } else {
        ap_sig_cseq_ST_st1_fsm_0 = ap_const_logic_0;
    }
}

void fire2_expand1x1::thread_ap_sig_cseq_ST_st2_fsm_1() {
    if (ap_sig_bdd_101.read()) {
        ap_sig_cseq_ST_st2_fsm_1 = ap_const_logic_1;
    } else {
        ap_sig_cseq_ST_st2_fsm_1 = ap_const_logic_0;
    }
}

void fire2_expand1x1::thread_ap_sig_cseq_ST_st3_fsm_2() {
    if (ap_sig_bdd_110.read()) {
        ap_sig_cseq_ST_st3_fsm_2 = ap_const_logic_1;
    } else {
        ap_sig_cseq_ST_st3_fsm_2 = ap_const_logic_0;
    }
}

void fire2_expand1x1::thread_ap_sig_cseq_ST_st4_fsm_3() {
    if (ap_sig_bdd_119.read()) {
        ap_sig_cseq_ST_st4_fsm_3 = ap_const_logic_1;
    } else {
        ap_sig_cseq_ST_st4_fsm_3 = ap_const_logic_0;
    }
}

void fire2_expand1x1::thread_c_1_fu_249_p2() {
    c_1_fu_249_p2 = (!c_reg_209.read().is_01() || !ap_const_lv6_1.is_01())? sc_lv<6>(): (sc_biguint<6>(c_reg_209.read()) + sc_biguint<6>(ap_const_lv6_1));
}

void fire2_expand1x1::thread_d_4_fu_261_p2() {
    d_4_fu_261_p2 = (!d_reg_220.read().is_01() || !ap_const_lv5_1.is_01())? sc_lv<5>(): (sc_biguint<5>(d_reg_220.read()) + sc_biguint<5>(ap_const_lv5_1));
}

void fire2_expand1x1::thread_exitcond2_fu_255_p2() {
    exitcond2_fu_255_p2 = (!d_reg_220.read().is_01() || !ap_const_lv5_10.is_01())? sc_lv<1>(): sc_lv<1>(d_reg_220.read() == ap_const_lv5_10);
}

void fire2_expand1x1::thread_exitcond3_fu_243_p2() {
    exitcond3_fu_243_p2 = (!c_reg_209.read().is_01() || !ap_const_lv6_37.is_01())? sc_lv<1>(): sc_lv<1>(c_reg_209.read() == ap_const_lv6_37);
}

void fire2_expand1x1::thread_exitcond4_fu_231_p2() {
    exitcond4_fu_231_p2 = (!r_reg_198.read().is_01() || !ap_const_lv6_37.is_01())? sc_lv<1>(): sc_lv<1>(r_reg_198.read() == ap_const_lv6_37);
}

void fire2_expand1x1::thread_matrix_e1x1_i_0_V_read() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st4_fsm_3.read()) && 
         esl_seteq<1,1,1>(exitcond2_fu_255_p2.read(), ap_const_lv1_0) && 
         esl_seteq<1,4,4>(tmp_122_fu_267_p1.read(), ap_const_lv4_0) && 
         !ap_sig_bdd_247.read())) {
        matrix_e1x1_i_0_V_read = ap_const_logic_1;
    } else {
        matrix_e1x1_i_0_V_read = ap_const_logic_0;
    }
}

void fire2_expand1x1::thread_matrix_e1x1_i_10_V_read() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st4_fsm_3.read()) && 
         esl_seteq<1,1,1>(exitcond2_fu_255_p2.read(), ap_const_lv1_0) && 
         esl_seteq<1,4,4>(tmp_122_fu_267_p1.read(), ap_const_lv4_A) && 
         !ap_sig_bdd_247.read())) {
        matrix_e1x1_i_10_V_read = ap_const_logic_1;
    } else {
        matrix_e1x1_i_10_V_read = ap_const_logic_0;
    }
}

void fire2_expand1x1::thread_matrix_e1x1_i_11_V_read() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st4_fsm_3.read()) && 
         esl_seteq<1,1,1>(exitcond2_fu_255_p2.read(), ap_const_lv1_0) && 
         esl_seteq<1,4,4>(tmp_122_fu_267_p1.read(), ap_const_lv4_B) && 
         !ap_sig_bdd_247.read())) {
        matrix_e1x1_i_11_V_read = ap_const_logic_1;
    } else {
        matrix_e1x1_i_11_V_read = ap_const_logic_0;
    }
}

void fire2_expand1x1::thread_matrix_e1x1_i_12_V_read() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st4_fsm_3.read()) && 
         esl_seteq<1,1,1>(exitcond2_fu_255_p2.read(), ap_const_lv1_0) && 
         esl_seteq<1,4,4>(tmp_122_fu_267_p1.read(), ap_const_lv4_C) && 
         !ap_sig_bdd_247.read())) {
        matrix_e1x1_i_12_V_read = ap_const_logic_1;
    } else {
        matrix_e1x1_i_12_V_read = ap_const_logic_0;
    }
}

void fire2_expand1x1::thread_matrix_e1x1_i_13_V_read() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st4_fsm_3.read()) && 
         esl_seteq<1,1,1>(exitcond2_fu_255_p2.read(), ap_const_lv1_0) && 
         esl_seteq<1,4,4>(tmp_122_fu_267_p1.read(), ap_const_lv4_D) && 
         !ap_sig_bdd_247.read())) {
        matrix_e1x1_i_13_V_read = ap_const_logic_1;
    } else {
        matrix_e1x1_i_13_V_read = ap_const_logic_0;
    }
}

void fire2_expand1x1::thread_matrix_e1x1_i_14_V_read() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st4_fsm_3.read()) && 
         esl_seteq<1,1,1>(exitcond2_fu_255_p2.read(), ap_const_lv1_0) && 
         esl_seteq<1,4,4>(tmp_122_fu_267_p1.read(), ap_const_lv4_E) && 
         !ap_sig_bdd_247.read())) {
        matrix_e1x1_i_14_V_read = ap_const_logic_1;
    } else {
        matrix_e1x1_i_14_V_read = ap_const_logic_0;
    }
}

void fire2_expand1x1::thread_matrix_e1x1_i_15_V_read() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st4_fsm_3.read()) && 
         esl_seteq<1,1,1>(exitcond2_fu_255_p2.read(), ap_const_lv1_0) && 
         !esl_seteq<1,4,4>(tmp_122_fu_267_p1.read(), ap_const_lv4_E) && 
         !esl_seteq<1,4,4>(tmp_122_fu_267_p1.read(), ap_const_lv4_D) && 
         !esl_seteq<1,4,4>(tmp_122_fu_267_p1.read(), ap_const_lv4_C) && 
         !esl_seteq<1,4,4>(tmp_122_fu_267_p1.read(), ap_const_lv4_B) && 
         !esl_seteq<1,4,4>(tmp_122_fu_267_p1.read(), ap_const_lv4_A) && 
         !esl_seteq<1,4,4>(tmp_122_fu_267_p1.read(), ap_const_lv4_9) && 
         !esl_seteq<1,4,4>(tmp_122_fu_267_p1.read(), ap_const_lv4_8) && 
         !esl_seteq<1,4,4>(tmp_122_fu_267_p1.read(), ap_const_lv4_7) && 
         !esl_seteq<1,4,4>(tmp_122_fu_267_p1.read(), ap_const_lv4_6) && 
         !esl_seteq<1,4,4>(tmp_122_fu_267_p1.read(), ap_const_lv4_5) && 
         !esl_seteq<1,4,4>(tmp_122_fu_267_p1.read(), ap_const_lv4_4) && 
         !esl_seteq<1,4,4>(tmp_122_fu_267_p1.read(), ap_const_lv4_3) && 
         !esl_seteq<1,4,4>(tmp_122_fu_267_p1.read(), ap_const_lv4_2) && 
         !esl_seteq<1,4,4>(tmp_122_fu_267_p1.read(), ap_const_lv4_1) && 
         !esl_seteq<1,4,4>(tmp_122_fu_267_p1.read(), ap_const_lv4_0) && 
         !ap_sig_bdd_247.read())) {
        matrix_e1x1_i_15_V_read = ap_const_logic_1;
    } else {
        matrix_e1x1_i_15_V_read = ap_const_logic_0;
    }
}

void fire2_expand1x1::thread_matrix_e1x1_i_1_V_read() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st4_fsm_3.read()) && 
         esl_seteq<1,1,1>(exitcond2_fu_255_p2.read(), ap_const_lv1_0) && 
         esl_seteq<1,4,4>(tmp_122_fu_267_p1.read(), ap_const_lv4_1) && 
         !ap_sig_bdd_247.read())) {
        matrix_e1x1_i_1_V_read = ap_const_logic_1;
    } else {
        matrix_e1x1_i_1_V_read = ap_const_logic_0;
    }
}

void fire2_expand1x1::thread_matrix_e1x1_i_2_V_read() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st4_fsm_3.read()) && 
         esl_seteq<1,1,1>(exitcond2_fu_255_p2.read(), ap_const_lv1_0) && 
         esl_seteq<1,4,4>(tmp_122_fu_267_p1.read(), ap_const_lv4_2) && 
         !ap_sig_bdd_247.read())) {
        matrix_e1x1_i_2_V_read = ap_const_logic_1;
    } else {
        matrix_e1x1_i_2_V_read = ap_const_logic_0;
    }
}

void fire2_expand1x1::thread_matrix_e1x1_i_3_V_read() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st4_fsm_3.read()) && 
         esl_seteq<1,1,1>(exitcond2_fu_255_p2.read(), ap_const_lv1_0) && 
         esl_seteq<1,4,4>(tmp_122_fu_267_p1.read(), ap_const_lv4_3) && 
         !ap_sig_bdd_247.read())) {
        matrix_e1x1_i_3_V_read = ap_const_logic_1;
    } else {
        matrix_e1x1_i_3_V_read = ap_const_logic_0;
    }
}

void fire2_expand1x1::thread_matrix_e1x1_i_4_V_read() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st4_fsm_3.read()) && 
         esl_seteq<1,1,1>(exitcond2_fu_255_p2.read(), ap_const_lv1_0) && 
         esl_seteq<1,4,4>(tmp_122_fu_267_p1.read(), ap_const_lv4_4) && 
         !ap_sig_bdd_247.read())) {
        matrix_e1x1_i_4_V_read = ap_const_logic_1;
    } else {
        matrix_e1x1_i_4_V_read = ap_const_logic_0;
    }
}

void fire2_expand1x1::thread_matrix_e1x1_i_5_V_read() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st4_fsm_3.read()) && 
         esl_seteq<1,1,1>(exitcond2_fu_255_p2.read(), ap_const_lv1_0) && 
         esl_seteq<1,4,4>(tmp_122_fu_267_p1.read(), ap_const_lv4_5) && 
         !ap_sig_bdd_247.read())) {
        matrix_e1x1_i_5_V_read = ap_const_logic_1;
    } else {
        matrix_e1x1_i_5_V_read = ap_const_logic_0;
    }
}

void fire2_expand1x1::thread_matrix_e1x1_i_6_V_read() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st4_fsm_3.read()) && 
         esl_seteq<1,1,1>(exitcond2_fu_255_p2.read(), ap_const_lv1_0) && 
         esl_seteq<1,4,4>(tmp_122_fu_267_p1.read(), ap_const_lv4_6) && 
         !ap_sig_bdd_247.read())) {
        matrix_e1x1_i_6_V_read = ap_const_logic_1;
    } else {
        matrix_e1x1_i_6_V_read = ap_const_logic_0;
    }
}

void fire2_expand1x1::thread_matrix_e1x1_i_7_V_read() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st4_fsm_3.read()) && 
         esl_seteq<1,1,1>(exitcond2_fu_255_p2.read(), ap_const_lv1_0) && 
         esl_seteq<1,4,4>(tmp_122_fu_267_p1.read(), ap_const_lv4_7) && 
         !ap_sig_bdd_247.read())) {
        matrix_e1x1_i_7_V_read = ap_const_logic_1;
    } else {
        matrix_e1x1_i_7_V_read = ap_const_logic_0;
    }
}

void fire2_expand1x1::thread_matrix_e1x1_i_8_V_read() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st4_fsm_3.read()) && 
         esl_seteq<1,1,1>(exitcond2_fu_255_p2.read(), ap_const_lv1_0) && 
         esl_seteq<1,4,4>(tmp_122_fu_267_p1.read(), ap_const_lv4_8) && 
         !ap_sig_bdd_247.read())) {
        matrix_e1x1_i_8_V_read = ap_const_logic_1;
    } else {
        matrix_e1x1_i_8_V_read = ap_const_logic_0;
    }
}

void fire2_expand1x1::thread_matrix_e1x1_i_9_V_read() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st4_fsm_3.read()) && 
         esl_seteq<1,1,1>(exitcond2_fu_255_p2.read(), ap_const_lv1_0) && 
         esl_seteq<1,4,4>(tmp_122_fu_267_p1.read(), ap_const_lv4_9) && 
         !ap_sig_bdd_247.read())) {
        matrix_e1x1_i_9_V_read = ap_const_logic_1;
    } else {
        matrix_e1x1_i_9_V_read = ap_const_logic_0;
    }
}

void fire2_expand1x1::thread_r_1_fu_237_p2() {
    r_1_fu_237_p2 = (!r_reg_198.read().is_01() || !ap_const_lv6_1.is_01())? sc_lv<6>(): (sc_biguint<6>(r_reg_198.read()) + sc_biguint<6>(ap_const_lv6_1));
}

void fire2_expand1x1::thread_tmp_122_fu_267_p1() {
    tmp_122_fu_267_p1 = d_reg_220.read().range(4-1, 0);
}

void fire2_expand1x1::thread_ap_NS_fsm() {
    switch (ap_CS_fsm.read().to_uint64()) {
        case 1 : 
            if (!ap_sig_bdd_260.read()) {
                ap_NS_fsm = ap_ST_st2_fsm_1;
            } else {
                ap_NS_fsm = ap_ST_st1_fsm_0;
            }
            break;
        case 2 : 
            if (!esl_seteq<1,1,1>(ap_const_lv1_0, exitcond4_fu_231_p2.read())) {
                ap_NS_fsm = ap_ST_st1_fsm_0;
            } else {
                ap_NS_fsm = ap_ST_st3_fsm_2;
            }
            break;
        case 4 : 
            if (!esl_seteq<1,1,1>(ap_const_lv1_0, exitcond3_fu_243_p2.read())) {
                ap_NS_fsm = ap_ST_st2_fsm_1;
            } else {
                ap_NS_fsm = ap_ST_st4_fsm_3;
            }
            break;
        case 8 : 
            if ((!ap_sig_bdd_247.read() && !esl_seteq<1,1,1>(exitcond2_fu_255_p2.read(), ap_const_lv1_0))) {
                ap_NS_fsm = ap_ST_st3_fsm_2;
            } else if ((esl_seteq<1,1,1>(exitcond2_fu_255_p2.read(), ap_const_lv1_0) && !ap_sig_bdd_247.read())) {
                ap_NS_fsm = ap_ST_st4_fsm_3;
            } else {
                ap_NS_fsm = ap_ST_st4_fsm_3;
            }
            break;
        default : 
            ap_NS_fsm = "XXXX";
            break;
    }
}

}

