// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2015.4
// Copyright (C) 2015 Xilinx Inc. All rights reserved.
// 
// ===========================================================

#include "fire2_fill_buffer.h"
#include "AESL_pkg.h"

using namespace std;

namespace ap_rtl {

const sc_logic fire2_fill_buffer::ap_const_logic_1 = sc_dt::Log_1;
const sc_logic fire2_fill_buffer::ap_const_logic_0 = sc_dt::Log_0;
const sc_lv<9> fire2_fill_buffer::ap_ST_st1_fsm_0 = "1";
const sc_lv<9> fire2_fill_buffer::ap_ST_pp0_stg0_fsm_1 = "10";
const sc_lv<9> fire2_fill_buffer::ap_ST_pp0_stg1_fsm_2 = "100";
const sc_lv<9> fire2_fill_buffer::ap_ST_pp0_stg2_fsm_3 = "1000";
const sc_lv<9> fire2_fill_buffer::ap_ST_pp0_stg3_fsm_4 = "10000";
const sc_lv<9> fire2_fill_buffer::ap_ST_pp0_stg4_fsm_5 = "100000";
const sc_lv<9> fire2_fill_buffer::ap_ST_pp0_stg5_fsm_6 = "1000000";
const sc_lv<9> fire2_fill_buffer::ap_ST_pp0_stg6_fsm_7 = "10000000";
const sc_lv<9> fire2_fill_buffer::ap_ST_st11_fsm_8 = "100000000";
const sc_lv<32> fire2_fill_buffer::ap_const_lv32_0 = "00000000000000000000000000000000";
const sc_lv<1> fire2_fill_buffer::ap_const_lv1_1 = "1";
const sc_lv<32> fire2_fill_buffer::ap_const_lv32_1 = "1";
const sc_lv<1> fire2_fill_buffer::ap_const_lv1_0 = "0";
const sc_lv<32> fire2_fill_buffer::ap_const_lv32_2 = "10";
const sc_lv<4> fire2_fill_buffer::ap_const_lv4_E = "1110";
const sc_lv<4> fire2_fill_buffer::ap_const_lv4_D = "1101";
const sc_lv<4> fire2_fill_buffer::ap_const_lv4_C = "1100";
const sc_lv<4> fire2_fill_buffer::ap_const_lv4_B = "1011";
const sc_lv<4> fire2_fill_buffer::ap_const_lv4_A = "1010";
const sc_lv<4> fire2_fill_buffer::ap_const_lv4_9 = "1001";
const sc_lv<4> fire2_fill_buffer::ap_const_lv4_8 = "1000";
const sc_lv<4> fire2_fill_buffer::ap_const_lv4_7 = "111";
const sc_lv<4> fire2_fill_buffer::ap_const_lv4_6 = "110";
const sc_lv<4> fire2_fill_buffer::ap_const_lv4_5 = "101";
const sc_lv<4> fire2_fill_buffer::ap_const_lv4_4 = "100";
const sc_lv<4> fire2_fill_buffer::ap_const_lv4_3 = "11";
const sc_lv<4> fire2_fill_buffer::ap_const_lv4_2 = "10";
const sc_lv<4> fire2_fill_buffer::ap_const_lv4_1 = "1";
const sc_lv<4> fire2_fill_buffer::ap_const_lv4_0 = "0000";
const sc_lv<32> fire2_fill_buffer::ap_const_lv32_3 = "11";
const sc_lv<32> fire2_fill_buffer::ap_const_lv32_4 = "100";
const sc_lv<32> fire2_fill_buffer::ap_const_lv32_6 = "110";
const sc_lv<32> fire2_fill_buffer::ap_const_lv32_7 = "111";
const sc_lv<5> fire2_fill_buffer::ap_const_lv5_0 = "00000";
const sc_lv<32> fire2_fill_buffer::ap_const_lv32_5 = "101";
const sc_lv<5> fire2_fill_buffer::ap_const_lv5_10 = "10000";
const sc_lv<5> fire2_fill_buffer::ap_const_lv5_1 = "1";
const sc_lv<59> fire2_fill_buffer::ap_const_lv59_5 = "101";
const sc_lv<7> fire2_fill_buffer::ap_const_lv7_50 = "1010000";
const sc_lv<59> fire2_fill_buffer::ap_const_lv59_1 = "1";
const sc_lv<59> fire2_fill_buffer::ap_const_lv59_2 = "10";
const sc_lv<59> fire2_fill_buffer::ap_const_lv59_3 = "11";
const sc_lv<59> fire2_fill_buffer::ap_const_lv59_4 = "100";
const sc_lv<8> fire2_fill_buffer::ap_const_lv8_90 = "10010000";
const sc_lv<32> fire2_fill_buffer::ap_const_lv32_8 = "1000";

fire2_fill_buffer::fire2_fill_buffer(sc_module_name name) : sc_module(name), mVcdFile(0) {

    SC_METHOD(thread_ap_clk_no_reset_);
    dont_initialize();
    sensitive << ( ap_clk.pos() );

    SC_METHOD(thread_ap_done);
    sensitive << ( ap_start );
    sensitive << ( ap_sig_cseq_ST_st1_fsm_0 );
    sensitive << ( ap_sig_cseq_ST_st11_fsm_8 );

    SC_METHOD(thread_ap_idle);
    sensitive << ( ap_start );
    sensitive << ( ap_sig_cseq_ST_st1_fsm_0 );

    SC_METHOD(thread_ap_ready);
    sensitive << ( ap_sig_cseq_ST_st11_fsm_8 );

    SC_METHOD(thread_ap_sig_bdd_159);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_sig_bdd_198);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_sig_bdd_27);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_sig_bdd_323);
    sensitive << ( matrix_e3x3_i_0_V_empty_n );
    sensitive << ( matrix_e3x3_i_1_V_empty_n );
    sensitive << ( matrix_e3x3_i_2_V_empty_n );
    sensitive << ( matrix_e3x3_i_3_V_empty_n );
    sensitive << ( matrix_e3x3_i_4_V_empty_n );
    sensitive << ( matrix_e3x3_i_5_V_empty_n );
    sensitive << ( matrix_e3x3_i_6_V_empty_n );
    sensitive << ( matrix_e3x3_i_7_V_empty_n );
    sensitive << ( matrix_e3x3_i_8_V_empty_n );
    sensitive << ( matrix_e3x3_i_9_V_empty_n );
    sensitive << ( matrix_e3x3_i_10_V_empty_n );
    sensitive << ( matrix_e3x3_i_11_V_empty_n );
    sensitive << ( matrix_e3x3_i_12_V_empty_n );
    sensitive << ( matrix_e3x3_i_13_V_empty_n );
    sensitive << ( matrix_e3x3_i_14_V_empty_n );
    sensitive << ( matrix_e3x3_i_15_V_empty_n );
    sensitive << ( exitcond2_reg_686 );
    sensitive << ( tmp_104_reg_732 );

    SC_METHOD(thread_ap_sig_bdd_382);
    sensitive << ( exitcond2_reg_686 );
    sensitive << ( ap_reg_ppiten_pp0_it0 );
    sensitive << ( ap_sig_cseq_ST_pp0_stg1_fsm_2 );
    sensitive << ( ap_sig_bdd_323 );

    SC_METHOD(thread_ap_sig_bdd_390);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_sig_bdd_401);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_sig_bdd_411);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_sig_bdd_424);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_sig_bdd_473);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_sig_bdd_596);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_sig_bdd_660);
    sensitive << ( tmp_104_reg_732 );

    SC_METHOD(thread_ap_sig_cseq_ST_pp0_stg0_fsm_1);
    sensitive << ( ap_sig_bdd_159 );

    SC_METHOD(thread_ap_sig_cseq_ST_pp0_stg1_fsm_2);
    sensitive << ( ap_sig_bdd_198 );

    SC_METHOD(thread_ap_sig_cseq_ST_pp0_stg2_fsm_3);
    sensitive << ( ap_sig_bdd_390 );

    SC_METHOD(thread_ap_sig_cseq_ST_pp0_stg3_fsm_4);
    sensitive << ( ap_sig_bdd_401 );

    SC_METHOD(thread_ap_sig_cseq_ST_pp0_stg4_fsm_5);
    sensitive << ( ap_sig_bdd_473 );

    SC_METHOD(thread_ap_sig_cseq_ST_pp0_stg5_fsm_6);
    sensitive << ( ap_sig_bdd_411 );

    SC_METHOD(thread_ap_sig_cseq_ST_pp0_stg6_fsm_7);
    sensitive << ( ap_sig_bdd_424 );

    SC_METHOD(thread_ap_sig_cseq_ST_st11_fsm_8);
    sensitive << ( ap_sig_bdd_596 );

    SC_METHOD(thread_ap_sig_cseq_ST_st1_fsm_0);
    sensitive << ( ap_sig_bdd_27 );

    SC_METHOD(thread_d_1_fu_570_p2);
    sensitive << ( d_phi_fu_518_p4 );

    SC_METHOD(thread_d_phi_fu_518_p4);
    sensitive << ( d_reg_514 );
    sensitive << ( exitcond2_reg_686 );
    sensitive << ( ap_sig_cseq_ST_pp0_stg0_fsm_1 );
    sensitive << ( ap_reg_ppiten_pp0_it1 );
    sensitive << ( d_1_reg_690 );

    SC_METHOD(thread_exitcond2_fu_564_p2);
    sensitive << ( ap_sig_cseq_ST_pp0_stg0_fsm_1 );
    sensitive << ( ap_reg_ppiten_pp0_it0 );
    sensitive << ( d_phi_fu_518_p4 );

    SC_METHOD(thread_line_buffer_0_0_address0);
    sensitive << ( ap_reg_ppiten_pp0_it0 );
    sensitive << ( tmp_reg_695 );
    sensitive << ( ap_sig_cseq_ST_pp0_stg2_fsm_3 );

    SC_METHOD(thread_line_buffer_0_0_ce0);
    sensitive << ( ap_reg_ppiten_pp0_it0 );
    sensitive << ( ap_sig_cseq_ST_pp0_stg2_fsm_3 );

    SC_METHOD(thread_line_buffer_0_0_d0);
    sensitive << ( ap_reg_ppiten_pp0_it0 );
    sensitive << ( ap_sig_cseq_ST_pp0_stg2_fsm_3 );
    sensitive << ( ap_reg_phiprechg_tmp_4_reg_526pp0_it0 );

    SC_METHOD(thread_line_buffer_0_0_we0);
    sensitive << ( exitcond2_reg_686 );
    sensitive << ( ap_reg_ppiten_pp0_it0 );
    sensitive << ( ap_sig_cseq_ST_pp0_stg2_fsm_3 );

    SC_METHOD(thread_line_buffer_0_54_address0);
    sensitive << ( ap_sig_cseq_ST_pp0_stg0_fsm_1 );
    sensitive << ( ap_reg_ppiten_pp0_it0 );
    sensitive << ( tmp_fu_576_p1 );

    SC_METHOD(thread_line_buffer_0_54_ce0);
    sensitive << ( ap_sig_cseq_ST_pp0_stg0_fsm_1 );
    sensitive << ( ap_reg_ppiten_pp0_it0 );

    SC_METHOD(thread_line_buffer_1_0_address0);
    sensitive << ( ap_reg_ppiten_pp0_it0 );
    sensitive << ( tmp_reg_695 );
    sensitive << ( ap_sig_cseq_ST_pp0_stg2_fsm_3 );

    SC_METHOD(thread_line_buffer_1_0_ce0);
    sensitive << ( ap_reg_ppiten_pp0_it0 );
    sensitive << ( ap_sig_cseq_ST_pp0_stg2_fsm_3 );

    SC_METHOD(thread_line_buffer_1_0_d0);
    sensitive << ( ap_reg_ppiten_pp0_it0 );
    sensitive << ( line_buffer_0_54_load_reg_748 );
    sensitive << ( ap_sig_cseq_ST_pp0_stg2_fsm_3 );

    SC_METHOD(thread_line_buffer_1_0_we0);
    sensitive << ( exitcond2_reg_686 );
    sensitive << ( ap_reg_ppiten_pp0_it0 );
    sensitive << ( ap_sig_cseq_ST_pp0_stg2_fsm_3 );

    SC_METHOD(thread_line_buffer_1_54_address0);
    sensitive << ( ap_sig_cseq_ST_pp0_stg0_fsm_1 );
    sensitive << ( ap_reg_ppiten_pp0_it0 );
    sensitive << ( tmp_fu_576_p1 );

    SC_METHOD(thread_line_buffer_1_54_ce0);
    sensitive << ( ap_sig_cseq_ST_pp0_stg0_fsm_1 );
    sensitive << ( ap_reg_ppiten_pp0_it0 );

    SC_METHOD(thread_line_buffer_2_0_address0);
    sensitive << ( ap_reg_ppiten_pp0_it0 );
    sensitive << ( tmp_reg_695 );
    sensitive << ( ap_sig_cseq_ST_pp0_stg2_fsm_3 );

    SC_METHOD(thread_line_buffer_2_0_ce0);
    sensitive << ( ap_reg_ppiten_pp0_it0 );
    sensitive << ( ap_sig_cseq_ST_pp0_stg2_fsm_3 );

    SC_METHOD(thread_line_buffer_2_0_d0);
    sensitive << ( ap_reg_ppiten_pp0_it0 );
    sensitive << ( line_buffer_1_54_load_reg_741 );
    sensitive << ( ap_sig_cseq_ST_pp0_stg2_fsm_3 );

    SC_METHOD(thread_line_buffer_2_0_we0);
    sensitive << ( exitcond2_reg_686 );
    sensitive << ( ap_reg_ppiten_pp0_it0 );
    sensitive << ( ap_sig_cseq_ST_pp0_stg2_fsm_3 );

    SC_METHOD(thread_line_buffer_2_54_address0);
    sensitive << ( ap_reg_ppiten_pp0_it0 );
    sensitive << ( tmp_reg_695 );
    sensitive << ( ap_sig_cseq_ST_pp0_stg2_fsm_3 );

    SC_METHOD(thread_line_buffer_2_54_ce0);
    sensitive << ( ap_reg_ppiten_pp0_it0 );
    sensitive << ( ap_sig_cseq_ST_pp0_stg2_fsm_3 );

    SC_METHOD(thread_matrix_e3x3_i_0_V_read);
    sensitive << ( exitcond2_reg_686 );
    sensitive << ( ap_reg_ppiten_pp0_it0 );
    sensitive << ( tmp_104_reg_732 );
    sensitive << ( ap_sig_cseq_ST_pp0_stg1_fsm_2 );
    sensitive << ( ap_sig_bdd_323 );

    SC_METHOD(thread_matrix_e3x3_i_10_V_read);
    sensitive << ( exitcond2_reg_686 );
    sensitive << ( ap_reg_ppiten_pp0_it0 );
    sensitive << ( tmp_104_reg_732 );
    sensitive << ( ap_sig_cseq_ST_pp0_stg1_fsm_2 );
    sensitive << ( ap_sig_bdd_323 );

    SC_METHOD(thread_matrix_e3x3_i_11_V_read);
    sensitive << ( exitcond2_reg_686 );
    sensitive << ( ap_reg_ppiten_pp0_it0 );
    sensitive << ( tmp_104_reg_732 );
    sensitive << ( ap_sig_cseq_ST_pp0_stg1_fsm_2 );
    sensitive << ( ap_sig_bdd_323 );

    SC_METHOD(thread_matrix_e3x3_i_12_V_read);
    sensitive << ( exitcond2_reg_686 );
    sensitive << ( ap_reg_ppiten_pp0_it0 );
    sensitive << ( tmp_104_reg_732 );
    sensitive << ( ap_sig_cseq_ST_pp0_stg1_fsm_2 );
    sensitive << ( ap_sig_bdd_323 );

    SC_METHOD(thread_matrix_e3x3_i_13_V_read);
    sensitive << ( exitcond2_reg_686 );
    sensitive << ( ap_reg_ppiten_pp0_it0 );
    sensitive << ( tmp_104_reg_732 );
    sensitive << ( ap_sig_cseq_ST_pp0_stg1_fsm_2 );
    sensitive << ( ap_sig_bdd_323 );

    SC_METHOD(thread_matrix_e3x3_i_14_V_read);
    sensitive << ( exitcond2_reg_686 );
    sensitive << ( ap_reg_ppiten_pp0_it0 );
    sensitive << ( tmp_104_reg_732 );
    sensitive << ( ap_sig_cseq_ST_pp0_stg1_fsm_2 );
    sensitive << ( ap_sig_bdd_323 );

    SC_METHOD(thread_matrix_e3x3_i_15_V_read);
    sensitive << ( exitcond2_reg_686 );
    sensitive << ( ap_reg_ppiten_pp0_it0 );
    sensitive << ( tmp_104_reg_732 );
    sensitive << ( ap_sig_cseq_ST_pp0_stg1_fsm_2 );
    sensitive << ( ap_sig_bdd_323 );

    SC_METHOD(thread_matrix_e3x3_i_1_V_read);
    sensitive << ( exitcond2_reg_686 );
    sensitive << ( ap_reg_ppiten_pp0_it0 );
    sensitive << ( tmp_104_reg_732 );
    sensitive << ( ap_sig_cseq_ST_pp0_stg1_fsm_2 );
    sensitive << ( ap_sig_bdd_323 );

    SC_METHOD(thread_matrix_e3x3_i_2_V_read);
    sensitive << ( exitcond2_reg_686 );
    sensitive << ( ap_reg_ppiten_pp0_it0 );
    sensitive << ( tmp_104_reg_732 );
    sensitive << ( ap_sig_cseq_ST_pp0_stg1_fsm_2 );
    sensitive << ( ap_sig_bdd_323 );

    SC_METHOD(thread_matrix_e3x3_i_3_V_read);
    sensitive << ( exitcond2_reg_686 );
    sensitive << ( ap_reg_ppiten_pp0_it0 );
    sensitive << ( tmp_104_reg_732 );
    sensitive << ( ap_sig_cseq_ST_pp0_stg1_fsm_2 );
    sensitive << ( ap_sig_bdd_323 );

    SC_METHOD(thread_matrix_e3x3_i_4_V_read);
    sensitive << ( exitcond2_reg_686 );
    sensitive << ( ap_reg_ppiten_pp0_it0 );
    sensitive << ( tmp_104_reg_732 );
    sensitive << ( ap_sig_cseq_ST_pp0_stg1_fsm_2 );
    sensitive << ( ap_sig_bdd_323 );

    SC_METHOD(thread_matrix_e3x3_i_5_V_read);
    sensitive << ( exitcond2_reg_686 );
    sensitive << ( ap_reg_ppiten_pp0_it0 );
    sensitive << ( tmp_104_reg_732 );
    sensitive << ( ap_sig_cseq_ST_pp0_stg1_fsm_2 );
    sensitive << ( ap_sig_bdd_323 );

    SC_METHOD(thread_matrix_e3x3_i_6_V_read);
    sensitive << ( exitcond2_reg_686 );
    sensitive << ( ap_reg_ppiten_pp0_it0 );
    sensitive << ( tmp_104_reg_732 );
    sensitive << ( ap_sig_cseq_ST_pp0_stg1_fsm_2 );
    sensitive << ( ap_sig_bdd_323 );

    SC_METHOD(thread_matrix_e3x3_i_7_V_read);
    sensitive << ( exitcond2_reg_686 );
    sensitive << ( ap_reg_ppiten_pp0_it0 );
    sensitive << ( tmp_104_reg_732 );
    sensitive << ( ap_sig_cseq_ST_pp0_stg1_fsm_2 );
    sensitive << ( ap_sig_bdd_323 );

    SC_METHOD(thread_matrix_e3x3_i_8_V_read);
    sensitive << ( exitcond2_reg_686 );
    sensitive << ( ap_reg_ppiten_pp0_it0 );
    sensitive << ( tmp_104_reg_732 );
    sensitive << ( ap_sig_cseq_ST_pp0_stg1_fsm_2 );
    sensitive << ( ap_sig_bdd_323 );

    SC_METHOD(thread_matrix_e3x3_i_9_V_read);
    sensitive << ( exitcond2_reg_686 );
    sensitive << ( ap_reg_ppiten_pp0_it0 );
    sensitive << ( tmp_104_reg_732 );
    sensitive << ( ap_sig_cseq_ST_pp0_stg1_fsm_2 );
    sensitive << ( ap_sig_bdd_323 );

    SC_METHOD(thread_tmp_104_fu_602_p1);
    sensitive << ( d_phi_fu_518_p4 );

    SC_METHOD(thread_tmp_67_cast_fu_588_p1);
    sensitive << ( tmp_67_fu_582_p2 );

    SC_METHOD(thread_tmp_67_fu_582_p2);
    sensitive << ( d_phi_fu_518_p4 );

    SC_METHOD(thread_tmp_68_fu_628_p3);
    sensitive << ( d_reg_514 );

    SC_METHOD(thread_tmp_69_cast1_fu_620_p1);
    sensitive << ( tmp_67_reg_704 );

    SC_METHOD(thread_tmp_69_cast_fu_623_p1);
    sensitive << ( tmp_69_cast1_fu_620_p1 );

    SC_METHOD(thread_tmp_69_fu_637_p3);
    sensitive << ( d_reg_514 );

    SC_METHOD(thread_tmp_70_fu_610_p2);
    sensitive << ( tmp_cast1_fu_606_p1 );

    SC_METHOD(thread_tmp_71_cast_fu_616_p1);
    sensitive << ( tmp_70_reg_736 );

    SC_METHOD(thread_tmp_71_fu_650_p3);
    sensitive << ( d_reg_514 );

    SC_METHOD(thread_tmp_72_fu_659_p3);
    sensitive << ( d_reg_514 );

    SC_METHOD(thread_tmp_73_cast1_fu_678_p1);
    sensitive << ( ap_reg_ppstg_tmp_67_reg_704_pp0_it1 );

    SC_METHOD(thread_tmp_73_cast_fu_681_p1);
    sensitive << ( tmp_73_cast1_fu_678_p1 );

    SC_METHOD(thread_tmp_73_fu_668_p2);
    sensitive << ( tmp_cast_fu_646_p1 );

    SC_METHOD(thread_tmp_74_fu_593_p3);
    sensitive << ( d_phi_fu_518_p4 );

    SC_METHOD(thread_tmp_75_cast_fu_674_p1);
    sensitive << ( tmp_73_reg_860 );

    SC_METHOD(thread_tmp_cast1_fu_606_p1);
    sensitive << ( d_reg_514 );

    SC_METHOD(thread_tmp_cast_fu_646_p1);
    sensitive << ( d_reg_514 );

    SC_METHOD(thread_tmp_fu_576_p1);
    sensitive << ( d_phi_fu_518_p4 );

    SC_METHOD(thread_window_buffer_address0);
    sensitive << ( ap_sig_cseq_ST_pp0_stg0_fsm_1 );
    sensitive << ( ap_reg_ppiten_pp0_it0 );
    sensitive << ( ap_reg_ppiten_pp0_it1 );
    sensitive << ( window_buffer_addr_10_reg_716 );
    sensitive << ( ap_sig_cseq_ST_pp0_stg1_fsm_2 );
    sensitive << ( ap_sig_cseq_ST_pp0_stg2_fsm_3 );
    sensitive << ( ap_sig_cseq_ST_pp0_stg3_fsm_4 );
    sensitive << ( ap_sig_cseq_ST_pp0_stg5_fsm_6 );
    sensitive << ( ap_sig_cseq_ST_pp0_stg6_fsm_7 );
    sensitive << ( tmp_67_cast_fu_588_p1 );
    sensitive << ( tmp_71_cast_fu_616_p1 );
    sensitive << ( tmp_69_cast_fu_623_p1 );
    sensitive << ( ap_sig_cseq_ST_pp0_stg4_fsm_5 );
    sensitive << ( tmp_69_fu_637_p3 );
    sensitive << ( tmp_72_fu_659_p3 );
    sensitive << ( tmp_73_cast_fu_681_p1 );

    SC_METHOD(thread_window_buffer_address1);
    sensitive << ( ap_sig_cseq_ST_pp0_stg0_fsm_1 );
    sensitive << ( ap_reg_ppiten_pp0_it0 );
    sensitive << ( window_buffer_addr_reg_710 );
    sensitive << ( window_buffer_addr_1_reg_845 );
    sensitive << ( ap_sig_cseq_ST_pp0_stg2_fsm_3 );
    sensitive << ( ap_sig_cseq_ST_pp0_stg3_fsm_4 );
    sensitive << ( ap_sig_cseq_ST_pp0_stg5_fsm_6 );
    sensitive << ( ap_sig_cseq_ST_pp0_stg6_fsm_7 );
    sensitive << ( tmp_74_fu_593_p3 );
    sensitive << ( tmp_68_fu_628_p3 );
    sensitive << ( ap_sig_cseq_ST_pp0_stg4_fsm_5 );
    sensitive << ( tmp_71_fu_650_p3 );
    sensitive << ( tmp_75_cast_fu_674_p1 );

    SC_METHOD(thread_window_buffer_ce0);
    sensitive << ( ap_sig_cseq_ST_pp0_stg0_fsm_1 );
    sensitive << ( ap_reg_ppiten_pp0_it0 );
    sensitive << ( ap_reg_ppiten_pp0_it1 );
    sensitive << ( ap_sig_cseq_ST_pp0_stg1_fsm_2 );
    sensitive << ( ap_sig_bdd_323 );
    sensitive << ( ap_sig_cseq_ST_pp0_stg2_fsm_3 );
    sensitive << ( ap_sig_cseq_ST_pp0_stg3_fsm_4 );
    sensitive << ( ap_sig_cseq_ST_pp0_stg5_fsm_6 );
    sensitive << ( ap_sig_cseq_ST_pp0_stg6_fsm_7 );
    sensitive << ( ap_sig_cseq_ST_pp0_stg4_fsm_5 );

    SC_METHOD(thread_window_buffer_ce1);
    sensitive << ( ap_sig_cseq_ST_pp0_stg0_fsm_1 );
    sensitive << ( ap_reg_ppiten_pp0_it0 );
    sensitive << ( ap_sig_cseq_ST_pp0_stg2_fsm_3 );
    sensitive << ( ap_sig_cseq_ST_pp0_stg3_fsm_4 );
    sensitive << ( ap_sig_cseq_ST_pp0_stg5_fsm_6 );
    sensitive << ( ap_sig_cseq_ST_pp0_stg6_fsm_7 );
    sensitive << ( ap_sig_cseq_ST_pp0_stg4_fsm_5 );

    SC_METHOD(thread_window_buffer_d0);
    sensitive << ( ap_reg_ppiten_pp0_it0 );
    sensitive << ( ap_reg_ppiten_pp0_it1 );
    sensitive << ( ap_sig_cseq_ST_pp0_stg1_fsm_2 );
    sensitive << ( line_buffer_1_54_load_reg_741 );
    sensitive << ( line_buffer_0_54_load_reg_748 );
    sensitive << ( ap_sig_cseq_ST_pp0_stg2_fsm_3 );
    sensitive << ( line_buffer_2_54_load_reg_855 );
    sensitive << ( ap_sig_cseq_ST_pp0_stg3_fsm_4 );
    sensitive << ( ap_sig_cseq_ST_pp0_stg5_fsm_6 );
    sensitive << ( ap_sig_cseq_ST_pp0_stg6_fsm_7 );
    sensitive << ( ap_sig_cseq_ST_pp0_stg4_fsm_5 );

    SC_METHOD(thread_window_buffer_d1);
    sensitive << ( ap_reg_ppiten_pp0_it0 );
    sensitive << ( line_buffer_1_54_load_reg_741 );
    sensitive << ( line_buffer_0_54_load_reg_748 );
    sensitive << ( window_buffer_load_reg_835 );
    sensitive << ( window_buffer_load_1_reg_840 );
    sensitive << ( ap_sig_cseq_ST_pp0_stg2_fsm_3 );
    sensitive << ( ap_sig_cseq_ST_pp0_stg3_fsm_4 );
    sensitive << ( ap_sig_cseq_ST_pp0_stg5_fsm_6 );
    sensitive << ( ap_sig_cseq_ST_pp0_stg6_fsm_7 );
    sensitive << ( ap_sig_cseq_ST_pp0_stg4_fsm_5 );

    SC_METHOD(thread_window_buffer_we0);
    sensitive << ( exitcond2_reg_686 );
    sensitive << ( ap_reg_ppiten_pp0_it0 );
    sensitive << ( ap_reg_ppiten_pp0_it1 );
    sensitive << ( ap_reg_ppstg_exitcond2_reg_686_pp0_it1 );
    sensitive << ( ap_sig_cseq_ST_pp0_stg1_fsm_2 );
    sensitive << ( ap_sig_bdd_323 );
    sensitive << ( ap_sig_cseq_ST_pp0_stg2_fsm_3 );
    sensitive << ( ap_sig_cseq_ST_pp0_stg3_fsm_4 );
    sensitive << ( ap_sig_cseq_ST_pp0_stg5_fsm_6 );
    sensitive << ( ap_sig_cseq_ST_pp0_stg6_fsm_7 );
    sensitive << ( ap_sig_cseq_ST_pp0_stg4_fsm_5 );

    SC_METHOD(thread_window_buffer_we1);
    sensitive << ( exitcond2_reg_686 );
    sensitive << ( ap_reg_ppiten_pp0_it0 );
    sensitive << ( ap_sig_cseq_ST_pp0_stg2_fsm_3 );
    sensitive << ( ap_sig_cseq_ST_pp0_stg3_fsm_4 );
    sensitive << ( ap_sig_cseq_ST_pp0_stg5_fsm_6 );
    sensitive << ( ap_sig_cseq_ST_pp0_stg6_fsm_7 );
    sensitive << ( ap_sig_cseq_ST_pp0_stg4_fsm_5 );

    SC_METHOD(thread_ap_NS_fsm);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm );
    sensitive << ( exitcond2_fu_564_p2 );
    sensitive << ( ap_reg_ppiten_pp0_it0 );
    sensitive << ( ap_reg_ppiten_pp0_it1 );
    sensitive << ( ap_sig_cseq_ST_pp0_stg1_fsm_2 );
    sensitive << ( ap_sig_bdd_323 );

    ap_CS_fsm = "000000001";
    ap_reg_ppiten_pp0_it0 = SC_LOGIC_0;
    ap_reg_ppiten_pp0_it1 = SC_LOGIC_0;
    static int apTFileNum = 0;
    stringstream apTFilenSS;
    apTFilenSS << "fire2_fill_buffer_sc_trace_" << apTFileNum ++;
    string apTFn = apTFilenSS.str();
    mVcdFile = sc_create_vcd_trace_file(apTFn.c_str());
    mVcdFile->set_time_unit(1, SC_PS);
    if (1) {
#ifdef __HLS_TRACE_LEVEL_PORT_HIER__
    sc_trace(mVcdFile, ap_clk, "(port)ap_clk");
    sc_trace(mVcdFile, ap_rst, "(port)ap_rst");
    sc_trace(mVcdFile, ap_start, "(port)ap_start");
    sc_trace(mVcdFile, ap_done, "(port)ap_done");
    sc_trace(mVcdFile, ap_idle, "(port)ap_idle");
    sc_trace(mVcdFile, ap_ready, "(port)ap_ready");
    sc_trace(mVcdFile, matrix_e3x3_i_0_V_dout, "(port)matrix_e3x3_i_0_V_dout");
    sc_trace(mVcdFile, matrix_e3x3_i_0_V_empty_n, "(port)matrix_e3x3_i_0_V_empty_n");
    sc_trace(mVcdFile, matrix_e3x3_i_0_V_read, "(port)matrix_e3x3_i_0_V_read");
    sc_trace(mVcdFile, matrix_e3x3_i_1_V_dout, "(port)matrix_e3x3_i_1_V_dout");
    sc_trace(mVcdFile, matrix_e3x3_i_1_V_empty_n, "(port)matrix_e3x3_i_1_V_empty_n");
    sc_trace(mVcdFile, matrix_e3x3_i_1_V_read, "(port)matrix_e3x3_i_1_V_read");
    sc_trace(mVcdFile, matrix_e3x3_i_2_V_dout, "(port)matrix_e3x3_i_2_V_dout");
    sc_trace(mVcdFile, matrix_e3x3_i_2_V_empty_n, "(port)matrix_e3x3_i_2_V_empty_n");
    sc_trace(mVcdFile, matrix_e3x3_i_2_V_read, "(port)matrix_e3x3_i_2_V_read");
    sc_trace(mVcdFile, matrix_e3x3_i_3_V_dout, "(port)matrix_e3x3_i_3_V_dout");
    sc_trace(mVcdFile, matrix_e3x3_i_3_V_empty_n, "(port)matrix_e3x3_i_3_V_empty_n");
    sc_trace(mVcdFile, matrix_e3x3_i_3_V_read, "(port)matrix_e3x3_i_3_V_read");
    sc_trace(mVcdFile, matrix_e3x3_i_4_V_dout, "(port)matrix_e3x3_i_4_V_dout");
    sc_trace(mVcdFile, matrix_e3x3_i_4_V_empty_n, "(port)matrix_e3x3_i_4_V_empty_n");
    sc_trace(mVcdFile, matrix_e3x3_i_4_V_read, "(port)matrix_e3x3_i_4_V_read");
    sc_trace(mVcdFile, matrix_e3x3_i_5_V_dout, "(port)matrix_e3x3_i_5_V_dout");
    sc_trace(mVcdFile, matrix_e3x3_i_5_V_empty_n, "(port)matrix_e3x3_i_5_V_empty_n");
    sc_trace(mVcdFile, matrix_e3x3_i_5_V_read, "(port)matrix_e3x3_i_5_V_read");
    sc_trace(mVcdFile, matrix_e3x3_i_6_V_dout, "(port)matrix_e3x3_i_6_V_dout");
    sc_trace(mVcdFile, matrix_e3x3_i_6_V_empty_n, "(port)matrix_e3x3_i_6_V_empty_n");
    sc_trace(mVcdFile, matrix_e3x3_i_6_V_read, "(port)matrix_e3x3_i_6_V_read");
    sc_trace(mVcdFile, matrix_e3x3_i_7_V_dout, "(port)matrix_e3x3_i_7_V_dout");
    sc_trace(mVcdFile, matrix_e3x3_i_7_V_empty_n, "(port)matrix_e3x3_i_7_V_empty_n");
    sc_trace(mVcdFile, matrix_e3x3_i_7_V_read, "(port)matrix_e3x3_i_7_V_read");
    sc_trace(mVcdFile, matrix_e3x3_i_8_V_dout, "(port)matrix_e3x3_i_8_V_dout");
    sc_trace(mVcdFile, matrix_e3x3_i_8_V_empty_n, "(port)matrix_e3x3_i_8_V_empty_n");
    sc_trace(mVcdFile, matrix_e3x3_i_8_V_read, "(port)matrix_e3x3_i_8_V_read");
    sc_trace(mVcdFile, matrix_e3x3_i_9_V_dout, "(port)matrix_e3x3_i_9_V_dout");
    sc_trace(mVcdFile, matrix_e3x3_i_9_V_empty_n, "(port)matrix_e3x3_i_9_V_empty_n");
    sc_trace(mVcdFile, matrix_e3x3_i_9_V_read, "(port)matrix_e3x3_i_9_V_read");
    sc_trace(mVcdFile, matrix_e3x3_i_10_V_dout, "(port)matrix_e3x3_i_10_V_dout");
    sc_trace(mVcdFile, matrix_e3x3_i_10_V_empty_n, "(port)matrix_e3x3_i_10_V_empty_n");
    sc_trace(mVcdFile, matrix_e3x3_i_10_V_read, "(port)matrix_e3x3_i_10_V_read");
    sc_trace(mVcdFile, matrix_e3x3_i_11_V_dout, "(port)matrix_e3x3_i_11_V_dout");
    sc_trace(mVcdFile, matrix_e3x3_i_11_V_empty_n, "(port)matrix_e3x3_i_11_V_empty_n");
    sc_trace(mVcdFile, matrix_e3x3_i_11_V_read, "(port)matrix_e3x3_i_11_V_read");
    sc_trace(mVcdFile, matrix_e3x3_i_12_V_dout, "(port)matrix_e3x3_i_12_V_dout");
    sc_trace(mVcdFile, matrix_e3x3_i_12_V_empty_n, "(port)matrix_e3x3_i_12_V_empty_n");
    sc_trace(mVcdFile, matrix_e3x3_i_12_V_read, "(port)matrix_e3x3_i_12_V_read");
    sc_trace(mVcdFile, matrix_e3x3_i_13_V_dout, "(port)matrix_e3x3_i_13_V_dout");
    sc_trace(mVcdFile, matrix_e3x3_i_13_V_empty_n, "(port)matrix_e3x3_i_13_V_empty_n");
    sc_trace(mVcdFile, matrix_e3x3_i_13_V_read, "(port)matrix_e3x3_i_13_V_read");
    sc_trace(mVcdFile, matrix_e3x3_i_14_V_dout, "(port)matrix_e3x3_i_14_V_dout");
    sc_trace(mVcdFile, matrix_e3x3_i_14_V_empty_n, "(port)matrix_e3x3_i_14_V_empty_n");
    sc_trace(mVcdFile, matrix_e3x3_i_14_V_read, "(port)matrix_e3x3_i_14_V_read");
    sc_trace(mVcdFile, matrix_e3x3_i_15_V_dout, "(port)matrix_e3x3_i_15_V_dout");
    sc_trace(mVcdFile, matrix_e3x3_i_15_V_empty_n, "(port)matrix_e3x3_i_15_V_empty_n");
    sc_trace(mVcdFile, matrix_e3x3_i_15_V_read, "(port)matrix_e3x3_i_15_V_read");
    sc_trace(mVcdFile, line_buffer_0_0_address0, "(port)line_buffer_0_0_address0");
    sc_trace(mVcdFile, line_buffer_0_0_ce0, "(port)line_buffer_0_0_ce0");
    sc_trace(mVcdFile, line_buffer_0_0_we0, "(port)line_buffer_0_0_we0");
    sc_trace(mVcdFile, line_buffer_0_0_d0, "(port)line_buffer_0_0_d0");
    sc_trace(mVcdFile, line_buffer_0_54_address0, "(port)line_buffer_0_54_address0");
    sc_trace(mVcdFile, line_buffer_0_54_ce0, "(port)line_buffer_0_54_ce0");
    sc_trace(mVcdFile, line_buffer_0_54_q0, "(port)line_buffer_0_54_q0");
    sc_trace(mVcdFile, line_buffer_1_0_address0, "(port)line_buffer_1_0_address0");
    sc_trace(mVcdFile, line_buffer_1_0_ce0, "(port)line_buffer_1_0_ce0");
    sc_trace(mVcdFile, line_buffer_1_0_we0, "(port)line_buffer_1_0_we0");
    sc_trace(mVcdFile, line_buffer_1_0_d0, "(port)line_buffer_1_0_d0");
    sc_trace(mVcdFile, line_buffer_1_54_address0, "(port)line_buffer_1_54_address0");
    sc_trace(mVcdFile, line_buffer_1_54_ce0, "(port)line_buffer_1_54_ce0");
    sc_trace(mVcdFile, line_buffer_1_54_q0, "(port)line_buffer_1_54_q0");
    sc_trace(mVcdFile, line_buffer_2_0_address0, "(port)line_buffer_2_0_address0");
    sc_trace(mVcdFile, line_buffer_2_0_ce0, "(port)line_buffer_2_0_ce0");
    sc_trace(mVcdFile, line_buffer_2_0_we0, "(port)line_buffer_2_0_we0");
    sc_trace(mVcdFile, line_buffer_2_0_d0, "(port)line_buffer_2_0_d0");
    sc_trace(mVcdFile, line_buffer_2_54_address0, "(port)line_buffer_2_54_address0");
    sc_trace(mVcdFile, line_buffer_2_54_ce0, "(port)line_buffer_2_54_ce0");
    sc_trace(mVcdFile, line_buffer_2_54_q0, "(port)line_buffer_2_54_q0");
    sc_trace(mVcdFile, window_buffer_address0, "(port)window_buffer_address0");
    sc_trace(mVcdFile, window_buffer_ce0, "(port)window_buffer_ce0");
    sc_trace(mVcdFile, window_buffer_we0, "(port)window_buffer_we0");
    sc_trace(mVcdFile, window_buffer_d0, "(port)window_buffer_d0");
    sc_trace(mVcdFile, window_buffer_q0, "(port)window_buffer_q0");
    sc_trace(mVcdFile, window_buffer_address1, "(port)window_buffer_address1");
    sc_trace(mVcdFile, window_buffer_ce1, "(port)window_buffer_ce1");
    sc_trace(mVcdFile, window_buffer_we1, "(port)window_buffer_we1");
    sc_trace(mVcdFile, window_buffer_d1, "(port)window_buffer_d1");
    sc_trace(mVcdFile, window_buffer_q1, "(port)window_buffer_q1");
#endif
#ifdef __HLS_TRACE_LEVEL_INT__
    sc_trace(mVcdFile, ap_CS_fsm, "ap_CS_fsm");
    sc_trace(mVcdFile, ap_sig_cseq_ST_st1_fsm_0, "ap_sig_cseq_ST_st1_fsm_0");
    sc_trace(mVcdFile, ap_sig_bdd_27, "ap_sig_bdd_27");
    sc_trace(mVcdFile, d_reg_514, "d_reg_514");
    sc_trace(mVcdFile, exitcond2_fu_564_p2, "exitcond2_fu_564_p2");
    sc_trace(mVcdFile, exitcond2_reg_686, "exitcond2_reg_686");
    sc_trace(mVcdFile, ap_sig_cseq_ST_pp0_stg0_fsm_1, "ap_sig_cseq_ST_pp0_stg0_fsm_1");
    sc_trace(mVcdFile, ap_sig_bdd_159, "ap_sig_bdd_159");
    sc_trace(mVcdFile, ap_reg_ppiten_pp0_it0, "ap_reg_ppiten_pp0_it0");
    sc_trace(mVcdFile, ap_reg_ppiten_pp0_it1, "ap_reg_ppiten_pp0_it1");
    sc_trace(mVcdFile, ap_reg_ppstg_exitcond2_reg_686_pp0_it1, "ap_reg_ppstg_exitcond2_reg_686_pp0_it1");
    sc_trace(mVcdFile, d_1_fu_570_p2, "d_1_fu_570_p2");
    sc_trace(mVcdFile, d_1_reg_690, "d_1_reg_690");
    sc_trace(mVcdFile, tmp_fu_576_p1, "tmp_fu_576_p1");
    sc_trace(mVcdFile, tmp_reg_695, "tmp_reg_695");
    sc_trace(mVcdFile, tmp_67_fu_582_p2, "tmp_67_fu_582_p2");
    sc_trace(mVcdFile, tmp_67_reg_704, "tmp_67_reg_704");
    sc_trace(mVcdFile, ap_reg_ppstg_tmp_67_reg_704_pp0_it1, "ap_reg_ppstg_tmp_67_reg_704_pp0_it1");
    sc_trace(mVcdFile, window_buffer_addr_reg_710, "window_buffer_addr_reg_710");
    sc_trace(mVcdFile, window_buffer_addr_10_reg_716, "window_buffer_addr_10_reg_716");
    sc_trace(mVcdFile, tmp_104_fu_602_p1, "tmp_104_fu_602_p1");
    sc_trace(mVcdFile, tmp_104_reg_732, "tmp_104_reg_732");
    sc_trace(mVcdFile, tmp_70_fu_610_p2, "tmp_70_fu_610_p2");
    sc_trace(mVcdFile, tmp_70_reg_736, "tmp_70_reg_736");
    sc_trace(mVcdFile, ap_sig_cseq_ST_pp0_stg1_fsm_2, "ap_sig_cseq_ST_pp0_stg1_fsm_2");
    sc_trace(mVcdFile, ap_sig_bdd_198, "ap_sig_bdd_198");
    sc_trace(mVcdFile, ap_sig_bdd_323, "ap_sig_bdd_323");
    sc_trace(mVcdFile, line_buffer_1_54_load_reg_741, "line_buffer_1_54_load_reg_741");
    sc_trace(mVcdFile, line_buffer_0_54_load_reg_748, "line_buffer_0_54_load_reg_748");
    sc_trace(mVcdFile, window_buffer_load_reg_835, "window_buffer_load_reg_835");
    sc_trace(mVcdFile, window_buffer_load_1_reg_840, "window_buffer_load_1_reg_840");
    sc_trace(mVcdFile, window_buffer_addr_1_reg_845, "window_buffer_addr_1_reg_845");
    sc_trace(mVcdFile, ap_sig_cseq_ST_pp0_stg2_fsm_3, "ap_sig_cseq_ST_pp0_stg2_fsm_3");
    sc_trace(mVcdFile, ap_sig_bdd_390, "ap_sig_bdd_390");
    sc_trace(mVcdFile, line_buffer_2_54_load_reg_855, "line_buffer_2_54_load_reg_855");
    sc_trace(mVcdFile, ap_sig_cseq_ST_pp0_stg3_fsm_4, "ap_sig_cseq_ST_pp0_stg3_fsm_4");
    sc_trace(mVcdFile, ap_sig_bdd_401, "ap_sig_bdd_401");
    sc_trace(mVcdFile, tmp_73_fu_668_p2, "tmp_73_fu_668_p2");
    sc_trace(mVcdFile, tmp_73_reg_860, "tmp_73_reg_860");
    sc_trace(mVcdFile, ap_sig_cseq_ST_pp0_stg5_fsm_6, "ap_sig_cseq_ST_pp0_stg5_fsm_6");
    sc_trace(mVcdFile, ap_sig_bdd_411, "ap_sig_bdd_411");
    sc_trace(mVcdFile, ap_sig_cseq_ST_pp0_stg6_fsm_7, "ap_sig_cseq_ST_pp0_stg6_fsm_7");
    sc_trace(mVcdFile, ap_sig_bdd_424, "ap_sig_bdd_424");
    sc_trace(mVcdFile, d_phi_fu_518_p4, "d_phi_fu_518_p4");
    sc_trace(mVcdFile, ap_reg_phiprechg_tmp_4_reg_526pp0_it0, "ap_reg_phiprechg_tmp_4_reg_526pp0_it0");
    sc_trace(mVcdFile, tmp_67_cast_fu_588_p1, "tmp_67_cast_fu_588_p1");
    sc_trace(mVcdFile, tmp_74_fu_593_p3, "tmp_74_fu_593_p3");
    sc_trace(mVcdFile, tmp_71_cast_fu_616_p1, "tmp_71_cast_fu_616_p1");
    sc_trace(mVcdFile, tmp_69_cast_fu_623_p1, "tmp_69_cast_fu_623_p1");
    sc_trace(mVcdFile, tmp_68_fu_628_p3, "tmp_68_fu_628_p3");
    sc_trace(mVcdFile, ap_sig_cseq_ST_pp0_stg4_fsm_5, "ap_sig_cseq_ST_pp0_stg4_fsm_5");
    sc_trace(mVcdFile, ap_sig_bdd_473, "ap_sig_bdd_473");
    sc_trace(mVcdFile, tmp_69_fu_637_p3, "tmp_69_fu_637_p3");
    sc_trace(mVcdFile, tmp_71_fu_650_p3, "tmp_71_fu_650_p3");
    sc_trace(mVcdFile, tmp_72_fu_659_p3, "tmp_72_fu_659_p3");
    sc_trace(mVcdFile, tmp_75_cast_fu_674_p1, "tmp_75_cast_fu_674_p1");
    sc_trace(mVcdFile, tmp_73_cast_fu_681_p1, "tmp_73_cast_fu_681_p1");
    sc_trace(mVcdFile, tmp_cast1_fu_606_p1, "tmp_cast1_fu_606_p1");
    sc_trace(mVcdFile, tmp_69_cast1_fu_620_p1, "tmp_69_cast1_fu_620_p1");
    sc_trace(mVcdFile, tmp_cast_fu_646_p1, "tmp_cast_fu_646_p1");
    sc_trace(mVcdFile, tmp_73_cast1_fu_678_p1, "tmp_73_cast1_fu_678_p1");
    sc_trace(mVcdFile, ap_sig_cseq_ST_st11_fsm_8, "ap_sig_cseq_ST_st11_fsm_8");
    sc_trace(mVcdFile, ap_sig_bdd_596, "ap_sig_bdd_596");
    sc_trace(mVcdFile, ap_NS_fsm, "ap_NS_fsm");
    sc_trace(mVcdFile, ap_sig_bdd_660, "ap_sig_bdd_660");
    sc_trace(mVcdFile, ap_sig_bdd_382, "ap_sig_bdd_382");
#endif

    }
}

fire2_fill_buffer::~fire2_fill_buffer() {
    if (mVcdFile) 
        sc_close_vcd_trace_file(mVcdFile);

}

void fire2_fill_buffer::thread_ap_clk_no_reset_() {
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_CS_fsm = ap_ST_st1_fsm_0;
    } else {
        ap_CS_fsm = ap_NS_fsm.read();
    }
    if (ap_sig_bdd_382.read()) {
        if (esl_seteq<1,4,4>(tmp_104_reg_732.read(), ap_const_lv4_0)) {
            ap_reg_phiprechg_tmp_4_reg_526pp0_it0 = matrix_e3x3_i_0_V_dout.read();
        } else if (esl_seteq<1,4,4>(tmp_104_reg_732.read(), ap_const_lv4_1)) {
            ap_reg_phiprechg_tmp_4_reg_526pp0_it0 = matrix_e3x3_i_1_V_dout.read();
        } else if (esl_seteq<1,4,4>(tmp_104_reg_732.read(), ap_const_lv4_2)) {
            ap_reg_phiprechg_tmp_4_reg_526pp0_it0 = matrix_e3x3_i_2_V_dout.read();
        } else if (esl_seteq<1,4,4>(tmp_104_reg_732.read(), ap_const_lv4_3)) {
            ap_reg_phiprechg_tmp_4_reg_526pp0_it0 = matrix_e3x3_i_3_V_dout.read();
        } else if (esl_seteq<1,4,4>(tmp_104_reg_732.read(), ap_const_lv4_4)) {
            ap_reg_phiprechg_tmp_4_reg_526pp0_it0 = matrix_e3x3_i_4_V_dout.read();
        } else if (esl_seteq<1,4,4>(tmp_104_reg_732.read(), ap_const_lv4_5)) {
            ap_reg_phiprechg_tmp_4_reg_526pp0_it0 = matrix_e3x3_i_5_V_dout.read();
        } else if (esl_seteq<1,4,4>(tmp_104_reg_732.read(), ap_const_lv4_6)) {
            ap_reg_phiprechg_tmp_4_reg_526pp0_it0 = matrix_e3x3_i_6_V_dout.read();
        } else if (esl_seteq<1,4,4>(tmp_104_reg_732.read(), ap_const_lv4_7)) {
            ap_reg_phiprechg_tmp_4_reg_526pp0_it0 = matrix_e3x3_i_7_V_dout.read();
        } else if (esl_seteq<1,4,4>(tmp_104_reg_732.read(), ap_const_lv4_8)) {
            ap_reg_phiprechg_tmp_4_reg_526pp0_it0 = matrix_e3x3_i_8_V_dout.read();
        } else if (esl_seteq<1,4,4>(tmp_104_reg_732.read(), ap_const_lv4_9)) {
            ap_reg_phiprechg_tmp_4_reg_526pp0_it0 = matrix_e3x3_i_9_V_dout.read();
        } else if (esl_seteq<1,4,4>(tmp_104_reg_732.read(), ap_const_lv4_A)) {
            ap_reg_phiprechg_tmp_4_reg_526pp0_it0 = matrix_e3x3_i_10_V_dout.read();
        } else if (esl_seteq<1,4,4>(tmp_104_reg_732.read(), ap_const_lv4_B)) {
            ap_reg_phiprechg_tmp_4_reg_526pp0_it0 = matrix_e3x3_i_11_V_dout.read();
        } else if (esl_seteq<1,4,4>(tmp_104_reg_732.read(), ap_const_lv4_C)) {
            ap_reg_phiprechg_tmp_4_reg_526pp0_it0 = matrix_e3x3_i_12_V_dout.read();
        } else if (esl_seteq<1,4,4>(tmp_104_reg_732.read(), ap_const_lv4_D)) {
            ap_reg_phiprechg_tmp_4_reg_526pp0_it0 = matrix_e3x3_i_13_V_dout.read();
        } else if (esl_seteq<1,4,4>(tmp_104_reg_732.read(), ap_const_lv4_E)) {
            ap_reg_phiprechg_tmp_4_reg_526pp0_it0 = matrix_e3x3_i_14_V_dout.read();
        } else if (ap_sig_bdd_660.read()) {
            ap_reg_phiprechg_tmp_4_reg_526pp0_it0 = matrix_e3x3_i_15_V_dout.read();
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_reg_ppiten_pp0_it0 = ap_const_logic_0;
    } else {
        if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_pp0_stg0_fsm_1.read()) && 
             !esl_seteq<1,1,1>(exitcond2_fu_564_p2.read(), ap_const_lv1_0))) {
            ap_reg_ppiten_pp0_it0 = ap_const_logic_0;
        } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st1_fsm_0.read()) && 
                    !esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_0))) {
            ap_reg_ppiten_pp0_it0 = ap_const_logic_1;
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_reg_ppiten_pp0_it1 = ap_const_logic_0;
    } else {
        if ((esl_seteq<1,1,1>(exitcond2_reg_686.read(), ap_const_lv1_0) && 
             esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_pp0_stg6_fsm_7.read()))) {
            ap_reg_ppiten_pp0_it1 = ap_const_logic_1;
        } else if (((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st1_fsm_0.read()) && 
                     !esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_0)) || 
                    (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_pp0_stg6_fsm_7.read()) && 
                     !esl_seteq<1,1,1>(exitcond2_reg_686.read(), ap_const_lv1_0)))) {
            ap_reg_ppiten_pp0_it1 = ap_const_logic_0;
        }
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_pp0_stg0_fsm_1.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it1.read()) && 
         esl_seteq<1,1,1>(exitcond2_reg_686.read(), ap_const_lv1_0))) {
        d_reg_514 = d_1_reg_690.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st1_fsm_0.read()) && 
                !esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_0))) {
        d_reg_514 = ap_const_lv5_0;
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_pp0_stg0_fsm_1.read())) {
        ap_reg_ppstg_exitcond2_reg_686_pp0_it1 = exitcond2_reg_686.read();
        ap_reg_ppstg_tmp_67_reg_704_pp0_it1 = tmp_67_reg_704.read();
        exitcond2_reg_686 = exitcond2_fu_564_p2.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_pp0_stg0_fsm_1.read()) && esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it0.read()))) {
        d_1_reg_690 = d_1_fu_570_p2.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_pp0_stg1_fsm_2.read()) && esl_seteq<1,1,1>(exitcond2_reg_686.read(), ap_const_lv1_0) && !(esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it0.read()) && ap_sig_bdd_323.read()))) {
        line_buffer_0_54_load_reg_748 = line_buffer_0_54_q0.read();
        line_buffer_1_54_load_reg_741 = line_buffer_1_54_q0.read();
        tmp_70_reg_736 = tmp_70_fu_610_p2.read();
    }
    if ((esl_seteq<1,1,1>(exitcond2_reg_686.read(), ap_const_lv1_0) && esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_pp0_stg3_fsm_4.read()))) {
        line_buffer_2_54_load_reg_855 = line_buffer_2_54_q0.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_pp0_stg0_fsm_1.read()) && esl_seteq<1,1,1>(exitcond2_fu_564_p2.read(), ap_const_lv1_0))) {
        tmp_104_reg_732 = tmp_104_fu_602_p1.read();
        tmp_67_reg_704 = tmp_67_fu_582_p2.read();
        tmp_reg_695 = tmp_fu_576_p1.read();
        window_buffer_addr_10_reg_716 =  (sc_lv<8>) (tmp_74_fu_593_p3.read());
        window_buffer_addr_reg_710 =  (sc_lv<8>) (tmp_67_cast_fu_588_p1.read());
    }
    if ((esl_seteq<1,1,1>(exitcond2_reg_686.read(), ap_const_lv1_0) && esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_pp0_stg5_fsm_6.read()))) {
        tmp_73_reg_860 = tmp_73_fu_668_p2.read();
    }
    if ((esl_seteq<1,1,1>(exitcond2_reg_686.read(), ap_const_lv1_0) && esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_pp0_stg2_fsm_3.read()))) {
        window_buffer_addr_1_reg_845 =  (sc_lv<8>) (tmp_reg_695.read());
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it0.read()) && esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_pp0_stg1_fsm_2.read()) && esl_seteq<1,1,1>(exitcond2_reg_686.read(), ap_const_lv1_0) && !(esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it0.read()) && ap_sig_bdd_323.read()))) {
        window_buffer_load_1_reg_840 = window_buffer_q1.read();
        window_buffer_load_reg_835 = window_buffer_q0.read();
    }
}

void fire2_fill_buffer::thread_ap_done() {
    if (((!esl_seteq<1,1,1>(ap_const_logic_1, ap_start.read()) && 
          esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st1_fsm_0.read())) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st11_fsm_8.read()))) {
        ap_done = ap_const_logic_1;
    } else {
        ap_done = ap_const_logic_0;
    }
}

void fire2_fill_buffer::thread_ap_idle() {
    if ((!esl_seteq<1,1,1>(ap_const_logic_1, ap_start.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st1_fsm_0.read()))) {
        ap_idle = ap_const_logic_1;
    } else {
        ap_idle = ap_const_logic_0;
    }
}

void fire2_fill_buffer::thread_ap_ready() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st11_fsm_8.read())) {
        ap_ready = ap_const_logic_1;
    } else {
        ap_ready = ap_const_logic_0;
    }
}

void fire2_fill_buffer::thread_ap_sig_bdd_159() {
    ap_sig_bdd_159 = esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm.read().range(1, 1));
}

void fire2_fill_buffer::thread_ap_sig_bdd_198() {
    ap_sig_bdd_198 = esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm.read().range(2, 2));
}

void fire2_fill_buffer::thread_ap_sig_bdd_27() {
    ap_sig_bdd_27 = esl_seteq<1,1,1>(ap_CS_fsm.read().range(0, 0), ap_const_lv1_1);
}

void fire2_fill_buffer::thread_ap_sig_bdd_323() {
    ap_sig_bdd_323 = ((esl_seteq<1,1,1>(matrix_e3x3_i_14_V_empty_n.read(), ap_const_logic_0) && 
  esl_seteq<1,1,1>(exitcond2_reg_686.read(), ap_const_lv1_0) && 
  esl_seteq<1,4,4>(tmp_104_reg_732.read(), ap_const_lv4_E)) || (esl_seteq<1,1,1>(exitcond2_reg_686.read(), ap_const_lv1_0) && 
  esl_seteq<1,1,1>(matrix_e3x3_i_13_V_empty_n.read(), ap_const_logic_0) && 
  esl_seteq<1,4,4>(tmp_104_reg_732.read(), ap_const_lv4_D)) || (esl_seteq<1,1,1>(exitcond2_reg_686.read(), ap_const_lv1_0) && 
  esl_seteq<1,1,1>(matrix_e3x3_i_12_V_empty_n.read(), ap_const_logic_0) && 
  esl_seteq<1,4,4>(tmp_104_reg_732.read(), ap_const_lv4_C)) || (esl_seteq<1,1,1>(exitcond2_reg_686.read(), ap_const_lv1_0) && 
  esl_seteq<1,1,1>(matrix_e3x3_i_11_V_empty_n.read(), ap_const_logic_0) && 
  esl_seteq<1,4,4>(tmp_104_reg_732.read(), ap_const_lv4_B)) || (esl_seteq<1,1,1>(exitcond2_reg_686.read(), ap_const_lv1_0) && 
  esl_seteq<1,1,1>(matrix_e3x3_i_10_V_empty_n.read(), ap_const_logic_0) && 
  esl_seteq<1,4,4>(tmp_104_reg_732.read(), ap_const_lv4_A)) || (esl_seteq<1,1,1>(exitcond2_reg_686.read(), ap_const_lv1_0) && 
  esl_seteq<1,1,1>(matrix_e3x3_i_9_V_empty_n.read(), ap_const_logic_0) && 
  esl_seteq<1,4,4>(tmp_104_reg_732.read(), ap_const_lv4_9)) || (esl_seteq<1,1,1>(exitcond2_reg_686.read(), ap_const_lv1_0) && 
  esl_seteq<1,1,1>(matrix_e3x3_i_8_V_empty_n.read(), ap_const_logic_0) && 
  esl_seteq<1,4,4>(tmp_104_reg_732.read(), ap_const_lv4_8)) || (esl_seteq<1,1,1>(exitcond2_reg_686.read(), ap_const_lv1_0) && 
  esl_seteq<1,1,1>(matrix_e3x3_i_7_V_empty_n.read(), ap_const_logic_0) && 
  esl_seteq<1,4,4>(tmp_104_reg_732.read(), ap_const_lv4_7)) || (esl_seteq<1,1,1>(exitcond2_reg_686.read(), ap_const_lv1_0) && 
  esl_seteq<1,1,1>(matrix_e3x3_i_6_V_empty_n.read(), ap_const_logic_0) && 
  esl_seteq<1,4,4>(tmp_104_reg_732.read(), ap_const_lv4_6)) || (esl_seteq<1,1,1>(exitcond2_reg_686.read(), ap_const_lv1_0) && 
  esl_seteq<1,1,1>(matrix_e3x3_i_5_V_empty_n.read(), ap_const_logic_0) && 
  esl_seteq<1,4,4>(tmp_104_reg_732.read(), ap_const_lv4_5)) || (esl_seteq<1,1,1>(exitcond2_reg_686.read(), ap_const_lv1_0) && 
  esl_seteq<1,1,1>(matrix_e3x3_i_4_V_empty_n.read(), ap_const_logic_0) && 
  esl_seteq<1,4,4>(tmp_104_reg_732.read(), ap_const_lv4_4)) || (esl_seteq<1,1,1>(exitcond2_reg_686.read(), ap_const_lv1_0) && 
  esl_seteq<1,1,1>(matrix_e3x3_i_3_V_empty_n.read(), ap_const_logic_0) && 
  esl_seteq<1,4,4>(tmp_104_reg_732.read(), ap_const_lv4_3)) || (esl_seteq<1,1,1>(exitcond2_reg_686.read(), ap_const_lv1_0) && 
  esl_seteq<1,1,1>(matrix_e3x3_i_2_V_empty_n.read(), ap_const_logic_0) && 
  esl_seteq<1,4,4>(tmp_104_reg_732.read(), ap_const_lv4_2)) || (esl_seteq<1,1,1>(exitcond2_reg_686.read(), ap_const_lv1_0) && 
  esl_seteq<1,1,1>(matrix_e3x3_i_1_V_empty_n.read(), ap_const_logic_0) && 
  esl_seteq<1,4,4>(tmp_104_reg_732.read(), ap_const_lv4_1)) || (esl_seteq<1,1,1>(exitcond2_reg_686.read(), ap_const_lv1_0) && 
  esl_seteq<1,1,1>(matrix_e3x3_i_0_V_empty_n.read(), ap_const_logic_0) && 
  esl_seteq<1,4,4>(tmp_104_reg_732.read(), ap_const_lv4_0)) || (esl_seteq<1,1,1>(exitcond2_reg_686.read(), ap_const_lv1_0) && 
  esl_seteq<1,1,1>(matrix_e3x3_i_15_V_empty_n.read(), ap_const_logic_0) && 
  !esl_seteq<1,4,4>(tmp_104_reg_732.read(), ap_const_lv4_E) && 
  !esl_seteq<1,4,4>(tmp_104_reg_732.read(), ap_const_lv4_D) && 
  !esl_seteq<1,4,4>(tmp_104_reg_732.read(), ap_const_lv4_C) && 
  !esl_seteq<1,4,4>(tmp_104_reg_732.read(), ap_const_lv4_B) && 
  !esl_seteq<1,4,4>(tmp_104_reg_732.read(), ap_const_lv4_A) && 
  !esl_seteq<1,4,4>(tmp_104_reg_732.read(), ap_const_lv4_9) && 
  !esl_seteq<1,4,4>(tmp_104_reg_732.read(), ap_const_lv4_8) && 
  !esl_seteq<1,4,4>(tmp_104_reg_732.read(), ap_const_lv4_7) && 
  !esl_seteq<1,4,4>(tmp_104_reg_732.read(), ap_const_lv4_6) && 
  !esl_seteq<1,4,4>(tmp_104_reg_732.read(), ap_const_lv4_5) && 
  !esl_seteq<1,4,4>(tmp_104_reg_732.read(), ap_const_lv4_4) && 
  !esl_seteq<1,4,4>(tmp_104_reg_732.read(), ap_const_lv4_3) && 
  !esl_seteq<1,4,4>(tmp_104_reg_732.read(), ap_const_lv4_2) && 
  !esl_seteq<1,4,4>(tmp_104_reg_732.read(), ap_const_lv4_1) && 
  !esl_seteq<1,4,4>(tmp_104_reg_732.read(), ap_const_lv4_0)));
}

void fire2_fill_buffer::thread_ap_sig_bdd_382() {
    ap_sig_bdd_382 = (esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it0.read()) && esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_pp0_stg1_fsm_2.read()) && esl_seteq<1,1,1>(exitcond2_reg_686.read(), ap_const_lv1_0) && !(esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it0.read()) && ap_sig_bdd_323.read()));
}

void fire2_fill_buffer::thread_ap_sig_bdd_390() {
    ap_sig_bdd_390 = esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm.read().range(3, 3));
}

void fire2_fill_buffer::thread_ap_sig_bdd_401() {
    ap_sig_bdd_401 = esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm.read().range(4, 4));
}

void fire2_fill_buffer::thread_ap_sig_bdd_411() {
    ap_sig_bdd_411 = esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm.read().range(6, 6));
}

void fire2_fill_buffer::thread_ap_sig_bdd_424() {
    ap_sig_bdd_424 = esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm.read().range(7, 7));
}

void fire2_fill_buffer::thread_ap_sig_bdd_473() {
    ap_sig_bdd_473 = esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm.read().range(5, 5));
}

void fire2_fill_buffer::thread_ap_sig_bdd_596() {
    ap_sig_bdd_596 = esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm.read().range(8, 8));
}

void fire2_fill_buffer::thread_ap_sig_bdd_660() {
    ap_sig_bdd_660 = (!esl_seteq<1,4,4>(tmp_104_reg_732.read(), ap_const_lv4_E) && !esl_seteq<1,4,4>(tmp_104_reg_732.read(), ap_const_lv4_D) && !esl_seteq<1,4,4>(tmp_104_reg_732.read(), ap_const_lv4_C) && !esl_seteq<1,4,4>(tmp_104_reg_732.read(), ap_const_lv4_B) && !esl_seteq<1,4,4>(tmp_104_reg_732.read(), ap_const_lv4_A) && !esl_seteq<1,4,4>(tmp_104_reg_732.read(), ap_const_lv4_9) && !esl_seteq<1,4,4>(tmp_104_reg_732.read(), ap_const_lv4_8) && !esl_seteq<1,4,4>(tmp_104_reg_732.read(), ap_const_lv4_7) && !esl_seteq<1,4,4>(tmp_104_reg_732.read(), ap_const_lv4_6) && !esl_seteq<1,4,4>(tmp_104_reg_732.read(), ap_const_lv4_5) && !esl_seteq<1,4,4>(tmp_104_reg_732.read(), ap_const_lv4_4) && !esl_seteq<1,4,4>(tmp_104_reg_732.read(), ap_const_lv4_3) && !esl_seteq<1,4,4>(tmp_104_reg_732.read(), ap_const_lv4_2) && !esl_seteq<1,4,4>(tmp_104_reg_732.read(), ap_const_lv4_1) && !esl_seteq<1,4,4>(tmp_104_reg_732.read(), ap_const_lv4_0));
}

void fire2_fill_buffer::thread_ap_sig_cseq_ST_pp0_stg0_fsm_1() {
    if (ap_sig_bdd_159.read()) {
        ap_sig_cseq_ST_pp0_stg0_fsm_1 = ap_const_logic_1;
    } else {
        ap_sig_cseq_ST_pp0_stg0_fsm_1 = ap_const_logic_0;
    }
}

void fire2_fill_buffer::thread_ap_sig_cseq_ST_pp0_stg1_fsm_2() {
    if (ap_sig_bdd_198.read()) {
        ap_sig_cseq_ST_pp0_stg1_fsm_2 = ap_const_logic_1;
    } else {
        ap_sig_cseq_ST_pp0_stg1_fsm_2 = ap_const_logic_0;
    }
}

void fire2_fill_buffer::thread_ap_sig_cseq_ST_pp0_stg2_fsm_3() {
    if (ap_sig_bdd_390.read()) {
        ap_sig_cseq_ST_pp0_stg2_fsm_3 = ap_const_logic_1;
    } else {
        ap_sig_cseq_ST_pp0_stg2_fsm_3 = ap_const_logic_0;
    }
}

void fire2_fill_buffer::thread_ap_sig_cseq_ST_pp0_stg3_fsm_4() {
    if (ap_sig_bdd_401.read()) {
        ap_sig_cseq_ST_pp0_stg3_fsm_4 = ap_const_logic_1;
    } else {
        ap_sig_cseq_ST_pp0_stg3_fsm_4 = ap_const_logic_0;
    }
}

void fire2_fill_buffer::thread_ap_sig_cseq_ST_pp0_stg4_fsm_5() {
    if (ap_sig_bdd_473.read()) {
        ap_sig_cseq_ST_pp0_stg4_fsm_5 = ap_const_logic_1;
    } else {
        ap_sig_cseq_ST_pp0_stg4_fsm_5 = ap_const_logic_0;
    }
}

void fire2_fill_buffer::thread_ap_sig_cseq_ST_pp0_stg5_fsm_6() {
    if (ap_sig_bdd_411.read()) {
        ap_sig_cseq_ST_pp0_stg5_fsm_6 = ap_const_logic_1;
    } else {
        ap_sig_cseq_ST_pp0_stg5_fsm_6 = ap_const_logic_0;
    }
}

void fire2_fill_buffer::thread_ap_sig_cseq_ST_pp0_stg6_fsm_7() {
    if (ap_sig_bdd_424.read()) {
        ap_sig_cseq_ST_pp0_stg6_fsm_7 = ap_const_logic_1;
    } else {
        ap_sig_cseq_ST_pp0_stg6_fsm_7 = ap_const_logic_0;
    }
}

void fire2_fill_buffer::thread_ap_sig_cseq_ST_st11_fsm_8() {
    if (ap_sig_bdd_596.read()) {
        ap_sig_cseq_ST_st11_fsm_8 = ap_const_logic_1;
    } else {
        ap_sig_cseq_ST_st11_fsm_8 = ap_const_logic_0;
    }
}

void fire2_fill_buffer::thread_ap_sig_cseq_ST_st1_fsm_0() {
    if (ap_sig_bdd_27.read()) {
        ap_sig_cseq_ST_st1_fsm_0 = ap_const_logic_1;
    } else {
        ap_sig_cseq_ST_st1_fsm_0 = ap_const_logic_0;
    }
}

void fire2_fill_buffer::thread_d_1_fu_570_p2() {
    d_1_fu_570_p2 = (!d_phi_fu_518_p4.read().is_01() || !ap_const_lv5_1.is_01())? sc_lv<5>(): (sc_biguint<5>(d_phi_fu_518_p4.read()) + sc_biguint<5>(ap_const_lv5_1));
}

void fire2_fill_buffer::thread_d_phi_fu_518_p4() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_pp0_stg0_fsm_1.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it1.read()) && 
         esl_seteq<1,1,1>(exitcond2_reg_686.read(), ap_const_lv1_0))) {
        d_phi_fu_518_p4 = d_1_reg_690.read();
    } else {
        d_phi_fu_518_p4 = d_reg_514.read();
    }
}

void fire2_fill_buffer::thread_exitcond2_fu_564_p2() {
    exitcond2_fu_564_p2 = (!d_phi_fu_518_p4.read().is_01() || !ap_const_lv5_10.is_01())? sc_lv<1>(): sc_lv<1>(d_phi_fu_518_p4.read() == ap_const_lv5_10);
}

void fire2_fill_buffer::thread_line_buffer_0_0_address0() {
    line_buffer_0_0_address0 =  (sc_lv<4>) (tmp_reg_695.read());
}

void fire2_fill_buffer::thread_line_buffer_0_0_ce0() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it0.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_pp0_stg2_fsm_3.read()))) {
        line_buffer_0_0_ce0 = ap_const_logic_1;
    } else {
        line_buffer_0_0_ce0 = ap_const_logic_0;
    }
}

void fire2_fill_buffer::thread_line_buffer_0_0_d0() {
    line_buffer_0_0_d0 = ap_reg_phiprechg_tmp_4_reg_526pp0_it0.read();
}

void fire2_fill_buffer::thread_line_buffer_0_0_we0() {
    if (((esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it0.read()) && 
          esl_seteq<1,1,1>(exitcond2_reg_686.read(), ap_const_lv1_0) && 
          esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_pp0_stg2_fsm_3.read())))) {
        line_buffer_0_0_we0 = ap_const_logic_1;
    } else {
        line_buffer_0_0_we0 = ap_const_logic_0;
    }
}

void fire2_fill_buffer::thread_line_buffer_0_54_address0() {
    line_buffer_0_54_address0 =  (sc_lv<4>) (tmp_fu_576_p1.read());
}

void fire2_fill_buffer::thread_line_buffer_0_54_ce0() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_pp0_stg0_fsm_1.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it0.read()))) {
        line_buffer_0_54_ce0 = ap_const_logic_1;
    } else {
        line_buffer_0_54_ce0 = ap_const_logic_0;
    }
}

void fire2_fill_buffer::thread_line_buffer_1_0_address0() {
    line_buffer_1_0_address0 =  (sc_lv<4>) (tmp_reg_695.read());
}

void fire2_fill_buffer::thread_line_buffer_1_0_ce0() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it0.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_pp0_stg2_fsm_3.read()))) {
        line_buffer_1_0_ce0 = ap_const_logic_1;
    } else {
        line_buffer_1_0_ce0 = ap_const_logic_0;
    }
}

void fire2_fill_buffer::thread_line_buffer_1_0_d0() {
    line_buffer_1_0_d0 = line_buffer_0_54_load_reg_748.read();
}

void fire2_fill_buffer::thread_line_buffer_1_0_we0() {
    if (((esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it0.read()) && 
          esl_seteq<1,1,1>(exitcond2_reg_686.read(), ap_const_lv1_0) && 
          esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_pp0_stg2_fsm_3.read())))) {
        line_buffer_1_0_we0 = ap_const_logic_1;
    } else {
        line_buffer_1_0_we0 = ap_const_logic_0;
    }
}

void fire2_fill_buffer::thread_line_buffer_1_54_address0() {
    line_buffer_1_54_address0 =  (sc_lv<4>) (tmp_fu_576_p1.read());
}

void fire2_fill_buffer::thread_line_buffer_1_54_ce0() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_pp0_stg0_fsm_1.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it0.read()))) {
        line_buffer_1_54_ce0 = ap_const_logic_1;
    } else {
        line_buffer_1_54_ce0 = ap_const_logic_0;
    }
}

void fire2_fill_buffer::thread_line_buffer_2_0_address0() {
    line_buffer_2_0_address0 =  (sc_lv<4>) (tmp_reg_695.read());
}

void fire2_fill_buffer::thread_line_buffer_2_0_ce0() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it0.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_pp0_stg2_fsm_3.read()))) {
        line_buffer_2_0_ce0 = ap_const_logic_1;
    } else {
        line_buffer_2_0_ce0 = ap_const_logic_0;
    }
}

void fire2_fill_buffer::thread_line_buffer_2_0_d0() {
    line_buffer_2_0_d0 = line_buffer_1_54_load_reg_741.read();
}

void fire2_fill_buffer::thread_line_buffer_2_0_we0() {
    if (((esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it0.read()) && 
          esl_seteq<1,1,1>(exitcond2_reg_686.read(), ap_const_lv1_0) && 
          esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_pp0_stg2_fsm_3.read())))) {
        line_buffer_2_0_we0 = ap_const_logic_1;
    } else {
        line_buffer_2_0_we0 = ap_const_logic_0;
    }
}

void fire2_fill_buffer::thread_line_buffer_2_54_address0() {
    line_buffer_2_54_address0 =  (sc_lv<4>) (tmp_reg_695.read());
}

void fire2_fill_buffer::thread_line_buffer_2_54_ce0() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it0.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_pp0_stg2_fsm_3.read()))) {
        line_buffer_2_54_ce0 = ap_const_logic_1;
    } else {
        line_buffer_2_54_ce0 = ap_const_logic_0;
    }
}

void fire2_fill_buffer::thread_matrix_e3x3_i_0_V_read() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it0.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_pp0_stg1_fsm_2.read()) && 
         esl_seteq<1,1,1>(exitcond2_reg_686.read(), ap_const_lv1_0) && 
         esl_seteq<1,4,4>(tmp_104_reg_732.read(), ap_const_lv4_0) && 
         !(esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it0.read()) && ap_sig_bdd_323.read()))) {
        matrix_e3x3_i_0_V_read = ap_const_logic_1;
    } else {
        matrix_e3x3_i_0_V_read = ap_const_logic_0;
    }
}

void fire2_fill_buffer::thread_matrix_e3x3_i_10_V_read() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it0.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_pp0_stg1_fsm_2.read()) && 
         esl_seteq<1,1,1>(exitcond2_reg_686.read(), ap_const_lv1_0) && 
         esl_seteq<1,4,4>(tmp_104_reg_732.read(), ap_const_lv4_A) && 
         !(esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it0.read()) && ap_sig_bdd_323.read()))) {
        matrix_e3x3_i_10_V_read = ap_const_logic_1;
    } else {
        matrix_e3x3_i_10_V_read = ap_const_logic_0;
    }
}

void fire2_fill_buffer::thread_matrix_e3x3_i_11_V_read() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it0.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_pp0_stg1_fsm_2.read()) && 
         esl_seteq<1,1,1>(exitcond2_reg_686.read(), ap_const_lv1_0) && 
         esl_seteq<1,4,4>(tmp_104_reg_732.read(), ap_const_lv4_B) && 
         !(esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it0.read()) && ap_sig_bdd_323.read()))) {
        matrix_e3x3_i_11_V_read = ap_const_logic_1;
    } else {
        matrix_e3x3_i_11_V_read = ap_const_logic_0;
    }
}

void fire2_fill_buffer::thread_matrix_e3x3_i_12_V_read() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it0.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_pp0_stg1_fsm_2.read()) && 
         esl_seteq<1,1,1>(exitcond2_reg_686.read(), ap_const_lv1_0) && 
         esl_seteq<1,4,4>(tmp_104_reg_732.read(), ap_const_lv4_C) && 
         !(esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it0.read()) && ap_sig_bdd_323.read()))) {
        matrix_e3x3_i_12_V_read = ap_const_logic_1;
    } else {
        matrix_e3x3_i_12_V_read = ap_const_logic_0;
    }
}

void fire2_fill_buffer::thread_matrix_e3x3_i_13_V_read() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it0.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_pp0_stg1_fsm_2.read()) && 
         esl_seteq<1,1,1>(exitcond2_reg_686.read(), ap_const_lv1_0) && 
         esl_seteq<1,4,4>(tmp_104_reg_732.read(), ap_const_lv4_D) && 
         !(esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it0.read()) && ap_sig_bdd_323.read()))) {
        matrix_e3x3_i_13_V_read = ap_const_logic_1;
    } else {
        matrix_e3x3_i_13_V_read = ap_const_logic_0;
    }
}

void fire2_fill_buffer::thread_matrix_e3x3_i_14_V_read() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it0.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_pp0_stg1_fsm_2.read()) && 
         esl_seteq<1,1,1>(exitcond2_reg_686.read(), ap_const_lv1_0) && 
         esl_seteq<1,4,4>(tmp_104_reg_732.read(), ap_const_lv4_E) && 
         !(esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it0.read()) && ap_sig_bdd_323.read()))) {
        matrix_e3x3_i_14_V_read = ap_const_logic_1;
    } else {
        matrix_e3x3_i_14_V_read = ap_const_logic_0;
    }
}

void fire2_fill_buffer::thread_matrix_e3x3_i_15_V_read() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it0.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_pp0_stg1_fsm_2.read()) && 
         esl_seteq<1,1,1>(exitcond2_reg_686.read(), ap_const_lv1_0) && 
         !esl_seteq<1,4,4>(tmp_104_reg_732.read(), ap_const_lv4_E) && 
         !esl_seteq<1,4,4>(tmp_104_reg_732.read(), ap_const_lv4_D) && 
         !esl_seteq<1,4,4>(tmp_104_reg_732.read(), ap_const_lv4_C) && 
         !esl_seteq<1,4,4>(tmp_104_reg_732.read(), ap_const_lv4_B) && 
         !esl_seteq<1,4,4>(tmp_104_reg_732.read(), ap_const_lv4_A) && 
         !esl_seteq<1,4,4>(tmp_104_reg_732.read(), ap_const_lv4_9) && 
         !esl_seteq<1,4,4>(tmp_104_reg_732.read(), ap_const_lv4_8) && 
         !esl_seteq<1,4,4>(tmp_104_reg_732.read(), ap_const_lv4_7) && 
         !esl_seteq<1,4,4>(tmp_104_reg_732.read(), ap_const_lv4_6) && 
         !esl_seteq<1,4,4>(tmp_104_reg_732.read(), ap_const_lv4_5) && 
         !esl_seteq<1,4,4>(tmp_104_reg_732.read(), ap_const_lv4_4) && 
         !esl_seteq<1,4,4>(tmp_104_reg_732.read(), ap_const_lv4_3) && 
         !esl_seteq<1,4,4>(tmp_104_reg_732.read(), ap_const_lv4_2) && 
         !esl_seteq<1,4,4>(tmp_104_reg_732.read(), ap_const_lv4_1) && 
         !esl_seteq<1,4,4>(tmp_104_reg_732.read(), ap_const_lv4_0) && 
         !(esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it0.read()) && ap_sig_bdd_323.read()))) {
        matrix_e3x3_i_15_V_read = ap_const_logic_1;
    } else {
        matrix_e3x3_i_15_V_read = ap_const_logic_0;
    }
}

void fire2_fill_buffer::thread_matrix_e3x3_i_1_V_read() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it0.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_pp0_stg1_fsm_2.read()) && 
         esl_seteq<1,1,1>(exitcond2_reg_686.read(), ap_const_lv1_0) && 
         esl_seteq<1,4,4>(tmp_104_reg_732.read(), ap_const_lv4_1) && 
         !(esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it0.read()) && ap_sig_bdd_323.read()))) {
        matrix_e3x3_i_1_V_read = ap_const_logic_1;
    } else {
        matrix_e3x3_i_1_V_read = ap_const_logic_0;
    }
}

void fire2_fill_buffer::thread_matrix_e3x3_i_2_V_read() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it0.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_pp0_stg1_fsm_2.read()) && 
         esl_seteq<1,1,1>(exitcond2_reg_686.read(), ap_const_lv1_0) && 
         esl_seteq<1,4,4>(tmp_104_reg_732.read(), ap_const_lv4_2) && 
         !(esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it0.read()) && ap_sig_bdd_323.read()))) {
        matrix_e3x3_i_2_V_read = ap_const_logic_1;
    } else {
        matrix_e3x3_i_2_V_read = ap_const_logic_0;
    }
}

void fire2_fill_buffer::thread_matrix_e3x3_i_3_V_read() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it0.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_pp0_stg1_fsm_2.read()) && 
         esl_seteq<1,1,1>(exitcond2_reg_686.read(), ap_const_lv1_0) && 
         esl_seteq<1,4,4>(tmp_104_reg_732.read(), ap_const_lv4_3) && 
         !(esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it0.read()) && ap_sig_bdd_323.read()))) {
        matrix_e3x3_i_3_V_read = ap_const_logic_1;
    } else {
        matrix_e3x3_i_3_V_read = ap_const_logic_0;
    }
}

void fire2_fill_buffer::thread_matrix_e3x3_i_4_V_read() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it0.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_pp0_stg1_fsm_2.read()) && 
         esl_seteq<1,1,1>(exitcond2_reg_686.read(), ap_const_lv1_0) && 
         esl_seteq<1,4,4>(tmp_104_reg_732.read(), ap_const_lv4_4) && 
         !(esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it0.read()) && ap_sig_bdd_323.read()))) {
        matrix_e3x3_i_4_V_read = ap_const_logic_1;
    } else {
        matrix_e3x3_i_4_V_read = ap_const_logic_0;
    }
}

void fire2_fill_buffer::thread_matrix_e3x3_i_5_V_read() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it0.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_pp0_stg1_fsm_2.read()) && 
         esl_seteq<1,1,1>(exitcond2_reg_686.read(), ap_const_lv1_0) && 
         esl_seteq<1,4,4>(tmp_104_reg_732.read(), ap_const_lv4_5) && 
         !(esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it0.read()) && ap_sig_bdd_323.read()))) {
        matrix_e3x3_i_5_V_read = ap_const_logic_1;
    } else {
        matrix_e3x3_i_5_V_read = ap_const_logic_0;
    }
}

void fire2_fill_buffer::thread_matrix_e3x3_i_6_V_read() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it0.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_pp0_stg1_fsm_2.read()) && 
         esl_seteq<1,1,1>(exitcond2_reg_686.read(), ap_const_lv1_0) && 
         esl_seteq<1,4,4>(tmp_104_reg_732.read(), ap_const_lv4_6) && 
         !(esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it0.read()) && ap_sig_bdd_323.read()))) {
        matrix_e3x3_i_6_V_read = ap_const_logic_1;
    } else {
        matrix_e3x3_i_6_V_read = ap_const_logic_0;
    }
}

void fire2_fill_buffer::thread_matrix_e3x3_i_7_V_read() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it0.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_pp0_stg1_fsm_2.read()) && 
         esl_seteq<1,1,1>(exitcond2_reg_686.read(), ap_const_lv1_0) && 
         esl_seteq<1,4,4>(tmp_104_reg_732.read(), ap_const_lv4_7) && 
         !(esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it0.read()) && ap_sig_bdd_323.read()))) {
        matrix_e3x3_i_7_V_read = ap_const_logic_1;
    } else {
        matrix_e3x3_i_7_V_read = ap_const_logic_0;
    }
}

void fire2_fill_buffer::thread_matrix_e3x3_i_8_V_read() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it0.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_pp0_stg1_fsm_2.read()) && 
         esl_seteq<1,1,1>(exitcond2_reg_686.read(), ap_const_lv1_0) && 
         esl_seteq<1,4,4>(tmp_104_reg_732.read(), ap_const_lv4_8) && 
         !(esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it0.read()) && ap_sig_bdd_323.read()))) {
        matrix_e3x3_i_8_V_read = ap_const_logic_1;
    } else {
        matrix_e3x3_i_8_V_read = ap_const_logic_0;
    }
}

void fire2_fill_buffer::thread_matrix_e3x3_i_9_V_read() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it0.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_pp0_stg1_fsm_2.read()) && 
         esl_seteq<1,1,1>(exitcond2_reg_686.read(), ap_const_lv1_0) && 
         esl_seteq<1,4,4>(tmp_104_reg_732.read(), ap_const_lv4_9) && 
         !(esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it0.read()) && ap_sig_bdd_323.read()))) {
        matrix_e3x3_i_9_V_read = ap_const_logic_1;
    } else {
        matrix_e3x3_i_9_V_read = ap_const_logic_0;
    }
}

void fire2_fill_buffer::thread_tmp_104_fu_602_p1() {
    tmp_104_fu_602_p1 = d_phi_fu_518_p4.read().range(4-1, 0);
}

void fire2_fill_buffer::thread_tmp_67_cast_fu_588_p1() {
    tmp_67_cast_fu_588_p1 = esl_zext<64,5>(tmp_67_fu_582_p2.read());
}

void fire2_fill_buffer::thread_tmp_67_fu_582_p2() {
    tmp_67_fu_582_p2 = (d_phi_fu_518_p4.read() ^ ap_const_lv5_10);
}

void fire2_fill_buffer::thread_tmp_68_fu_628_p3() {
    tmp_68_fu_628_p3 = esl_concat<59,5>(ap_const_lv59_1, d_reg_514.read());
}

void fire2_fill_buffer::thread_tmp_69_cast1_fu_620_p1() {
    tmp_69_cast1_fu_620_p1 = esl_sext<6,5>(tmp_67_reg_704.read());
}

void fire2_fill_buffer::thread_tmp_69_cast_fu_623_p1() {
    tmp_69_cast_fu_623_p1 = esl_zext<64,6>(tmp_69_cast1_fu_620_p1.read());
}

void fire2_fill_buffer::thread_tmp_69_fu_637_p3() {
    tmp_69_fu_637_p3 = esl_concat<59,5>(ap_const_lv59_2, d_reg_514.read());
}

void fire2_fill_buffer::thread_tmp_70_fu_610_p2() {
    tmp_70_fu_610_p2 = (!ap_const_lv7_50.is_01() || !tmp_cast1_fu_606_p1.read().is_01())? sc_lv<7>(): (sc_bigint<7>(ap_const_lv7_50) + sc_biguint<7>(tmp_cast1_fu_606_p1.read()));
}

void fire2_fill_buffer::thread_tmp_71_cast_fu_616_p1() {
    tmp_71_cast_fu_616_p1 = esl_zext<64,7>(tmp_70_reg_736.read());
}

void fire2_fill_buffer::thread_tmp_71_fu_650_p3() {
    tmp_71_fu_650_p3 = esl_concat<59,5>(ap_const_lv59_3, d_reg_514.read());
}

void fire2_fill_buffer::thread_tmp_72_fu_659_p3() {
    tmp_72_fu_659_p3 = esl_concat<59,5>(ap_const_lv59_4, d_reg_514.read());
}

void fire2_fill_buffer::thread_tmp_73_cast1_fu_678_p1() {
    tmp_73_cast1_fu_678_p1 = esl_sext<7,5>(ap_reg_ppstg_tmp_67_reg_704_pp0_it1.read());
}

void fire2_fill_buffer::thread_tmp_73_cast_fu_681_p1() {
    tmp_73_cast_fu_681_p1 = esl_zext<64,7>(tmp_73_cast1_fu_678_p1.read());
}

void fire2_fill_buffer::thread_tmp_73_fu_668_p2() {
    tmp_73_fu_668_p2 = (!ap_const_lv8_90.is_01() || !tmp_cast_fu_646_p1.read().is_01())? sc_lv<8>(): (sc_bigint<8>(ap_const_lv8_90) + sc_biguint<8>(tmp_cast_fu_646_p1.read()));
}

void fire2_fill_buffer::thread_tmp_74_fu_593_p3() {
    tmp_74_fu_593_p3 = esl_concat<59,5>(ap_const_lv59_5, d_phi_fu_518_p4.read());
}

void fire2_fill_buffer::thread_tmp_75_cast_fu_674_p1() {
    tmp_75_cast_fu_674_p1 = esl_zext<64,8>(tmp_73_reg_860.read());
}

void fire2_fill_buffer::thread_tmp_cast1_fu_606_p1() {
    tmp_cast1_fu_606_p1 = esl_zext<7,5>(d_reg_514.read());
}

void fire2_fill_buffer::thread_tmp_cast_fu_646_p1() {
    tmp_cast_fu_646_p1 = esl_zext<8,5>(d_reg_514.read());
}

void fire2_fill_buffer::thread_tmp_fu_576_p1() {
    tmp_fu_576_p1 = esl_zext<64,5>(d_phi_fu_518_p4.read());
}

void fire2_fill_buffer::thread_window_buffer_address0() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it1.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_pp0_stg1_fsm_2.read()))) {
        window_buffer_address0 =  (sc_lv<8>) (tmp_73_cast_fu_681_p1.read());
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it0.read()) && 
                esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_pp0_stg6_fsm_7.read()))) {
        window_buffer_address0 = window_buffer_addr_10_reg_716.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it0.read()) && 
                esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_pp0_stg5_fsm_6.read()))) {
        window_buffer_address0 =  (sc_lv<8>) (tmp_72_fu_659_p3.read());
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it0.read()) && 
                esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_pp0_stg4_fsm_5.read()))) {
        window_buffer_address0 =  (sc_lv<8>) (tmp_69_fu_637_p3.read());
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it0.read()) && 
                esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_pp0_stg3_fsm_4.read()))) {
        window_buffer_address0 =  (sc_lv<8>) (tmp_69_cast_fu_623_p1.read());
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it0.read()) && 
                esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_pp0_stg2_fsm_3.read()))) {
        window_buffer_address0 =  (sc_lv<8>) (tmp_71_cast_fu_616_p1.read());
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_pp0_stg0_fsm_1.read()) && 
                esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it0.read()))) {
        window_buffer_address0 =  (sc_lv<8>) (tmp_67_cast_fu_588_p1.read());
    } else {
        window_buffer_address0 = "XXXXXXXX";
    }
}

void fire2_fill_buffer::thread_window_buffer_address1() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it0.read())) {
        if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_pp0_stg6_fsm_7.read())) {
            window_buffer_address1 =  (sc_lv<8>) (tmp_75_cast_fu_674_p1.read());
        } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_pp0_stg5_fsm_6.read())) {
            window_buffer_address1 =  (sc_lv<8>) (tmp_71_fu_650_p3.read());
        } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_pp0_stg4_fsm_5.read())) {
            window_buffer_address1 =  (sc_lv<8>) (tmp_68_fu_628_p3.read());
        } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_pp0_stg3_fsm_4.read())) {
            window_buffer_address1 = window_buffer_addr_1_reg_845.read();
        } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_pp0_stg2_fsm_3.read())) {
            window_buffer_address1 = window_buffer_addr_reg_710.read();
        } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_pp0_stg0_fsm_1.read())) {
            window_buffer_address1 =  (sc_lv<8>) (tmp_74_fu_593_p3.read());
        } else {
            window_buffer_address1 = "XXXXXXXX";
        }
    } else {
        window_buffer_address1 = "XXXXXXXX";
    }
}

void fire2_fill_buffer::thread_window_buffer_ce0() {
    if (((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_pp0_stg0_fsm_1.read()) && 
          esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it0.read())) || 
         (esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it0.read()) && 
          esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_pp0_stg2_fsm_3.read())) || 
         (esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it0.read()) && 
          esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_pp0_stg3_fsm_4.read())) || 
         (esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it0.read()) && 
          esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_pp0_stg4_fsm_5.read())) || 
         (esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it0.read()) && 
          esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_pp0_stg5_fsm_6.read())) || 
         (esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it0.read()) && 
          esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_pp0_stg6_fsm_7.read())) || 
         (esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it1.read()) && 
          esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_pp0_stg1_fsm_2.read()) && 
          !(esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it0.read()) && ap_sig_bdd_323.read())))) {
        window_buffer_ce0 = ap_const_logic_1;
    } else {
        window_buffer_ce0 = ap_const_logic_0;
    }
}

void fire2_fill_buffer::thread_window_buffer_ce1() {
    if (((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_pp0_stg0_fsm_1.read()) && 
          esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it0.read())) || 
         (esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it0.read()) && 
          esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_pp0_stg2_fsm_3.read())) || 
         (esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it0.read()) && 
          esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_pp0_stg3_fsm_4.read())) || 
         (esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it0.read()) && 
          esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_pp0_stg4_fsm_5.read())) || 
         (esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it0.read()) && 
          esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_pp0_stg5_fsm_6.read())) || 
         (esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it0.read()) && 
          esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_pp0_stg6_fsm_7.read())))) {
        window_buffer_ce1 = ap_const_logic_1;
    } else {
        window_buffer_ce1 = ap_const_logic_0;
    }
}

void fire2_fill_buffer::thread_window_buffer_d0() {
    if (((esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it0.read()) && 
          esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_pp0_stg5_fsm_6.read())) || 
         (esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it0.read()) && 
          esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_pp0_stg6_fsm_7.read())) || 
         (esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it1.read()) && 
          esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_pp0_stg1_fsm_2.read())))) {
        window_buffer_d0 = line_buffer_2_54_load_reg_855.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it0.read()) && 
                esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_pp0_stg3_fsm_4.read()))) {
        window_buffer_d0 = line_buffer_0_54_load_reg_748.read();
    } else if (((esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it0.read()) && 
                 esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_pp0_stg2_fsm_3.read())) || 
                (esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it0.read()) && 
                 esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_pp0_stg4_fsm_5.read())))) {
        window_buffer_d0 = line_buffer_1_54_load_reg_741.read();
    } else {
        window_buffer_d0 =  (sc_lv<16>) ("XXXXXXXXXXXXXXXX");
    }
}

void fire2_fill_buffer::thread_window_buffer_d1() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it0.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_pp0_stg6_fsm_7.read()))) {
        window_buffer_d1 = window_buffer_load_1_reg_840.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it0.read()) && 
                esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_pp0_stg5_fsm_6.read()))) {
        window_buffer_d1 = line_buffer_1_54_load_reg_741.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it0.read()) && 
                esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_pp0_stg3_fsm_4.read()))) {
        window_buffer_d1 = window_buffer_load_reg_835.read();
    } else if (((esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it0.read()) && 
                 esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_pp0_stg2_fsm_3.read())) || 
                (esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it0.read()) && 
                 esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_pp0_stg4_fsm_5.read())))) {
        window_buffer_d1 = line_buffer_0_54_load_reg_748.read();
    } else {
        window_buffer_d1 =  (sc_lv<16>) ("XXXXXXXXXXXXXXXX");
    }
}

void fire2_fill_buffer::thread_window_buffer_we0() {
    if (((esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it0.read()) && 
          esl_seteq<1,1,1>(exitcond2_reg_686.read(), ap_const_lv1_0) && 
          esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_pp0_stg2_fsm_3.read())) || 
         (esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it0.read()) && 
          esl_seteq<1,1,1>(exitcond2_reg_686.read(), ap_const_lv1_0) && 
          esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_pp0_stg3_fsm_4.read())) || 
         (esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it0.read()) && 
          esl_seteq<1,1,1>(exitcond2_reg_686.read(), ap_const_lv1_0) && 
          esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_pp0_stg4_fsm_5.read())) || 
         (esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it0.read()) && 
          esl_seteq<1,1,1>(exitcond2_reg_686.read(), ap_const_lv1_0) && 
          esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_pp0_stg5_fsm_6.read())) || 
         (esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it0.read()) && 
          esl_seteq<1,1,1>(exitcond2_reg_686.read(), ap_const_lv1_0) && 
          esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_pp0_stg6_fsm_7.read())) || 
         (esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it1.read()) && 
          esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_pp0_stg1_fsm_2.read()) && 
          !(esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it0.read()) && ap_sig_bdd_323.read()) && 
          esl_seteq<1,1,1>(ap_reg_ppstg_exitcond2_reg_686_pp0_it1.read(), ap_const_lv1_0)))) {
        window_buffer_we0 = ap_const_logic_1;
    } else {
        window_buffer_we0 = ap_const_logic_0;
    }
}

void fire2_fill_buffer::thread_window_buffer_we1() {
    if (((esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it0.read()) && 
          esl_seteq<1,1,1>(exitcond2_reg_686.read(), ap_const_lv1_0) && 
          esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_pp0_stg2_fsm_3.read())) || 
         (esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it0.read()) && 
          esl_seteq<1,1,1>(exitcond2_reg_686.read(), ap_const_lv1_0) && 
          esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_pp0_stg3_fsm_4.read())) || 
         (esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it0.read()) && 
          esl_seteq<1,1,1>(exitcond2_reg_686.read(), ap_const_lv1_0) && 
          esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_pp0_stg4_fsm_5.read())) || 
         (esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it0.read()) && 
          esl_seteq<1,1,1>(exitcond2_reg_686.read(), ap_const_lv1_0) && 
          esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_pp0_stg5_fsm_6.read())) || 
         (esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it0.read()) && 
          esl_seteq<1,1,1>(exitcond2_reg_686.read(), ap_const_lv1_0) && 
          esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_pp0_stg6_fsm_7.read())))) {
        window_buffer_we1 = ap_const_logic_1;
    } else {
        window_buffer_we1 = ap_const_logic_0;
    }
}

void fire2_fill_buffer::thread_ap_NS_fsm() {
    switch (ap_CS_fsm.read().to_uint64()) {
        case 1 : 
            if (!esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_0)) {
                ap_NS_fsm = ap_ST_pp0_stg0_fsm_1;
            } else {
                ap_NS_fsm = ap_ST_st1_fsm_0;
            }
            break;
        case 2 : 
            if (!(esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it0.read()) && !esl_seteq<1,1,1>(exitcond2_fu_564_p2.read(), ap_const_lv1_0) && !esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it1.read()))) {
                ap_NS_fsm = ap_ST_pp0_stg1_fsm_2;
            } else {
                ap_NS_fsm = ap_ST_st11_fsm_8;
            }
            break;
        case 4 : 
            if ((!(esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it0.read()) && ap_sig_bdd_323.read()) && !(esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it1.read()) && esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_pp0_stg1_fsm_2.read()) && !(esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it0.read()) && ap_sig_bdd_323.read()) && !esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it0.read())))) {
                ap_NS_fsm = ap_ST_pp0_stg2_fsm_3;
            } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it1.read()) && esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_pp0_stg1_fsm_2.read()) && !(esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it0.read()) && ap_sig_bdd_323.read()) && !esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it0.read()))) {
                ap_NS_fsm = ap_ST_st11_fsm_8;
            } else {
                ap_NS_fsm = ap_ST_pp0_stg1_fsm_2;
            }
            break;
        case 8 : 
            ap_NS_fsm = ap_ST_pp0_stg3_fsm_4;
            break;
        case 16 : 
            ap_NS_fsm = ap_ST_pp0_stg4_fsm_5;
            break;
        case 32 : 
            ap_NS_fsm = ap_ST_pp0_stg5_fsm_6;
            break;
        case 64 : 
            ap_NS_fsm = ap_ST_pp0_stg6_fsm_7;
            break;
        case 128 : 
            ap_NS_fsm = ap_ST_pp0_stg0_fsm_1;
            break;
        case 256 : 
            ap_NS_fsm = ap_ST_st1_fsm_0;
            break;
        default : 
            ap_NS_fsm =  (sc_lv<9>) ("XXXXXXXXX");
            break;
    }
}

}

