// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2015.4
// Copyright (C) 2015 Xilinx Inc. All rights reserved.
// 
// ===========================================================

#include "fire2_copy.h"
#include "AESL_pkg.h"

using namespace std;

namespace ap_rtl {

const sc_logic fire2_copy::ap_const_logic_1 = sc_dt::Log_1;
const sc_logic fire2_copy::ap_const_logic_0 = sc_dt::Log_0;
const sc_lv<3> fire2_copy::ap_ST_st1_fsm_0 = "1";
const sc_lv<3> fire2_copy::ap_ST_pp0_stg0_fsm_1 = "10";
const sc_lv<3> fire2_copy::ap_ST_st4_fsm_2 = "100";
const sc_lv<32> fire2_copy::ap_const_lv32_0 = "00000000000000000000000000000000";
const sc_lv<1> fire2_copy::ap_const_lv1_1 = "1";
const sc_lv<32> fire2_copy::ap_const_lv32_1 = "1";
const sc_lv<1> fire2_copy::ap_const_lv1_0 = "0";
const sc_lv<12> fire2_copy::ap_const_lv12_0 = "000000000000";
const sc_lv<12> fire2_copy::ap_const_lv12_BD1 = "101111010001";
const sc_lv<12> fire2_copy::ap_const_lv12_1 = "1";
const sc_lv<32> fire2_copy::ap_const_lv32_2 = "10";

fire2_copy::fire2_copy(sc_module_name name) : sc_module(name), mVcdFile(0) {

    SC_METHOD(thread_ap_clk_no_reset_);
    dont_initialize();
    sensitive << ( ap_clk.pos() );

    SC_METHOD(thread_ap_done);
    sensitive << ( ap_done_reg );
    sensitive << ( ap_sig_cseq_ST_st4_fsm_2 );

    SC_METHOD(thread_ap_idle);
    sensitive << ( ap_start );
    sensitive << ( ap_sig_cseq_ST_st1_fsm_0 );

    SC_METHOD(thread_ap_ready);
    sensitive << ( ap_sig_cseq_ST_st4_fsm_2 );

    SC_METHOD(thread_ap_sig_bdd_22);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_sig_bdd_230);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_sig_bdd_379);
    sensitive << ( mat_i_0_V_empty_n );
    sensitive << ( mat_i_1_V_empty_n );
    sensitive << ( mat_i_2_V_empty_n );
    sensitive << ( mat_i_3_V_empty_n );
    sensitive << ( mat_i_4_V_empty_n );
    sensitive << ( mat_i_5_V_empty_n );
    sensitive << ( mat_i_6_V_empty_n );
    sensitive << ( mat_i_7_V_empty_n );
    sensitive << ( mat_i_8_V_empty_n );
    sensitive << ( mat_i_9_V_empty_n );
    sensitive << ( mat_i_10_V_empty_n );
    sensitive << ( mat_i_11_V_empty_n );
    sensitive << ( mat_i_12_V_empty_n );
    sensitive << ( mat_i_13_V_empty_n );
    sensitive << ( mat_i_14_V_empty_n );
    sensitive << ( mat_i_15_V_empty_n );
    sensitive << ( mat1_o_0_V_full_n );
    sensitive << ( mat1_o_1_V_full_n );
    sensitive << ( mat1_o_2_V_full_n );
    sensitive << ( mat1_o_3_V_full_n );
    sensitive << ( mat1_o_4_V_full_n );
    sensitive << ( mat1_o_5_V_full_n );
    sensitive << ( mat1_o_6_V_full_n );
    sensitive << ( mat1_o_7_V_full_n );
    sensitive << ( mat1_o_8_V_full_n );
    sensitive << ( mat1_o_9_V_full_n );
    sensitive << ( mat1_o_10_V_full_n );
    sensitive << ( mat1_o_11_V_full_n );
    sensitive << ( mat1_o_12_V_full_n );
    sensitive << ( mat1_o_13_V_full_n );
    sensitive << ( mat1_o_14_V_full_n );
    sensitive << ( mat1_o_15_V_full_n );
    sensitive << ( mat2_o_0_V_full_n );
    sensitive << ( mat2_o_1_V_full_n );
    sensitive << ( mat2_o_2_V_full_n );
    sensitive << ( mat2_o_3_V_full_n );
    sensitive << ( mat2_o_4_V_full_n );
    sensitive << ( mat2_o_5_V_full_n );
    sensitive << ( mat2_o_6_V_full_n );
    sensitive << ( mat2_o_7_V_full_n );
    sensitive << ( mat2_o_8_V_full_n );
    sensitive << ( mat2_o_9_V_full_n );
    sensitive << ( mat2_o_10_V_full_n );
    sensitive << ( mat2_o_11_V_full_n );
    sensitive << ( mat2_o_12_V_full_n );
    sensitive << ( mat2_o_13_V_full_n );
    sensitive << ( mat2_o_14_V_full_n );
    sensitive << ( mat2_o_15_V_full_n );
    sensitive << ( exitcond_flatten_reg_891 );

    SC_METHOD(thread_ap_sig_bdd_392);
    sensitive << ( ap_start );
    sensitive << ( ap_done_reg );

    SC_METHOD(thread_ap_sig_bdd_483);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_sig_cseq_ST_pp0_stg0_fsm_1);
    sensitive << ( ap_sig_bdd_230 );

    SC_METHOD(thread_ap_sig_cseq_ST_st1_fsm_0);
    sensitive << ( ap_sig_bdd_22 );

    SC_METHOD(thread_ap_sig_cseq_ST_st4_fsm_2);
    sensitive << ( ap_sig_bdd_483 );

    SC_METHOD(thread_exitcond_flatten_fu_879_p2);
    sensitive << ( indvar_flatten_reg_868 );
    sensitive << ( ap_sig_cseq_ST_pp0_stg0_fsm_1 );
    sensitive << ( ap_reg_ppiten_pp0_it0 );
    sensitive << ( ap_sig_bdd_379 );
    sensitive << ( ap_reg_ppiten_pp0_it1 );

    SC_METHOD(thread_indvar_flatten_next_fu_885_p2);
    sensitive << ( indvar_flatten_reg_868 );

    SC_METHOD(thread_mat1_o_0_V_din);
    sensitive << ( mat_i_0_V_dout );
    sensitive << ( exitcond_flatten_reg_891 );
    sensitive << ( ap_sig_cseq_ST_pp0_stg0_fsm_1 );
    sensitive << ( ap_sig_bdd_379 );
    sensitive << ( ap_reg_ppiten_pp0_it1 );

    SC_METHOD(thread_mat1_o_0_V_write);
    sensitive << ( exitcond_flatten_reg_891 );
    sensitive << ( ap_sig_cseq_ST_pp0_stg0_fsm_1 );
    sensitive << ( ap_sig_bdd_379 );
    sensitive << ( ap_reg_ppiten_pp0_it1 );

    SC_METHOD(thread_mat1_o_10_V_din);
    sensitive << ( mat_i_10_V_dout );
    sensitive << ( exitcond_flatten_reg_891 );
    sensitive << ( ap_sig_cseq_ST_pp0_stg0_fsm_1 );
    sensitive << ( ap_sig_bdd_379 );
    sensitive << ( ap_reg_ppiten_pp0_it1 );

    SC_METHOD(thread_mat1_o_10_V_write);
    sensitive << ( exitcond_flatten_reg_891 );
    sensitive << ( ap_sig_cseq_ST_pp0_stg0_fsm_1 );
    sensitive << ( ap_sig_bdd_379 );
    sensitive << ( ap_reg_ppiten_pp0_it1 );

    SC_METHOD(thread_mat1_o_11_V_din);
    sensitive << ( mat_i_11_V_dout );
    sensitive << ( exitcond_flatten_reg_891 );
    sensitive << ( ap_sig_cseq_ST_pp0_stg0_fsm_1 );
    sensitive << ( ap_sig_bdd_379 );
    sensitive << ( ap_reg_ppiten_pp0_it1 );

    SC_METHOD(thread_mat1_o_11_V_write);
    sensitive << ( exitcond_flatten_reg_891 );
    sensitive << ( ap_sig_cseq_ST_pp0_stg0_fsm_1 );
    sensitive << ( ap_sig_bdd_379 );
    sensitive << ( ap_reg_ppiten_pp0_it1 );

    SC_METHOD(thread_mat1_o_12_V_din);
    sensitive << ( mat_i_12_V_dout );
    sensitive << ( exitcond_flatten_reg_891 );
    sensitive << ( ap_sig_cseq_ST_pp0_stg0_fsm_1 );
    sensitive << ( ap_sig_bdd_379 );
    sensitive << ( ap_reg_ppiten_pp0_it1 );

    SC_METHOD(thread_mat1_o_12_V_write);
    sensitive << ( exitcond_flatten_reg_891 );
    sensitive << ( ap_sig_cseq_ST_pp0_stg0_fsm_1 );
    sensitive << ( ap_sig_bdd_379 );
    sensitive << ( ap_reg_ppiten_pp0_it1 );

    SC_METHOD(thread_mat1_o_13_V_din);
    sensitive << ( mat_i_13_V_dout );
    sensitive << ( exitcond_flatten_reg_891 );
    sensitive << ( ap_sig_cseq_ST_pp0_stg0_fsm_1 );
    sensitive << ( ap_sig_bdd_379 );
    sensitive << ( ap_reg_ppiten_pp0_it1 );

    SC_METHOD(thread_mat1_o_13_V_write);
    sensitive << ( exitcond_flatten_reg_891 );
    sensitive << ( ap_sig_cseq_ST_pp0_stg0_fsm_1 );
    sensitive << ( ap_sig_bdd_379 );
    sensitive << ( ap_reg_ppiten_pp0_it1 );

    SC_METHOD(thread_mat1_o_14_V_din);
    sensitive << ( mat_i_14_V_dout );
    sensitive << ( exitcond_flatten_reg_891 );
    sensitive << ( ap_sig_cseq_ST_pp0_stg0_fsm_1 );
    sensitive << ( ap_sig_bdd_379 );
    sensitive << ( ap_reg_ppiten_pp0_it1 );

    SC_METHOD(thread_mat1_o_14_V_write);
    sensitive << ( exitcond_flatten_reg_891 );
    sensitive << ( ap_sig_cseq_ST_pp0_stg0_fsm_1 );
    sensitive << ( ap_sig_bdd_379 );
    sensitive << ( ap_reg_ppiten_pp0_it1 );

    SC_METHOD(thread_mat1_o_15_V_din);
    sensitive << ( mat_i_15_V_dout );
    sensitive << ( exitcond_flatten_reg_891 );
    sensitive << ( ap_sig_cseq_ST_pp0_stg0_fsm_1 );
    sensitive << ( ap_sig_bdd_379 );
    sensitive << ( ap_reg_ppiten_pp0_it1 );

    SC_METHOD(thread_mat1_o_15_V_write);
    sensitive << ( exitcond_flatten_reg_891 );
    sensitive << ( ap_sig_cseq_ST_pp0_stg0_fsm_1 );
    sensitive << ( ap_sig_bdd_379 );
    sensitive << ( ap_reg_ppiten_pp0_it1 );

    SC_METHOD(thread_mat1_o_1_V_din);
    sensitive << ( mat_i_1_V_dout );
    sensitive << ( exitcond_flatten_reg_891 );
    sensitive << ( ap_sig_cseq_ST_pp0_stg0_fsm_1 );
    sensitive << ( ap_sig_bdd_379 );
    sensitive << ( ap_reg_ppiten_pp0_it1 );

    SC_METHOD(thread_mat1_o_1_V_write);
    sensitive << ( exitcond_flatten_reg_891 );
    sensitive << ( ap_sig_cseq_ST_pp0_stg0_fsm_1 );
    sensitive << ( ap_sig_bdd_379 );
    sensitive << ( ap_reg_ppiten_pp0_it1 );

    SC_METHOD(thread_mat1_o_2_V_din);
    sensitive << ( mat_i_2_V_dout );
    sensitive << ( exitcond_flatten_reg_891 );
    sensitive << ( ap_sig_cseq_ST_pp0_stg0_fsm_1 );
    sensitive << ( ap_sig_bdd_379 );
    sensitive << ( ap_reg_ppiten_pp0_it1 );

    SC_METHOD(thread_mat1_o_2_V_write);
    sensitive << ( exitcond_flatten_reg_891 );
    sensitive << ( ap_sig_cseq_ST_pp0_stg0_fsm_1 );
    sensitive << ( ap_sig_bdd_379 );
    sensitive << ( ap_reg_ppiten_pp0_it1 );

    SC_METHOD(thread_mat1_o_3_V_din);
    sensitive << ( mat_i_3_V_dout );
    sensitive << ( exitcond_flatten_reg_891 );
    sensitive << ( ap_sig_cseq_ST_pp0_stg0_fsm_1 );
    sensitive << ( ap_sig_bdd_379 );
    sensitive << ( ap_reg_ppiten_pp0_it1 );

    SC_METHOD(thread_mat1_o_3_V_write);
    sensitive << ( exitcond_flatten_reg_891 );
    sensitive << ( ap_sig_cseq_ST_pp0_stg0_fsm_1 );
    sensitive << ( ap_sig_bdd_379 );
    sensitive << ( ap_reg_ppiten_pp0_it1 );

    SC_METHOD(thread_mat1_o_4_V_din);
    sensitive << ( mat_i_4_V_dout );
    sensitive << ( exitcond_flatten_reg_891 );
    sensitive << ( ap_sig_cseq_ST_pp0_stg0_fsm_1 );
    sensitive << ( ap_sig_bdd_379 );
    sensitive << ( ap_reg_ppiten_pp0_it1 );

    SC_METHOD(thread_mat1_o_4_V_write);
    sensitive << ( exitcond_flatten_reg_891 );
    sensitive << ( ap_sig_cseq_ST_pp0_stg0_fsm_1 );
    sensitive << ( ap_sig_bdd_379 );
    sensitive << ( ap_reg_ppiten_pp0_it1 );

    SC_METHOD(thread_mat1_o_5_V_din);
    sensitive << ( mat_i_5_V_dout );
    sensitive << ( exitcond_flatten_reg_891 );
    sensitive << ( ap_sig_cseq_ST_pp0_stg0_fsm_1 );
    sensitive << ( ap_sig_bdd_379 );
    sensitive << ( ap_reg_ppiten_pp0_it1 );

    SC_METHOD(thread_mat1_o_5_V_write);
    sensitive << ( exitcond_flatten_reg_891 );
    sensitive << ( ap_sig_cseq_ST_pp0_stg0_fsm_1 );
    sensitive << ( ap_sig_bdd_379 );
    sensitive << ( ap_reg_ppiten_pp0_it1 );

    SC_METHOD(thread_mat1_o_6_V_din);
    sensitive << ( mat_i_6_V_dout );
    sensitive << ( exitcond_flatten_reg_891 );
    sensitive << ( ap_sig_cseq_ST_pp0_stg0_fsm_1 );
    sensitive << ( ap_sig_bdd_379 );
    sensitive << ( ap_reg_ppiten_pp0_it1 );

    SC_METHOD(thread_mat1_o_6_V_write);
    sensitive << ( exitcond_flatten_reg_891 );
    sensitive << ( ap_sig_cseq_ST_pp0_stg0_fsm_1 );
    sensitive << ( ap_sig_bdd_379 );
    sensitive << ( ap_reg_ppiten_pp0_it1 );

    SC_METHOD(thread_mat1_o_7_V_din);
    sensitive << ( mat_i_7_V_dout );
    sensitive << ( exitcond_flatten_reg_891 );
    sensitive << ( ap_sig_cseq_ST_pp0_stg0_fsm_1 );
    sensitive << ( ap_sig_bdd_379 );
    sensitive << ( ap_reg_ppiten_pp0_it1 );

    SC_METHOD(thread_mat1_o_7_V_write);
    sensitive << ( exitcond_flatten_reg_891 );
    sensitive << ( ap_sig_cseq_ST_pp0_stg0_fsm_1 );
    sensitive << ( ap_sig_bdd_379 );
    sensitive << ( ap_reg_ppiten_pp0_it1 );

    SC_METHOD(thread_mat1_o_8_V_din);
    sensitive << ( mat_i_8_V_dout );
    sensitive << ( exitcond_flatten_reg_891 );
    sensitive << ( ap_sig_cseq_ST_pp0_stg0_fsm_1 );
    sensitive << ( ap_sig_bdd_379 );
    sensitive << ( ap_reg_ppiten_pp0_it1 );

    SC_METHOD(thread_mat1_o_8_V_write);
    sensitive << ( exitcond_flatten_reg_891 );
    sensitive << ( ap_sig_cseq_ST_pp0_stg0_fsm_1 );
    sensitive << ( ap_sig_bdd_379 );
    sensitive << ( ap_reg_ppiten_pp0_it1 );

    SC_METHOD(thread_mat1_o_9_V_din);
    sensitive << ( mat_i_9_V_dout );
    sensitive << ( exitcond_flatten_reg_891 );
    sensitive << ( ap_sig_cseq_ST_pp0_stg0_fsm_1 );
    sensitive << ( ap_sig_bdd_379 );
    sensitive << ( ap_reg_ppiten_pp0_it1 );

    SC_METHOD(thread_mat1_o_9_V_write);
    sensitive << ( exitcond_flatten_reg_891 );
    sensitive << ( ap_sig_cseq_ST_pp0_stg0_fsm_1 );
    sensitive << ( ap_sig_bdd_379 );
    sensitive << ( ap_reg_ppiten_pp0_it1 );

    SC_METHOD(thread_mat2_o_0_V_din);
    sensitive << ( mat_i_0_V_dout );
    sensitive << ( exitcond_flatten_reg_891 );
    sensitive << ( ap_sig_cseq_ST_pp0_stg0_fsm_1 );
    sensitive << ( ap_sig_bdd_379 );
    sensitive << ( ap_reg_ppiten_pp0_it1 );

    SC_METHOD(thread_mat2_o_0_V_write);
    sensitive << ( exitcond_flatten_reg_891 );
    sensitive << ( ap_sig_cseq_ST_pp0_stg0_fsm_1 );
    sensitive << ( ap_sig_bdd_379 );
    sensitive << ( ap_reg_ppiten_pp0_it1 );

    SC_METHOD(thread_mat2_o_10_V_din);
    sensitive << ( mat_i_10_V_dout );
    sensitive << ( exitcond_flatten_reg_891 );
    sensitive << ( ap_sig_cseq_ST_pp0_stg0_fsm_1 );
    sensitive << ( ap_sig_bdd_379 );
    sensitive << ( ap_reg_ppiten_pp0_it1 );

    SC_METHOD(thread_mat2_o_10_V_write);
    sensitive << ( exitcond_flatten_reg_891 );
    sensitive << ( ap_sig_cseq_ST_pp0_stg0_fsm_1 );
    sensitive << ( ap_sig_bdd_379 );
    sensitive << ( ap_reg_ppiten_pp0_it1 );

    SC_METHOD(thread_mat2_o_11_V_din);
    sensitive << ( mat_i_11_V_dout );
    sensitive << ( exitcond_flatten_reg_891 );
    sensitive << ( ap_sig_cseq_ST_pp0_stg0_fsm_1 );
    sensitive << ( ap_sig_bdd_379 );
    sensitive << ( ap_reg_ppiten_pp0_it1 );

    SC_METHOD(thread_mat2_o_11_V_write);
    sensitive << ( exitcond_flatten_reg_891 );
    sensitive << ( ap_sig_cseq_ST_pp0_stg0_fsm_1 );
    sensitive << ( ap_sig_bdd_379 );
    sensitive << ( ap_reg_ppiten_pp0_it1 );

    SC_METHOD(thread_mat2_o_12_V_din);
    sensitive << ( mat_i_12_V_dout );
    sensitive << ( exitcond_flatten_reg_891 );
    sensitive << ( ap_sig_cseq_ST_pp0_stg0_fsm_1 );
    sensitive << ( ap_sig_bdd_379 );
    sensitive << ( ap_reg_ppiten_pp0_it1 );

    SC_METHOD(thread_mat2_o_12_V_write);
    sensitive << ( exitcond_flatten_reg_891 );
    sensitive << ( ap_sig_cseq_ST_pp0_stg0_fsm_1 );
    sensitive << ( ap_sig_bdd_379 );
    sensitive << ( ap_reg_ppiten_pp0_it1 );

    SC_METHOD(thread_mat2_o_13_V_din);
    sensitive << ( mat_i_13_V_dout );
    sensitive << ( exitcond_flatten_reg_891 );
    sensitive << ( ap_sig_cseq_ST_pp0_stg0_fsm_1 );
    sensitive << ( ap_sig_bdd_379 );
    sensitive << ( ap_reg_ppiten_pp0_it1 );

    SC_METHOD(thread_mat2_o_13_V_write);
    sensitive << ( exitcond_flatten_reg_891 );
    sensitive << ( ap_sig_cseq_ST_pp0_stg0_fsm_1 );
    sensitive << ( ap_sig_bdd_379 );
    sensitive << ( ap_reg_ppiten_pp0_it1 );

    SC_METHOD(thread_mat2_o_14_V_din);
    sensitive << ( mat_i_14_V_dout );
    sensitive << ( exitcond_flatten_reg_891 );
    sensitive << ( ap_sig_cseq_ST_pp0_stg0_fsm_1 );
    sensitive << ( ap_sig_bdd_379 );
    sensitive << ( ap_reg_ppiten_pp0_it1 );

    SC_METHOD(thread_mat2_o_14_V_write);
    sensitive << ( exitcond_flatten_reg_891 );
    sensitive << ( ap_sig_cseq_ST_pp0_stg0_fsm_1 );
    sensitive << ( ap_sig_bdd_379 );
    sensitive << ( ap_reg_ppiten_pp0_it1 );

    SC_METHOD(thread_mat2_o_15_V_din);
    sensitive << ( mat_i_15_V_dout );
    sensitive << ( exitcond_flatten_reg_891 );
    sensitive << ( ap_sig_cseq_ST_pp0_stg0_fsm_1 );
    sensitive << ( ap_sig_bdd_379 );
    sensitive << ( ap_reg_ppiten_pp0_it1 );

    SC_METHOD(thread_mat2_o_15_V_write);
    sensitive << ( exitcond_flatten_reg_891 );
    sensitive << ( ap_sig_cseq_ST_pp0_stg0_fsm_1 );
    sensitive << ( ap_sig_bdd_379 );
    sensitive << ( ap_reg_ppiten_pp0_it1 );

    SC_METHOD(thread_mat2_o_1_V_din);
    sensitive << ( mat_i_1_V_dout );
    sensitive << ( exitcond_flatten_reg_891 );
    sensitive << ( ap_sig_cseq_ST_pp0_stg0_fsm_1 );
    sensitive << ( ap_sig_bdd_379 );
    sensitive << ( ap_reg_ppiten_pp0_it1 );

    SC_METHOD(thread_mat2_o_1_V_write);
    sensitive << ( exitcond_flatten_reg_891 );
    sensitive << ( ap_sig_cseq_ST_pp0_stg0_fsm_1 );
    sensitive << ( ap_sig_bdd_379 );
    sensitive << ( ap_reg_ppiten_pp0_it1 );

    SC_METHOD(thread_mat2_o_2_V_din);
    sensitive << ( mat_i_2_V_dout );
    sensitive << ( exitcond_flatten_reg_891 );
    sensitive << ( ap_sig_cseq_ST_pp0_stg0_fsm_1 );
    sensitive << ( ap_sig_bdd_379 );
    sensitive << ( ap_reg_ppiten_pp0_it1 );

    SC_METHOD(thread_mat2_o_2_V_write);
    sensitive << ( exitcond_flatten_reg_891 );
    sensitive << ( ap_sig_cseq_ST_pp0_stg0_fsm_1 );
    sensitive << ( ap_sig_bdd_379 );
    sensitive << ( ap_reg_ppiten_pp0_it1 );

    SC_METHOD(thread_mat2_o_3_V_din);
    sensitive << ( mat_i_3_V_dout );
    sensitive << ( exitcond_flatten_reg_891 );
    sensitive << ( ap_sig_cseq_ST_pp0_stg0_fsm_1 );
    sensitive << ( ap_sig_bdd_379 );
    sensitive << ( ap_reg_ppiten_pp0_it1 );

    SC_METHOD(thread_mat2_o_3_V_write);
    sensitive << ( exitcond_flatten_reg_891 );
    sensitive << ( ap_sig_cseq_ST_pp0_stg0_fsm_1 );
    sensitive << ( ap_sig_bdd_379 );
    sensitive << ( ap_reg_ppiten_pp0_it1 );

    SC_METHOD(thread_mat2_o_4_V_din);
    sensitive << ( mat_i_4_V_dout );
    sensitive << ( exitcond_flatten_reg_891 );
    sensitive << ( ap_sig_cseq_ST_pp0_stg0_fsm_1 );
    sensitive << ( ap_sig_bdd_379 );
    sensitive << ( ap_reg_ppiten_pp0_it1 );

    SC_METHOD(thread_mat2_o_4_V_write);
    sensitive << ( exitcond_flatten_reg_891 );
    sensitive << ( ap_sig_cseq_ST_pp0_stg0_fsm_1 );
    sensitive << ( ap_sig_bdd_379 );
    sensitive << ( ap_reg_ppiten_pp0_it1 );

    SC_METHOD(thread_mat2_o_5_V_din);
    sensitive << ( mat_i_5_V_dout );
    sensitive << ( exitcond_flatten_reg_891 );
    sensitive << ( ap_sig_cseq_ST_pp0_stg0_fsm_1 );
    sensitive << ( ap_sig_bdd_379 );
    sensitive << ( ap_reg_ppiten_pp0_it1 );

    SC_METHOD(thread_mat2_o_5_V_write);
    sensitive << ( exitcond_flatten_reg_891 );
    sensitive << ( ap_sig_cseq_ST_pp0_stg0_fsm_1 );
    sensitive << ( ap_sig_bdd_379 );
    sensitive << ( ap_reg_ppiten_pp0_it1 );

    SC_METHOD(thread_mat2_o_6_V_din);
    sensitive << ( mat_i_6_V_dout );
    sensitive << ( exitcond_flatten_reg_891 );
    sensitive << ( ap_sig_cseq_ST_pp0_stg0_fsm_1 );
    sensitive << ( ap_sig_bdd_379 );
    sensitive << ( ap_reg_ppiten_pp0_it1 );

    SC_METHOD(thread_mat2_o_6_V_write);
    sensitive << ( exitcond_flatten_reg_891 );
    sensitive << ( ap_sig_cseq_ST_pp0_stg0_fsm_1 );
    sensitive << ( ap_sig_bdd_379 );
    sensitive << ( ap_reg_ppiten_pp0_it1 );

    SC_METHOD(thread_mat2_o_7_V_din);
    sensitive << ( mat_i_7_V_dout );
    sensitive << ( exitcond_flatten_reg_891 );
    sensitive << ( ap_sig_cseq_ST_pp0_stg0_fsm_1 );
    sensitive << ( ap_sig_bdd_379 );
    sensitive << ( ap_reg_ppiten_pp0_it1 );

    SC_METHOD(thread_mat2_o_7_V_write);
    sensitive << ( exitcond_flatten_reg_891 );
    sensitive << ( ap_sig_cseq_ST_pp0_stg0_fsm_1 );
    sensitive << ( ap_sig_bdd_379 );
    sensitive << ( ap_reg_ppiten_pp0_it1 );

    SC_METHOD(thread_mat2_o_8_V_din);
    sensitive << ( mat_i_8_V_dout );
    sensitive << ( exitcond_flatten_reg_891 );
    sensitive << ( ap_sig_cseq_ST_pp0_stg0_fsm_1 );
    sensitive << ( ap_sig_bdd_379 );
    sensitive << ( ap_reg_ppiten_pp0_it1 );

    SC_METHOD(thread_mat2_o_8_V_write);
    sensitive << ( exitcond_flatten_reg_891 );
    sensitive << ( ap_sig_cseq_ST_pp0_stg0_fsm_1 );
    sensitive << ( ap_sig_bdd_379 );
    sensitive << ( ap_reg_ppiten_pp0_it1 );

    SC_METHOD(thread_mat2_o_9_V_din);
    sensitive << ( mat_i_9_V_dout );
    sensitive << ( exitcond_flatten_reg_891 );
    sensitive << ( ap_sig_cseq_ST_pp0_stg0_fsm_1 );
    sensitive << ( ap_sig_bdd_379 );
    sensitive << ( ap_reg_ppiten_pp0_it1 );

    SC_METHOD(thread_mat2_o_9_V_write);
    sensitive << ( exitcond_flatten_reg_891 );
    sensitive << ( ap_sig_cseq_ST_pp0_stg0_fsm_1 );
    sensitive << ( ap_sig_bdd_379 );
    sensitive << ( ap_reg_ppiten_pp0_it1 );

    SC_METHOD(thread_mat_i_0_V_read);
    sensitive << ( exitcond_flatten_reg_891 );
    sensitive << ( ap_sig_cseq_ST_pp0_stg0_fsm_1 );
    sensitive << ( ap_sig_bdd_379 );
    sensitive << ( ap_reg_ppiten_pp0_it1 );

    SC_METHOD(thread_mat_i_10_V_read);
    sensitive << ( exitcond_flatten_reg_891 );
    sensitive << ( ap_sig_cseq_ST_pp0_stg0_fsm_1 );
    sensitive << ( ap_sig_bdd_379 );
    sensitive << ( ap_reg_ppiten_pp0_it1 );

    SC_METHOD(thread_mat_i_11_V_read);
    sensitive << ( exitcond_flatten_reg_891 );
    sensitive << ( ap_sig_cseq_ST_pp0_stg0_fsm_1 );
    sensitive << ( ap_sig_bdd_379 );
    sensitive << ( ap_reg_ppiten_pp0_it1 );

    SC_METHOD(thread_mat_i_12_V_read);
    sensitive << ( exitcond_flatten_reg_891 );
    sensitive << ( ap_sig_cseq_ST_pp0_stg0_fsm_1 );
    sensitive << ( ap_sig_bdd_379 );
    sensitive << ( ap_reg_ppiten_pp0_it1 );

    SC_METHOD(thread_mat_i_13_V_read);
    sensitive << ( exitcond_flatten_reg_891 );
    sensitive << ( ap_sig_cseq_ST_pp0_stg0_fsm_1 );
    sensitive << ( ap_sig_bdd_379 );
    sensitive << ( ap_reg_ppiten_pp0_it1 );

    SC_METHOD(thread_mat_i_14_V_read);
    sensitive << ( exitcond_flatten_reg_891 );
    sensitive << ( ap_sig_cseq_ST_pp0_stg0_fsm_1 );
    sensitive << ( ap_sig_bdd_379 );
    sensitive << ( ap_reg_ppiten_pp0_it1 );

    SC_METHOD(thread_mat_i_15_V_read);
    sensitive << ( exitcond_flatten_reg_891 );
    sensitive << ( ap_sig_cseq_ST_pp0_stg0_fsm_1 );
    sensitive << ( ap_sig_bdd_379 );
    sensitive << ( ap_reg_ppiten_pp0_it1 );

    SC_METHOD(thread_mat_i_1_V_read);
    sensitive << ( exitcond_flatten_reg_891 );
    sensitive << ( ap_sig_cseq_ST_pp0_stg0_fsm_1 );
    sensitive << ( ap_sig_bdd_379 );
    sensitive << ( ap_reg_ppiten_pp0_it1 );

    SC_METHOD(thread_mat_i_2_V_read);
    sensitive << ( exitcond_flatten_reg_891 );
    sensitive << ( ap_sig_cseq_ST_pp0_stg0_fsm_1 );
    sensitive << ( ap_sig_bdd_379 );
    sensitive << ( ap_reg_ppiten_pp0_it1 );

    SC_METHOD(thread_mat_i_3_V_read);
    sensitive << ( exitcond_flatten_reg_891 );
    sensitive << ( ap_sig_cseq_ST_pp0_stg0_fsm_1 );
    sensitive << ( ap_sig_bdd_379 );
    sensitive << ( ap_reg_ppiten_pp0_it1 );

    SC_METHOD(thread_mat_i_4_V_read);
    sensitive << ( exitcond_flatten_reg_891 );
    sensitive << ( ap_sig_cseq_ST_pp0_stg0_fsm_1 );
    sensitive << ( ap_sig_bdd_379 );
    sensitive << ( ap_reg_ppiten_pp0_it1 );

    SC_METHOD(thread_mat_i_5_V_read);
    sensitive << ( exitcond_flatten_reg_891 );
    sensitive << ( ap_sig_cseq_ST_pp0_stg0_fsm_1 );
    sensitive << ( ap_sig_bdd_379 );
    sensitive << ( ap_reg_ppiten_pp0_it1 );

    SC_METHOD(thread_mat_i_6_V_read);
    sensitive << ( exitcond_flatten_reg_891 );
    sensitive << ( ap_sig_cseq_ST_pp0_stg0_fsm_1 );
    sensitive << ( ap_sig_bdd_379 );
    sensitive << ( ap_reg_ppiten_pp0_it1 );

    SC_METHOD(thread_mat_i_7_V_read);
    sensitive << ( exitcond_flatten_reg_891 );
    sensitive << ( ap_sig_cseq_ST_pp0_stg0_fsm_1 );
    sensitive << ( ap_sig_bdd_379 );
    sensitive << ( ap_reg_ppiten_pp0_it1 );

    SC_METHOD(thread_mat_i_8_V_read);
    sensitive << ( exitcond_flatten_reg_891 );
    sensitive << ( ap_sig_cseq_ST_pp0_stg0_fsm_1 );
    sensitive << ( ap_sig_bdd_379 );
    sensitive << ( ap_reg_ppiten_pp0_it1 );

    SC_METHOD(thread_mat_i_9_V_read);
    sensitive << ( exitcond_flatten_reg_891 );
    sensitive << ( ap_sig_cseq_ST_pp0_stg0_fsm_1 );
    sensitive << ( ap_sig_bdd_379 );
    sensitive << ( ap_reg_ppiten_pp0_it1 );

    SC_METHOD(thread_ap_NS_fsm);
    sensitive << ( ap_CS_fsm );
    sensitive << ( exitcond_flatten_fu_879_p2 );
    sensitive << ( ap_reg_ppiten_pp0_it0 );
    sensitive << ( ap_sig_bdd_379 );
    sensitive << ( ap_reg_ppiten_pp0_it1 );
    sensitive << ( ap_sig_bdd_392 );

    ap_done_reg = SC_LOGIC_0;
    ap_CS_fsm = "001";
    ap_reg_ppiten_pp0_it0 = SC_LOGIC_0;
    ap_reg_ppiten_pp0_it1 = SC_LOGIC_0;
    static int apTFileNum = 0;
    stringstream apTFilenSS;
    apTFilenSS << "fire2_copy_sc_trace_" << apTFileNum ++;
    string apTFn = apTFilenSS.str();
    mVcdFile = sc_create_vcd_trace_file(apTFn.c_str());
    mVcdFile->set_time_unit(1, SC_PS);
    if (1) {
#ifdef __HLS_TRACE_LEVEL_PORT_HIER__
    sc_trace(mVcdFile, ap_clk, "(port)ap_clk");
    sc_trace(mVcdFile, ap_rst, "(port)ap_rst");
    sc_trace(mVcdFile, ap_start, "(port)ap_start");
    sc_trace(mVcdFile, ap_done, "(port)ap_done");
    sc_trace(mVcdFile, ap_continue, "(port)ap_continue");
    sc_trace(mVcdFile, ap_idle, "(port)ap_idle");
    sc_trace(mVcdFile, ap_ready, "(port)ap_ready");
    sc_trace(mVcdFile, mat_i_0_V_dout, "(port)mat_i_0_V_dout");
    sc_trace(mVcdFile, mat_i_0_V_empty_n, "(port)mat_i_0_V_empty_n");
    sc_trace(mVcdFile, mat_i_0_V_read, "(port)mat_i_0_V_read");
    sc_trace(mVcdFile, mat_i_1_V_dout, "(port)mat_i_1_V_dout");
    sc_trace(mVcdFile, mat_i_1_V_empty_n, "(port)mat_i_1_V_empty_n");
    sc_trace(mVcdFile, mat_i_1_V_read, "(port)mat_i_1_V_read");
    sc_trace(mVcdFile, mat_i_2_V_dout, "(port)mat_i_2_V_dout");
    sc_trace(mVcdFile, mat_i_2_V_empty_n, "(port)mat_i_2_V_empty_n");
    sc_trace(mVcdFile, mat_i_2_V_read, "(port)mat_i_2_V_read");
    sc_trace(mVcdFile, mat_i_3_V_dout, "(port)mat_i_3_V_dout");
    sc_trace(mVcdFile, mat_i_3_V_empty_n, "(port)mat_i_3_V_empty_n");
    sc_trace(mVcdFile, mat_i_3_V_read, "(port)mat_i_3_V_read");
    sc_trace(mVcdFile, mat_i_4_V_dout, "(port)mat_i_4_V_dout");
    sc_trace(mVcdFile, mat_i_4_V_empty_n, "(port)mat_i_4_V_empty_n");
    sc_trace(mVcdFile, mat_i_4_V_read, "(port)mat_i_4_V_read");
    sc_trace(mVcdFile, mat_i_5_V_dout, "(port)mat_i_5_V_dout");
    sc_trace(mVcdFile, mat_i_5_V_empty_n, "(port)mat_i_5_V_empty_n");
    sc_trace(mVcdFile, mat_i_5_V_read, "(port)mat_i_5_V_read");
    sc_trace(mVcdFile, mat_i_6_V_dout, "(port)mat_i_6_V_dout");
    sc_trace(mVcdFile, mat_i_6_V_empty_n, "(port)mat_i_6_V_empty_n");
    sc_trace(mVcdFile, mat_i_6_V_read, "(port)mat_i_6_V_read");
    sc_trace(mVcdFile, mat_i_7_V_dout, "(port)mat_i_7_V_dout");
    sc_trace(mVcdFile, mat_i_7_V_empty_n, "(port)mat_i_7_V_empty_n");
    sc_trace(mVcdFile, mat_i_7_V_read, "(port)mat_i_7_V_read");
    sc_trace(mVcdFile, mat_i_8_V_dout, "(port)mat_i_8_V_dout");
    sc_trace(mVcdFile, mat_i_8_V_empty_n, "(port)mat_i_8_V_empty_n");
    sc_trace(mVcdFile, mat_i_8_V_read, "(port)mat_i_8_V_read");
    sc_trace(mVcdFile, mat_i_9_V_dout, "(port)mat_i_9_V_dout");
    sc_trace(mVcdFile, mat_i_9_V_empty_n, "(port)mat_i_9_V_empty_n");
    sc_trace(mVcdFile, mat_i_9_V_read, "(port)mat_i_9_V_read");
    sc_trace(mVcdFile, mat_i_10_V_dout, "(port)mat_i_10_V_dout");
    sc_trace(mVcdFile, mat_i_10_V_empty_n, "(port)mat_i_10_V_empty_n");
    sc_trace(mVcdFile, mat_i_10_V_read, "(port)mat_i_10_V_read");
    sc_trace(mVcdFile, mat_i_11_V_dout, "(port)mat_i_11_V_dout");
    sc_trace(mVcdFile, mat_i_11_V_empty_n, "(port)mat_i_11_V_empty_n");
    sc_trace(mVcdFile, mat_i_11_V_read, "(port)mat_i_11_V_read");
    sc_trace(mVcdFile, mat_i_12_V_dout, "(port)mat_i_12_V_dout");
    sc_trace(mVcdFile, mat_i_12_V_empty_n, "(port)mat_i_12_V_empty_n");
    sc_trace(mVcdFile, mat_i_12_V_read, "(port)mat_i_12_V_read");
    sc_trace(mVcdFile, mat_i_13_V_dout, "(port)mat_i_13_V_dout");
    sc_trace(mVcdFile, mat_i_13_V_empty_n, "(port)mat_i_13_V_empty_n");
    sc_trace(mVcdFile, mat_i_13_V_read, "(port)mat_i_13_V_read");
    sc_trace(mVcdFile, mat_i_14_V_dout, "(port)mat_i_14_V_dout");
    sc_trace(mVcdFile, mat_i_14_V_empty_n, "(port)mat_i_14_V_empty_n");
    sc_trace(mVcdFile, mat_i_14_V_read, "(port)mat_i_14_V_read");
    sc_trace(mVcdFile, mat_i_15_V_dout, "(port)mat_i_15_V_dout");
    sc_trace(mVcdFile, mat_i_15_V_empty_n, "(port)mat_i_15_V_empty_n");
    sc_trace(mVcdFile, mat_i_15_V_read, "(port)mat_i_15_V_read");
    sc_trace(mVcdFile, mat1_o_0_V_din, "(port)mat1_o_0_V_din");
    sc_trace(mVcdFile, mat1_o_0_V_full_n, "(port)mat1_o_0_V_full_n");
    sc_trace(mVcdFile, mat1_o_0_V_write, "(port)mat1_o_0_V_write");
    sc_trace(mVcdFile, mat1_o_1_V_din, "(port)mat1_o_1_V_din");
    sc_trace(mVcdFile, mat1_o_1_V_full_n, "(port)mat1_o_1_V_full_n");
    sc_trace(mVcdFile, mat1_o_1_V_write, "(port)mat1_o_1_V_write");
    sc_trace(mVcdFile, mat1_o_2_V_din, "(port)mat1_o_2_V_din");
    sc_trace(mVcdFile, mat1_o_2_V_full_n, "(port)mat1_o_2_V_full_n");
    sc_trace(mVcdFile, mat1_o_2_V_write, "(port)mat1_o_2_V_write");
    sc_trace(mVcdFile, mat1_o_3_V_din, "(port)mat1_o_3_V_din");
    sc_trace(mVcdFile, mat1_o_3_V_full_n, "(port)mat1_o_3_V_full_n");
    sc_trace(mVcdFile, mat1_o_3_V_write, "(port)mat1_o_3_V_write");
    sc_trace(mVcdFile, mat1_o_4_V_din, "(port)mat1_o_4_V_din");
    sc_trace(mVcdFile, mat1_o_4_V_full_n, "(port)mat1_o_4_V_full_n");
    sc_trace(mVcdFile, mat1_o_4_V_write, "(port)mat1_o_4_V_write");
    sc_trace(mVcdFile, mat1_o_5_V_din, "(port)mat1_o_5_V_din");
    sc_trace(mVcdFile, mat1_o_5_V_full_n, "(port)mat1_o_5_V_full_n");
    sc_trace(mVcdFile, mat1_o_5_V_write, "(port)mat1_o_5_V_write");
    sc_trace(mVcdFile, mat1_o_6_V_din, "(port)mat1_o_6_V_din");
    sc_trace(mVcdFile, mat1_o_6_V_full_n, "(port)mat1_o_6_V_full_n");
    sc_trace(mVcdFile, mat1_o_6_V_write, "(port)mat1_o_6_V_write");
    sc_trace(mVcdFile, mat1_o_7_V_din, "(port)mat1_o_7_V_din");
    sc_trace(mVcdFile, mat1_o_7_V_full_n, "(port)mat1_o_7_V_full_n");
    sc_trace(mVcdFile, mat1_o_7_V_write, "(port)mat1_o_7_V_write");
    sc_trace(mVcdFile, mat1_o_8_V_din, "(port)mat1_o_8_V_din");
    sc_trace(mVcdFile, mat1_o_8_V_full_n, "(port)mat1_o_8_V_full_n");
    sc_trace(mVcdFile, mat1_o_8_V_write, "(port)mat1_o_8_V_write");
    sc_trace(mVcdFile, mat1_o_9_V_din, "(port)mat1_o_9_V_din");
    sc_trace(mVcdFile, mat1_o_9_V_full_n, "(port)mat1_o_9_V_full_n");
    sc_trace(mVcdFile, mat1_o_9_V_write, "(port)mat1_o_9_V_write");
    sc_trace(mVcdFile, mat1_o_10_V_din, "(port)mat1_o_10_V_din");
    sc_trace(mVcdFile, mat1_o_10_V_full_n, "(port)mat1_o_10_V_full_n");
    sc_trace(mVcdFile, mat1_o_10_V_write, "(port)mat1_o_10_V_write");
    sc_trace(mVcdFile, mat1_o_11_V_din, "(port)mat1_o_11_V_din");
    sc_trace(mVcdFile, mat1_o_11_V_full_n, "(port)mat1_o_11_V_full_n");
    sc_trace(mVcdFile, mat1_o_11_V_write, "(port)mat1_o_11_V_write");
    sc_trace(mVcdFile, mat1_o_12_V_din, "(port)mat1_o_12_V_din");
    sc_trace(mVcdFile, mat1_o_12_V_full_n, "(port)mat1_o_12_V_full_n");
    sc_trace(mVcdFile, mat1_o_12_V_write, "(port)mat1_o_12_V_write");
    sc_trace(mVcdFile, mat1_o_13_V_din, "(port)mat1_o_13_V_din");
    sc_trace(mVcdFile, mat1_o_13_V_full_n, "(port)mat1_o_13_V_full_n");
    sc_trace(mVcdFile, mat1_o_13_V_write, "(port)mat1_o_13_V_write");
    sc_trace(mVcdFile, mat1_o_14_V_din, "(port)mat1_o_14_V_din");
    sc_trace(mVcdFile, mat1_o_14_V_full_n, "(port)mat1_o_14_V_full_n");
    sc_trace(mVcdFile, mat1_o_14_V_write, "(port)mat1_o_14_V_write");
    sc_trace(mVcdFile, mat1_o_15_V_din, "(port)mat1_o_15_V_din");
    sc_trace(mVcdFile, mat1_o_15_V_full_n, "(port)mat1_o_15_V_full_n");
    sc_trace(mVcdFile, mat1_o_15_V_write, "(port)mat1_o_15_V_write");
    sc_trace(mVcdFile, mat2_o_0_V_din, "(port)mat2_o_0_V_din");
    sc_trace(mVcdFile, mat2_o_0_V_full_n, "(port)mat2_o_0_V_full_n");
    sc_trace(mVcdFile, mat2_o_0_V_write, "(port)mat2_o_0_V_write");
    sc_trace(mVcdFile, mat2_o_1_V_din, "(port)mat2_o_1_V_din");
    sc_trace(mVcdFile, mat2_o_1_V_full_n, "(port)mat2_o_1_V_full_n");
    sc_trace(mVcdFile, mat2_o_1_V_write, "(port)mat2_o_1_V_write");
    sc_trace(mVcdFile, mat2_o_2_V_din, "(port)mat2_o_2_V_din");
    sc_trace(mVcdFile, mat2_o_2_V_full_n, "(port)mat2_o_2_V_full_n");
    sc_trace(mVcdFile, mat2_o_2_V_write, "(port)mat2_o_2_V_write");
    sc_trace(mVcdFile, mat2_o_3_V_din, "(port)mat2_o_3_V_din");
    sc_trace(mVcdFile, mat2_o_3_V_full_n, "(port)mat2_o_3_V_full_n");
    sc_trace(mVcdFile, mat2_o_3_V_write, "(port)mat2_o_3_V_write");
    sc_trace(mVcdFile, mat2_o_4_V_din, "(port)mat2_o_4_V_din");
    sc_trace(mVcdFile, mat2_o_4_V_full_n, "(port)mat2_o_4_V_full_n");
    sc_trace(mVcdFile, mat2_o_4_V_write, "(port)mat2_o_4_V_write");
    sc_trace(mVcdFile, mat2_o_5_V_din, "(port)mat2_o_5_V_din");
    sc_trace(mVcdFile, mat2_o_5_V_full_n, "(port)mat2_o_5_V_full_n");
    sc_trace(mVcdFile, mat2_o_5_V_write, "(port)mat2_o_5_V_write");
    sc_trace(mVcdFile, mat2_o_6_V_din, "(port)mat2_o_6_V_din");
    sc_trace(mVcdFile, mat2_o_6_V_full_n, "(port)mat2_o_6_V_full_n");
    sc_trace(mVcdFile, mat2_o_6_V_write, "(port)mat2_o_6_V_write");
    sc_trace(mVcdFile, mat2_o_7_V_din, "(port)mat2_o_7_V_din");
    sc_trace(mVcdFile, mat2_o_7_V_full_n, "(port)mat2_o_7_V_full_n");
    sc_trace(mVcdFile, mat2_o_7_V_write, "(port)mat2_o_7_V_write");
    sc_trace(mVcdFile, mat2_o_8_V_din, "(port)mat2_o_8_V_din");
    sc_trace(mVcdFile, mat2_o_8_V_full_n, "(port)mat2_o_8_V_full_n");
    sc_trace(mVcdFile, mat2_o_8_V_write, "(port)mat2_o_8_V_write");
    sc_trace(mVcdFile, mat2_o_9_V_din, "(port)mat2_o_9_V_din");
    sc_trace(mVcdFile, mat2_o_9_V_full_n, "(port)mat2_o_9_V_full_n");
    sc_trace(mVcdFile, mat2_o_9_V_write, "(port)mat2_o_9_V_write");
    sc_trace(mVcdFile, mat2_o_10_V_din, "(port)mat2_o_10_V_din");
    sc_trace(mVcdFile, mat2_o_10_V_full_n, "(port)mat2_o_10_V_full_n");
    sc_trace(mVcdFile, mat2_o_10_V_write, "(port)mat2_o_10_V_write");
    sc_trace(mVcdFile, mat2_o_11_V_din, "(port)mat2_o_11_V_din");
    sc_trace(mVcdFile, mat2_o_11_V_full_n, "(port)mat2_o_11_V_full_n");
    sc_trace(mVcdFile, mat2_o_11_V_write, "(port)mat2_o_11_V_write");
    sc_trace(mVcdFile, mat2_o_12_V_din, "(port)mat2_o_12_V_din");
    sc_trace(mVcdFile, mat2_o_12_V_full_n, "(port)mat2_o_12_V_full_n");
    sc_trace(mVcdFile, mat2_o_12_V_write, "(port)mat2_o_12_V_write");
    sc_trace(mVcdFile, mat2_o_13_V_din, "(port)mat2_o_13_V_din");
    sc_trace(mVcdFile, mat2_o_13_V_full_n, "(port)mat2_o_13_V_full_n");
    sc_trace(mVcdFile, mat2_o_13_V_write, "(port)mat2_o_13_V_write");
    sc_trace(mVcdFile, mat2_o_14_V_din, "(port)mat2_o_14_V_din");
    sc_trace(mVcdFile, mat2_o_14_V_full_n, "(port)mat2_o_14_V_full_n");
    sc_trace(mVcdFile, mat2_o_14_V_write, "(port)mat2_o_14_V_write");
    sc_trace(mVcdFile, mat2_o_15_V_din, "(port)mat2_o_15_V_din");
    sc_trace(mVcdFile, mat2_o_15_V_full_n, "(port)mat2_o_15_V_full_n");
    sc_trace(mVcdFile, mat2_o_15_V_write, "(port)mat2_o_15_V_write");
#endif
#ifdef __HLS_TRACE_LEVEL_INT__
    sc_trace(mVcdFile, ap_done_reg, "ap_done_reg");
    sc_trace(mVcdFile, ap_CS_fsm, "ap_CS_fsm");
    sc_trace(mVcdFile, ap_sig_cseq_ST_st1_fsm_0, "ap_sig_cseq_ST_st1_fsm_0");
    sc_trace(mVcdFile, ap_sig_bdd_22, "ap_sig_bdd_22");
    sc_trace(mVcdFile, indvar_flatten_reg_868, "indvar_flatten_reg_868");
    sc_trace(mVcdFile, exitcond_flatten_fu_879_p2, "exitcond_flatten_fu_879_p2");
    sc_trace(mVcdFile, exitcond_flatten_reg_891, "exitcond_flatten_reg_891");
    sc_trace(mVcdFile, ap_sig_cseq_ST_pp0_stg0_fsm_1, "ap_sig_cseq_ST_pp0_stg0_fsm_1");
    sc_trace(mVcdFile, ap_sig_bdd_230, "ap_sig_bdd_230");
    sc_trace(mVcdFile, ap_reg_ppiten_pp0_it0, "ap_reg_ppiten_pp0_it0");
    sc_trace(mVcdFile, ap_sig_bdd_379, "ap_sig_bdd_379");
    sc_trace(mVcdFile, ap_reg_ppiten_pp0_it1, "ap_reg_ppiten_pp0_it1");
    sc_trace(mVcdFile, indvar_flatten_next_fu_885_p2, "indvar_flatten_next_fu_885_p2");
    sc_trace(mVcdFile, ap_sig_bdd_392, "ap_sig_bdd_392");
    sc_trace(mVcdFile, ap_sig_cseq_ST_st4_fsm_2, "ap_sig_cseq_ST_st4_fsm_2");
    sc_trace(mVcdFile, ap_sig_bdd_483, "ap_sig_bdd_483");
    sc_trace(mVcdFile, ap_NS_fsm, "ap_NS_fsm");
#endif

    }
}

fire2_copy::~fire2_copy() {
    if (mVcdFile) 
        sc_close_vcd_trace_file(mVcdFile);

}

void fire2_copy::thread_ap_clk_no_reset_() {
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_CS_fsm = ap_ST_st1_fsm_0;
    } else {
        ap_CS_fsm = ap_NS_fsm.read();
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_done_reg = ap_const_logic_0;
    } else {
        if (esl_seteq<1,1,1>(ap_const_logic_1, ap_continue.read())) {
            ap_done_reg = ap_const_logic_0;
        } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st4_fsm_2.read())) {
            ap_done_reg = ap_const_logic_1;
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_reg_ppiten_pp0_it0 = ap_const_logic_0;
    } else {
        if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_pp0_stg0_fsm_1.read()) && 
             !(ap_sig_bdd_379.read() && esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it1.read())) && 
             !esl_seteq<1,1,1>(exitcond_flatten_fu_879_p2.read(), ap_const_lv1_0))) {
            ap_reg_ppiten_pp0_it0 = ap_const_logic_0;
        } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st1_fsm_0.read()) && 
                    !ap_sig_bdd_392.read())) {
            ap_reg_ppiten_pp0_it0 = ap_const_logic_1;
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_reg_ppiten_pp0_it1 = ap_const_logic_0;
    } else {
        if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_pp0_stg0_fsm_1.read()) && 
             !(ap_sig_bdd_379.read() && esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it1.read())) && 
             esl_seteq<1,1,1>(exitcond_flatten_fu_879_p2.read(), ap_const_lv1_0))) {
            ap_reg_ppiten_pp0_it1 = ap_const_logic_1;
        } else if (((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st1_fsm_0.read()) && 
                     !ap_sig_bdd_392.read()) || 
                    (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_pp0_stg0_fsm_1.read()) && 
                     !(ap_sig_bdd_379.read() && esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it1.read())) && 
                     !esl_seteq<1,1,1>(exitcond_flatten_fu_879_p2.read(), ap_const_lv1_0)))) {
            ap_reg_ppiten_pp0_it1 = ap_const_logic_0;
        }
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_pp0_stg0_fsm_1.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it0.read()) && 
         !(ap_sig_bdd_379.read() && esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it1.read())) && 
         esl_seteq<1,1,1>(exitcond_flatten_fu_879_p2.read(), ap_const_lv1_0))) {
        indvar_flatten_reg_868 = indvar_flatten_next_fu_885_p2.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st1_fsm_0.read()) && 
                !ap_sig_bdd_392.read())) {
        indvar_flatten_reg_868 = ap_const_lv12_0;
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_pp0_stg0_fsm_1.read()) && !(ap_sig_bdd_379.read() && esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it1.read())))) {
        exitcond_flatten_reg_891 = exitcond_flatten_fu_879_p2.read();
    }
}

void fire2_copy::thread_ap_done() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_done_reg.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st4_fsm_2.read()))) {
        ap_done = ap_const_logic_1;
    } else {
        ap_done = ap_const_logic_0;
    }
}

void fire2_copy::thread_ap_idle() {
    if ((!esl_seteq<1,1,1>(ap_const_logic_1, ap_start.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st1_fsm_0.read()))) {
        ap_idle = ap_const_logic_1;
    } else {
        ap_idle = ap_const_logic_0;
    }
}

void fire2_copy::thread_ap_ready() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st4_fsm_2.read())) {
        ap_ready = ap_const_logic_1;
    } else {
        ap_ready = ap_const_logic_0;
    }
}

void fire2_copy::thread_ap_sig_bdd_22() {
    ap_sig_bdd_22 = esl_seteq<1,1,1>(ap_CS_fsm.read().range(0, 0), ap_const_lv1_1);
}

void fire2_copy::thread_ap_sig_bdd_230() {
    ap_sig_bdd_230 = esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm.read().range(1, 1));
}

void fire2_copy::thread_ap_sig_bdd_379() {
    ap_sig_bdd_379 = ((esl_seteq<1,1,1>(mat_i_0_V_empty_n.read(), ap_const_logic_0) && 
  esl_seteq<1,1,1>(exitcond_flatten_reg_891.read(), ap_const_lv1_0)) || (esl_seteq<1,1,1>(exitcond_flatten_reg_891.read(), ap_const_lv1_0) && 
  esl_seteq<1,1,1>(mat1_o_0_V_full_n.read(), ap_const_logic_0)) || (esl_seteq<1,1,1>(exitcond_flatten_reg_891.read(), ap_const_lv1_0) && 
  esl_seteq<1,1,1>(mat2_o_0_V_full_n.read(), ap_const_logic_0)) || (esl_seteq<1,1,1>(exitcond_flatten_reg_891.read(), ap_const_lv1_0) && 
  esl_seteq<1,1,1>(mat_i_1_V_empty_n.read(), ap_const_logic_0)) || (esl_seteq<1,1,1>(exitcond_flatten_reg_891.read(), ap_const_lv1_0) && 
  esl_seteq<1,1,1>(mat1_o_1_V_full_n.read(), ap_const_logic_0)) || (esl_seteq<1,1,1>(exitcond_flatten_reg_891.read(), ap_const_lv1_0) && 
  esl_seteq<1,1,1>(mat2_o_1_V_full_n.read(), ap_const_logic_0)) || (esl_seteq<1,1,1>(exitcond_flatten_reg_891.read(), ap_const_lv1_0) && 
  esl_seteq<1,1,1>(mat_i_2_V_empty_n.read(), ap_const_logic_0)) || (esl_seteq<1,1,1>(exitcond_flatten_reg_891.read(), ap_const_lv1_0) && 
  esl_seteq<1,1,1>(mat1_o_2_V_full_n.read(), ap_const_logic_0)) || (esl_seteq<1,1,1>(exitcond_flatten_reg_891.read(), ap_const_lv1_0) && 
  esl_seteq<1,1,1>(mat2_o_2_V_full_n.read(), ap_const_logic_0)) || (esl_seteq<1,1,1>(exitcond_flatten_reg_891.read(), ap_const_lv1_0) && 
  esl_seteq<1,1,1>(mat_i_3_V_empty_n.read(), ap_const_logic_0)) || (esl_seteq<1,1,1>(exitcond_flatten_reg_891.read(), ap_const_lv1_0) && 
  esl_seteq<1,1,1>(mat1_o_3_V_full_n.read(), ap_const_logic_0)) || (esl_seteq<1,1,1>(exitcond_flatten_reg_891.read(), ap_const_lv1_0) && 
  esl_seteq<1,1,1>(mat2_o_3_V_full_n.read(), ap_const_logic_0)) || (esl_seteq<1,1,1>(exitcond_flatten_reg_891.read(), ap_const_lv1_0) && 
  esl_seteq<1,1,1>(mat_i_4_V_empty_n.read(), ap_const_logic_0)) || (esl_seteq<1,1,1>(exitcond_flatten_reg_891.read(), ap_const_lv1_0) && 
  esl_seteq<1,1,1>(mat1_o_4_V_full_n.read(), ap_const_logic_0)) || (esl_seteq<1,1,1>(exitcond_flatten_reg_891.read(), ap_const_lv1_0) && 
  esl_seteq<1,1,1>(mat2_o_4_V_full_n.read(), ap_const_logic_0)) || (esl_seteq<1,1,1>(exitcond_flatten_reg_891.read(), ap_const_lv1_0) && 
  esl_seteq<1,1,1>(mat_i_5_V_empty_n.read(), ap_const_logic_0)) || (esl_seteq<1,1,1>(exitcond_flatten_reg_891.read(), ap_const_lv1_0) && 
  esl_seteq<1,1,1>(mat1_o_5_V_full_n.read(), ap_const_logic_0)) || (esl_seteq<1,1,1>(exitcond_flatten_reg_891.read(), ap_const_lv1_0) && 
  esl_seteq<1,1,1>(mat2_o_5_V_full_n.read(), ap_const_logic_0)) || (esl_seteq<1,1,1>(exitcond_flatten_reg_891.read(), ap_const_lv1_0) && 
  esl_seteq<1,1,1>(mat_i_6_V_empty_n.read(), ap_const_logic_0)) || (esl_seteq<1,1,1>(exitcond_flatten_reg_891.read(), ap_const_lv1_0) && 
  esl_seteq<1,1,1>(mat1_o_6_V_full_n.read(), ap_const_logic_0)) || (esl_seteq<1,1,1>(exitcond_flatten_reg_891.read(), ap_const_lv1_0) && 
  esl_seteq<1,1,1>(mat2_o_6_V_full_n.read(), ap_const_logic_0)) || (esl_seteq<1,1,1>(exitcond_flatten_reg_891.read(), ap_const_lv1_0) && 
  esl_seteq<1,1,1>(mat_i_7_V_empty_n.read(), ap_const_logic_0)) || (esl_seteq<1,1,1>(exitcond_flatten_reg_891.read(), ap_const_lv1_0) && 
  esl_seteq<1,1,1>(mat1_o_7_V_full_n.read(), ap_const_logic_0)) || (esl_seteq<1,1,1>(exitcond_flatten_reg_891.read(), ap_const_lv1_0) && 
  esl_seteq<1,1,1>(mat2_o_7_V_full_n.read(), ap_const_logic_0)) || (esl_seteq<1,1,1>(exitcond_flatten_reg_891.read(), ap_const_lv1_0) && 
  esl_seteq<1,1,1>(mat_i_8_V_empty_n.read(), ap_const_logic_0)) || (esl_seteq<1,1,1>(exitcond_flatten_reg_891.read(), ap_const_lv1_0) && 
  esl_seteq<1,1,1>(mat1_o_8_V_full_n.read(), ap_const_logic_0)) || (esl_seteq<1,1,1>(exitcond_flatten_reg_891.read(), ap_const_lv1_0) && 
  esl_seteq<1,1,1>(mat2_o_8_V_full_n.read(), ap_const_logic_0)) || (esl_seteq<1,1,1>(exitcond_flatten_reg_891.read(), ap_const_lv1_0) && 
  esl_seteq<1,1,1>(mat_i_9_V_empty_n.read(), ap_const_logic_0)) || (esl_seteq<1,1,1>(exitcond_flatten_reg_891.read(), ap_const_lv1_0) && 
  esl_seteq<1,1,1>(mat1_o_9_V_full_n.read(), ap_const_logic_0)) || (esl_seteq<1,1,1>(exitcond_flatten_reg_891.read(), ap_const_lv1_0) && 
  esl_seteq<1,1,1>(mat2_o_9_V_full_n.read(), ap_const_logic_0)) || (esl_seteq<1,1,1>(exitcond_flatten_reg_891.read(), ap_const_lv1_0) && 
  esl_seteq<1,1,1>(mat_i_10_V_empty_n.read(), ap_const_logic_0)) || (esl_seteq<1,1,1>(exitcond_flatten_reg_891.read(), ap_const_lv1_0) && 
  esl_seteq<1,1,1>(mat1_o_10_V_full_n.read(), ap_const_logic_0)) || (esl_seteq<1,1,1>(exitcond_flatten_reg_891.read(), ap_const_lv1_0) && 
  esl_seteq<1,1,1>(mat2_o_10_V_full_n.read(), ap_const_logic_0)) || (esl_seteq<1,1,1>(exitcond_flatten_reg_891.read(), ap_const_lv1_0) && 
  esl_seteq<1,1,1>(mat_i_11_V_empty_n.read(), ap_const_logic_0)) || (esl_seteq<1,1,1>(exitcond_flatten_reg_891.read(), ap_const_lv1_0) && 
  esl_seteq<1,1,1>(mat1_o_11_V_full_n.read(), ap_const_logic_0)) || (esl_seteq<1,1,1>(exitcond_flatten_reg_891.read(), ap_const_lv1_0) && 
  esl_seteq<1,1,1>(mat2_o_11_V_full_n.read(), ap_const_logic_0)) || (esl_seteq<1,1,1>(exitcond_flatten_reg_891.read(), ap_const_lv1_0) && 
  esl_seteq<1,1,1>(mat_i_12_V_empty_n.read(), ap_const_logic_0)) || (esl_seteq<1,1,1>(exitcond_flatten_reg_891.read(), ap_const_lv1_0) && 
  esl_seteq<1,1,1>(mat1_o_12_V_full_n.read(), ap_const_logic_0)) || (esl_seteq<1,1,1>(exitcond_flatten_reg_891.read(), ap_const_lv1_0) && 
  esl_seteq<1,1,1>(mat2_o_12_V_full_n.read(), ap_const_logic_0)) || (esl_seteq<1,1,1>(exitcond_flatten_reg_891.read(), ap_const_lv1_0) && 
  esl_seteq<1,1,1>(mat_i_13_V_empty_n.read(), ap_const_logic_0)) || (esl_seteq<1,1,1>(exitcond_flatten_reg_891.read(), ap_const_lv1_0) && 
  esl_seteq<1,1,1>(mat1_o_13_V_full_n.read(), ap_const_logic_0)) || (esl_seteq<1,1,1>(exitcond_flatten_reg_891.read(), ap_const_lv1_0) && 
  esl_seteq<1,1,1>(mat2_o_13_V_full_n.read(), ap_const_logic_0)) || (esl_seteq<1,1,1>(exitcond_flatten_reg_891.read(), ap_const_lv1_0) && 
  esl_seteq<1,1,1>(mat_i_14_V_empty_n.read(), ap_const_logic_0)) || (esl_seteq<1,1,1>(exitcond_flatten_reg_891.read(), ap_const_lv1_0) && 
  esl_seteq<1,1,1>(mat1_o_14_V_full_n.read(), ap_const_logic_0)) || (esl_seteq<1,1,1>(exitcond_flatten_reg_891.read(), ap_const_lv1_0) && 
  esl_seteq<1,1,1>(mat2_o_14_V_full_n.read(), ap_const_logic_0)) || (esl_seteq<1,1,1>(exitcond_flatten_reg_891.read(), ap_const_lv1_0) && 
  esl_seteq<1,1,1>(mat_i_15_V_empty_n.read(), ap_const_logic_0)) || (esl_seteq<1,1,1>(exitcond_flatten_reg_891.read(), ap_const_lv1_0) && 
  esl_seteq<1,1,1>(mat1_o_15_V_full_n.read(), ap_const_logic_0)) || (esl_seteq<1,1,1>(exitcond_flatten_reg_891.read(), ap_const_lv1_0) && 
  esl_seteq<1,1,1>(mat2_o_15_V_full_n.read(), ap_const_logic_0)));
}

void fire2_copy::thread_ap_sig_bdd_392() {
    ap_sig_bdd_392 = (esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_0) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1));
}

void fire2_copy::thread_ap_sig_bdd_483() {
    ap_sig_bdd_483 = esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm.read().range(2, 2));
}

void fire2_copy::thread_ap_sig_cseq_ST_pp0_stg0_fsm_1() {
    if (ap_sig_bdd_230.read()) {
        ap_sig_cseq_ST_pp0_stg0_fsm_1 = ap_const_logic_1;
    } else {
        ap_sig_cseq_ST_pp0_stg0_fsm_1 = ap_const_logic_0;
    }
}

void fire2_copy::thread_ap_sig_cseq_ST_st1_fsm_0() {
    if (ap_sig_bdd_22.read()) {
        ap_sig_cseq_ST_st1_fsm_0 = ap_const_logic_1;
    } else {
        ap_sig_cseq_ST_st1_fsm_0 = ap_const_logic_0;
    }
}

void fire2_copy::thread_ap_sig_cseq_ST_st4_fsm_2() {
    if (ap_sig_bdd_483.read()) {
        ap_sig_cseq_ST_st4_fsm_2 = ap_const_logic_1;
    } else {
        ap_sig_cseq_ST_st4_fsm_2 = ap_const_logic_0;
    }
}

void fire2_copy::thread_exitcond_flatten_fu_879_p2() {
    exitcond_flatten_fu_879_p2 = (!indvar_flatten_reg_868.read().is_01() || !ap_const_lv12_BD1.is_01())? sc_lv<1>(): sc_lv<1>(indvar_flatten_reg_868.read() == ap_const_lv12_BD1);
}

void fire2_copy::thread_indvar_flatten_next_fu_885_p2() {
    indvar_flatten_next_fu_885_p2 = (!indvar_flatten_reg_868.read().is_01() || !ap_const_lv12_1.is_01())? sc_lv<12>(): (sc_biguint<12>(indvar_flatten_reg_868.read()) + sc_biguint<12>(ap_const_lv12_1));
}

void fire2_copy::thread_mat1_o_0_V_din() {
    mat1_o_0_V_din = mat_i_0_V_dout.read();
}

void fire2_copy::thread_mat1_o_0_V_write() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_pp0_stg0_fsm_1.read()) && 
         esl_seteq<1,1,1>(exitcond_flatten_reg_891.read(), ap_const_lv1_0) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it1.read()) && 
         !(ap_sig_bdd_379.read() && esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it1.read())))) {
        mat1_o_0_V_write = ap_const_logic_1;
    } else {
        mat1_o_0_V_write = ap_const_logic_0;
    }
}

void fire2_copy::thread_mat1_o_10_V_din() {
    mat1_o_10_V_din = mat_i_10_V_dout.read();
}

void fire2_copy::thread_mat1_o_10_V_write() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_pp0_stg0_fsm_1.read()) && 
         esl_seteq<1,1,1>(exitcond_flatten_reg_891.read(), ap_const_lv1_0) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it1.read()) && 
         !(ap_sig_bdd_379.read() && esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it1.read())))) {
        mat1_o_10_V_write = ap_const_logic_1;
    } else {
        mat1_o_10_V_write = ap_const_logic_0;
    }
}

void fire2_copy::thread_mat1_o_11_V_din() {
    mat1_o_11_V_din = mat_i_11_V_dout.read();
}

void fire2_copy::thread_mat1_o_11_V_write() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_pp0_stg0_fsm_1.read()) && 
         esl_seteq<1,1,1>(exitcond_flatten_reg_891.read(), ap_const_lv1_0) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it1.read()) && 
         !(ap_sig_bdd_379.read() && esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it1.read())))) {
        mat1_o_11_V_write = ap_const_logic_1;
    } else {
        mat1_o_11_V_write = ap_const_logic_0;
    }
}

void fire2_copy::thread_mat1_o_12_V_din() {
    mat1_o_12_V_din = mat_i_12_V_dout.read();
}

void fire2_copy::thread_mat1_o_12_V_write() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_pp0_stg0_fsm_1.read()) && 
         esl_seteq<1,1,1>(exitcond_flatten_reg_891.read(), ap_const_lv1_0) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it1.read()) && 
         !(ap_sig_bdd_379.read() && esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it1.read())))) {
        mat1_o_12_V_write = ap_const_logic_1;
    } else {
        mat1_o_12_V_write = ap_const_logic_0;
    }
}

void fire2_copy::thread_mat1_o_13_V_din() {
    mat1_o_13_V_din = mat_i_13_V_dout.read();
}

void fire2_copy::thread_mat1_o_13_V_write() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_pp0_stg0_fsm_1.read()) && 
         esl_seteq<1,1,1>(exitcond_flatten_reg_891.read(), ap_const_lv1_0) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it1.read()) && 
         !(ap_sig_bdd_379.read() && esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it1.read())))) {
        mat1_o_13_V_write = ap_const_logic_1;
    } else {
        mat1_o_13_V_write = ap_const_logic_0;
    }
}

void fire2_copy::thread_mat1_o_14_V_din() {
    mat1_o_14_V_din = mat_i_14_V_dout.read();
}

void fire2_copy::thread_mat1_o_14_V_write() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_pp0_stg0_fsm_1.read()) && 
         esl_seteq<1,1,1>(exitcond_flatten_reg_891.read(), ap_const_lv1_0) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it1.read()) && 
         !(ap_sig_bdd_379.read() && esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it1.read())))) {
        mat1_o_14_V_write = ap_const_logic_1;
    } else {
        mat1_o_14_V_write = ap_const_logic_0;
    }
}

void fire2_copy::thread_mat1_o_15_V_din() {
    mat1_o_15_V_din = mat_i_15_V_dout.read();
}

void fire2_copy::thread_mat1_o_15_V_write() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_pp0_stg0_fsm_1.read()) && 
         esl_seteq<1,1,1>(exitcond_flatten_reg_891.read(), ap_const_lv1_0) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it1.read()) && 
         !(ap_sig_bdd_379.read() && esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it1.read())))) {
        mat1_o_15_V_write = ap_const_logic_1;
    } else {
        mat1_o_15_V_write = ap_const_logic_0;
    }
}

void fire2_copy::thread_mat1_o_1_V_din() {
    mat1_o_1_V_din = mat_i_1_V_dout.read();
}

void fire2_copy::thread_mat1_o_1_V_write() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_pp0_stg0_fsm_1.read()) && 
         esl_seteq<1,1,1>(exitcond_flatten_reg_891.read(), ap_const_lv1_0) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it1.read()) && 
         !(ap_sig_bdd_379.read() && esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it1.read())))) {
        mat1_o_1_V_write = ap_const_logic_1;
    } else {
        mat1_o_1_V_write = ap_const_logic_0;
    }
}

void fire2_copy::thread_mat1_o_2_V_din() {
    mat1_o_2_V_din = mat_i_2_V_dout.read();
}

void fire2_copy::thread_mat1_o_2_V_write() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_pp0_stg0_fsm_1.read()) && 
         esl_seteq<1,1,1>(exitcond_flatten_reg_891.read(), ap_const_lv1_0) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it1.read()) && 
         !(ap_sig_bdd_379.read() && esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it1.read())))) {
        mat1_o_2_V_write = ap_const_logic_1;
    } else {
        mat1_o_2_V_write = ap_const_logic_0;
    }
}

void fire2_copy::thread_mat1_o_3_V_din() {
    mat1_o_3_V_din = mat_i_3_V_dout.read();
}

void fire2_copy::thread_mat1_o_3_V_write() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_pp0_stg0_fsm_1.read()) && 
         esl_seteq<1,1,1>(exitcond_flatten_reg_891.read(), ap_const_lv1_0) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it1.read()) && 
         !(ap_sig_bdd_379.read() && esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it1.read())))) {
        mat1_o_3_V_write = ap_const_logic_1;
    } else {
        mat1_o_3_V_write = ap_const_logic_0;
    }
}

void fire2_copy::thread_mat1_o_4_V_din() {
    mat1_o_4_V_din = mat_i_4_V_dout.read();
}

void fire2_copy::thread_mat1_o_4_V_write() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_pp0_stg0_fsm_1.read()) && 
         esl_seteq<1,1,1>(exitcond_flatten_reg_891.read(), ap_const_lv1_0) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it1.read()) && 
         !(ap_sig_bdd_379.read() && esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it1.read())))) {
        mat1_o_4_V_write = ap_const_logic_1;
    } else {
        mat1_o_4_V_write = ap_const_logic_0;
    }
}

void fire2_copy::thread_mat1_o_5_V_din() {
    mat1_o_5_V_din = mat_i_5_V_dout.read();
}

void fire2_copy::thread_mat1_o_5_V_write() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_pp0_stg0_fsm_1.read()) && 
         esl_seteq<1,1,1>(exitcond_flatten_reg_891.read(), ap_const_lv1_0) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it1.read()) && 
         !(ap_sig_bdd_379.read() && esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it1.read())))) {
        mat1_o_5_V_write = ap_const_logic_1;
    } else {
        mat1_o_5_V_write = ap_const_logic_0;
    }
}

void fire2_copy::thread_mat1_o_6_V_din() {
    mat1_o_6_V_din = mat_i_6_V_dout.read();
}

void fire2_copy::thread_mat1_o_6_V_write() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_pp0_stg0_fsm_1.read()) && 
         esl_seteq<1,1,1>(exitcond_flatten_reg_891.read(), ap_const_lv1_0) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it1.read()) && 
         !(ap_sig_bdd_379.read() && esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it1.read())))) {
        mat1_o_6_V_write = ap_const_logic_1;
    } else {
        mat1_o_6_V_write = ap_const_logic_0;
    }
}

void fire2_copy::thread_mat1_o_7_V_din() {
    mat1_o_7_V_din = mat_i_7_V_dout.read();
}

void fire2_copy::thread_mat1_o_7_V_write() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_pp0_stg0_fsm_1.read()) && 
         esl_seteq<1,1,1>(exitcond_flatten_reg_891.read(), ap_const_lv1_0) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it1.read()) && 
         !(ap_sig_bdd_379.read() && esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it1.read())))) {
        mat1_o_7_V_write = ap_const_logic_1;
    } else {
        mat1_o_7_V_write = ap_const_logic_0;
    }
}

void fire2_copy::thread_mat1_o_8_V_din() {
    mat1_o_8_V_din = mat_i_8_V_dout.read();
}

void fire2_copy::thread_mat1_o_8_V_write() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_pp0_stg0_fsm_1.read()) && 
         esl_seteq<1,1,1>(exitcond_flatten_reg_891.read(), ap_const_lv1_0) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it1.read()) && 
         !(ap_sig_bdd_379.read() && esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it1.read())))) {
        mat1_o_8_V_write = ap_const_logic_1;
    } else {
        mat1_o_8_V_write = ap_const_logic_0;
    }
}

void fire2_copy::thread_mat1_o_9_V_din() {
    mat1_o_9_V_din = mat_i_9_V_dout.read();
}

void fire2_copy::thread_mat1_o_9_V_write() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_pp0_stg0_fsm_1.read()) && 
         esl_seteq<1,1,1>(exitcond_flatten_reg_891.read(), ap_const_lv1_0) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it1.read()) && 
         !(ap_sig_bdd_379.read() && esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it1.read())))) {
        mat1_o_9_V_write = ap_const_logic_1;
    } else {
        mat1_o_9_V_write = ap_const_logic_0;
    }
}

void fire2_copy::thread_mat2_o_0_V_din() {
    mat2_o_0_V_din = mat_i_0_V_dout.read();
}

void fire2_copy::thread_mat2_o_0_V_write() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_pp0_stg0_fsm_1.read()) && 
         esl_seteq<1,1,1>(exitcond_flatten_reg_891.read(), ap_const_lv1_0) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it1.read()) && 
         !(ap_sig_bdd_379.read() && esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it1.read())))) {
        mat2_o_0_V_write = ap_const_logic_1;
    } else {
        mat2_o_0_V_write = ap_const_logic_0;
    }
}

void fire2_copy::thread_mat2_o_10_V_din() {
    mat2_o_10_V_din = mat_i_10_V_dout.read();
}

void fire2_copy::thread_mat2_o_10_V_write() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_pp0_stg0_fsm_1.read()) && 
         esl_seteq<1,1,1>(exitcond_flatten_reg_891.read(), ap_const_lv1_0) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it1.read()) && 
         !(ap_sig_bdd_379.read() && esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it1.read())))) {
        mat2_o_10_V_write = ap_const_logic_1;
    } else {
        mat2_o_10_V_write = ap_const_logic_0;
    }
}

void fire2_copy::thread_mat2_o_11_V_din() {
    mat2_o_11_V_din = mat_i_11_V_dout.read();
}

void fire2_copy::thread_mat2_o_11_V_write() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_pp0_stg0_fsm_1.read()) && 
         esl_seteq<1,1,1>(exitcond_flatten_reg_891.read(), ap_const_lv1_0) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it1.read()) && 
         !(ap_sig_bdd_379.read() && esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it1.read())))) {
        mat2_o_11_V_write = ap_const_logic_1;
    } else {
        mat2_o_11_V_write = ap_const_logic_0;
    }
}

void fire2_copy::thread_mat2_o_12_V_din() {
    mat2_o_12_V_din = mat_i_12_V_dout.read();
}

void fire2_copy::thread_mat2_o_12_V_write() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_pp0_stg0_fsm_1.read()) && 
         esl_seteq<1,1,1>(exitcond_flatten_reg_891.read(), ap_const_lv1_0) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it1.read()) && 
         !(ap_sig_bdd_379.read() && esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it1.read())))) {
        mat2_o_12_V_write = ap_const_logic_1;
    } else {
        mat2_o_12_V_write = ap_const_logic_0;
    }
}

void fire2_copy::thread_mat2_o_13_V_din() {
    mat2_o_13_V_din = mat_i_13_V_dout.read();
}

void fire2_copy::thread_mat2_o_13_V_write() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_pp0_stg0_fsm_1.read()) && 
         esl_seteq<1,1,1>(exitcond_flatten_reg_891.read(), ap_const_lv1_0) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it1.read()) && 
         !(ap_sig_bdd_379.read() && esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it1.read())))) {
        mat2_o_13_V_write = ap_const_logic_1;
    } else {
        mat2_o_13_V_write = ap_const_logic_0;
    }
}

void fire2_copy::thread_mat2_o_14_V_din() {
    mat2_o_14_V_din = mat_i_14_V_dout.read();
}

void fire2_copy::thread_mat2_o_14_V_write() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_pp0_stg0_fsm_1.read()) && 
         esl_seteq<1,1,1>(exitcond_flatten_reg_891.read(), ap_const_lv1_0) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it1.read()) && 
         !(ap_sig_bdd_379.read() && esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it1.read())))) {
        mat2_o_14_V_write = ap_const_logic_1;
    } else {
        mat2_o_14_V_write = ap_const_logic_0;
    }
}

void fire2_copy::thread_mat2_o_15_V_din() {
    mat2_o_15_V_din = mat_i_15_V_dout.read();
}

void fire2_copy::thread_mat2_o_15_V_write() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_pp0_stg0_fsm_1.read()) && 
         esl_seteq<1,1,1>(exitcond_flatten_reg_891.read(), ap_const_lv1_0) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it1.read()) && 
         !(ap_sig_bdd_379.read() && esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it1.read())))) {
        mat2_o_15_V_write = ap_const_logic_1;
    } else {
        mat2_o_15_V_write = ap_const_logic_0;
    }
}

void fire2_copy::thread_mat2_o_1_V_din() {
    mat2_o_1_V_din = mat_i_1_V_dout.read();
}

void fire2_copy::thread_mat2_o_1_V_write() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_pp0_stg0_fsm_1.read()) && 
         esl_seteq<1,1,1>(exitcond_flatten_reg_891.read(), ap_const_lv1_0) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it1.read()) && 
         !(ap_sig_bdd_379.read() && esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it1.read())))) {
        mat2_o_1_V_write = ap_const_logic_1;
    } else {
        mat2_o_1_V_write = ap_const_logic_0;
    }
}

void fire2_copy::thread_mat2_o_2_V_din() {
    mat2_o_2_V_din = mat_i_2_V_dout.read();
}

void fire2_copy::thread_mat2_o_2_V_write() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_pp0_stg0_fsm_1.read()) && 
         esl_seteq<1,1,1>(exitcond_flatten_reg_891.read(), ap_const_lv1_0) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it1.read()) && 
         !(ap_sig_bdd_379.read() && esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it1.read())))) {
        mat2_o_2_V_write = ap_const_logic_1;
    } else {
        mat2_o_2_V_write = ap_const_logic_0;
    }
}

void fire2_copy::thread_mat2_o_3_V_din() {
    mat2_o_3_V_din = mat_i_3_V_dout.read();
}

void fire2_copy::thread_mat2_o_3_V_write() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_pp0_stg0_fsm_1.read()) && 
         esl_seteq<1,1,1>(exitcond_flatten_reg_891.read(), ap_const_lv1_0) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it1.read()) && 
         !(ap_sig_bdd_379.read() && esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it1.read())))) {
        mat2_o_3_V_write = ap_const_logic_1;
    } else {
        mat2_o_3_V_write = ap_const_logic_0;
    }
}

void fire2_copy::thread_mat2_o_4_V_din() {
    mat2_o_4_V_din = mat_i_4_V_dout.read();
}

void fire2_copy::thread_mat2_o_4_V_write() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_pp0_stg0_fsm_1.read()) && 
         esl_seteq<1,1,1>(exitcond_flatten_reg_891.read(), ap_const_lv1_0) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it1.read()) && 
         !(ap_sig_bdd_379.read() && esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it1.read())))) {
        mat2_o_4_V_write = ap_const_logic_1;
    } else {
        mat2_o_4_V_write = ap_const_logic_0;
    }
}

void fire2_copy::thread_mat2_o_5_V_din() {
    mat2_o_5_V_din = mat_i_5_V_dout.read();
}

void fire2_copy::thread_mat2_o_5_V_write() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_pp0_stg0_fsm_1.read()) && 
         esl_seteq<1,1,1>(exitcond_flatten_reg_891.read(), ap_const_lv1_0) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it1.read()) && 
         !(ap_sig_bdd_379.read() && esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it1.read())))) {
        mat2_o_5_V_write = ap_const_logic_1;
    } else {
        mat2_o_5_V_write = ap_const_logic_0;
    }
}

void fire2_copy::thread_mat2_o_6_V_din() {
    mat2_o_6_V_din = mat_i_6_V_dout.read();
}

void fire2_copy::thread_mat2_o_6_V_write() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_pp0_stg0_fsm_1.read()) && 
         esl_seteq<1,1,1>(exitcond_flatten_reg_891.read(), ap_const_lv1_0) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it1.read()) && 
         !(ap_sig_bdd_379.read() && esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it1.read())))) {
        mat2_o_6_V_write = ap_const_logic_1;
    } else {
        mat2_o_6_V_write = ap_const_logic_0;
    }
}

void fire2_copy::thread_mat2_o_7_V_din() {
    mat2_o_7_V_din = mat_i_7_V_dout.read();
}

void fire2_copy::thread_mat2_o_7_V_write() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_pp0_stg0_fsm_1.read()) && 
         esl_seteq<1,1,1>(exitcond_flatten_reg_891.read(), ap_const_lv1_0) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it1.read()) && 
         !(ap_sig_bdd_379.read() && esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it1.read())))) {
        mat2_o_7_V_write = ap_const_logic_1;
    } else {
        mat2_o_7_V_write = ap_const_logic_0;
    }
}

void fire2_copy::thread_mat2_o_8_V_din() {
    mat2_o_8_V_din = mat_i_8_V_dout.read();
}

void fire2_copy::thread_mat2_o_8_V_write() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_pp0_stg0_fsm_1.read()) && 
         esl_seteq<1,1,1>(exitcond_flatten_reg_891.read(), ap_const_lv1_0) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it1.read()) && 
         !(ap_sig_bdd_379.read() && esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it1.read())))) {
        mat2_o_8_V_write = ap_const_logic_1;
    } else {
        mat2_o_8_V_write = ap_const_logic_0;
    }
}

void fire2_copy::thread_mat2_o_9_V_din() {
    mat2_o_9_V_din = mat_i_9_V_dout.read();
}

void fire2_copy::thread_mat2_o_9_V_write() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_pp0_stg0_fsm_1.read()) && 
         esl_seteq<1,1,1>(exitcond_flatten_reg_891.read(), ap_const_lv1_0) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it1.read()) && 
         !(ap_sig_bdd_379.read() && esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it1.read())))) {
        mat2_o_9_V_write = ap_const_logic_1;
    } else {
        mat2_o_9_V_write = ap_const_logic_0;
    }
}

void fire2_copy::thread_mat_i_0_V_read() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_pp0_stg0_fsm_1.read()) && 
         esl_seteq<1,1,1>(exitcond_flatten_reg_891.read(), ap_const_lv1_0) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it1.read()) && 
         !(ap_sig_bdd_379.read() && esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it1.read())))) {
        mat_i_0_V_read = ap_const_logic_1;
    } else {
        mat_i_0_V_read = ap_const_logic_0;
    }
}

void fire2_copy::thread_mat_i_10_V_read() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_pp0_stg0_fsm_1.read()) && 
         esl_seteq<1,1,1>(exitcond_flatten_reg_891.read(), ap_const_lv1_0) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it1.read()) && 
         !(ap_sig_bdd_379.read() && esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it1.read())))) {
        mat_i_10_V_read = ap_const_logic_1;
    } else {
        mat_i_10_V_read = ap_const_logic_0;
    }
}

void fire2_copy::thread_mat_i_11_V_read() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_pp0_stg0_fsm_1.read()) && 
         esl_seteq<1,1,1>(exitcond_flatten_reg_891.read(), ap_const_lv1_0) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it1.read()) && 
         !(ap_sig_bdd_379.read() && esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it1.read())))) {
        mat_i_11_V_read = ap_const_logic_1;
    } else {
        mat_i_11_V_read = ap_const_logic_0;
    }
}

void fire2_copy::thread_mat_i_12_V_read() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_pp0_stg0_fsm_1.read()) && 
         esl_seteq<1,1,1>(exitcond_flatten_reg_891.read(), ap_const_lv1_0) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it1.read()) && 
         !(ap_sig_bdd_379.read() && esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it1.read())))) {
        mat_i_12_V_read = ap_const_logic_1;
    } else {
        mat_i_12_V_read = ap_const_logic_0;
    }
}

void fire2_copy::thread_mat_i_13_V_read() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_pp0_stg0_fsm_1.read()) && 
         esl_seteq<1,1,1>(exitcond_flatten_reg_891.read(), ap_const_lv1_0) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it1.read()) && 
         !(ap_sig_bdd_379.read() && esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it1.read())))) {
        mat_i_13_V_read = ap_const_logic_1;
    } else {
        mat_i_13_V_read = ap_const_logic_0;
    }
}

void fire2_copy::thread_mat_i_14_V_read() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_pp0_stg0_fsm_1.read()) && 
         esl_seteq<1,1,1>(exitcond_flatten_reg_891.read(), ap_const_lv1_0) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it1.read()) && 
         !(ap_sig_bdd_379.read() && esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it1.read())))) {
        mat_i_14_V_read = ap_const_logic_1;
    } else {
        mat_i_14_V_read = ap_const_logic_0;
    }
}

void fire2_copy::thread_mat_i_15_V_read() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_pp0_stg0_fsm_1.read()) && 
         esl_seteq<1,1,1>(exitcond_flatten_reg_891.read(), ap_const_lv1_0) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it1.read()) && 
         !(ap_sig_bdd_379.read() && esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it1.read())))) {
        mat_i_15_V_read = ap_const_logic_1;
    } else {
        mat_i_15_V_read = ap_const_logic_0;
    }
}

void fire2_copy::thread_mat_i_1_V_read() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_pp0_stg0_fsm_1.read()) && 
         esl_seteq<1,1,1>(exitcond_flatten_reg_891.read(), ap_const_lv1_0) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it1.read()) && 
         !(ap_sig_bdd_379.read() && esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it1.read())))) {
        mat_i_1_V_read = ap_const_logic_1;
    } else {
        mat_i_1_V_read = ap_const_logic_0;
    }
}

void fire2_copy::thread_mat_i_2_V_read() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_pp0_stg0_fsm_1.read()) && 
         esl_seteq<1,1,1>(exitcond_flatten_reg_891.read(), ap_const_lv1_0) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it1.read()) && 
         !(ap_sig_bdd_379.read() && esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it1.read())))) {
        mat_i_2_V_read = ap_const_logic_1;
    } else {
        mat_i_2_V_read = ap_const_logic_0;
    }
}

void fire2_copy::thread_mat_i_3_V_read() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_pp0_stg0_fsm_1.read()) && 
         esl_seteq<1,1,1>(exitcond_flatten_reg_891.read(), ap_const_lv1_0) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it1.read()) && 
         !(ap_sig_bdd_379.read() && esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it1.read())))) {
        mat_i_3_V_read = ap_const_logic_1;
    } else {
        mat_i_3_V_read = ap_const_logic_0;
    }
}

void fire2_copy::thread_mat_i_4_V_read() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_pp0_stg0_fsm_1.read()) && 
         esl_seteq<1,1,1>(exitcond_flatten_reg_891.read(), ap_const_lv1_0) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it1.read()) && 
         !(ap_sig_bdd_379.read() && esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it1.read())))) {
        mat_i_4_V_read = ap_const_logic_1;
    } else {
        mat_i_4_V_read = ap_const_logic_0;
    }
}

void fire2_copy::thread_mat_i_5_V_read() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_pp0_stg0_fsm_1.read()) && 
         esl_seteq<1,1,1>(exitcond_flatten_reg_891.read(), ap_const_lv1_0) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it1.read()) && 
         !(ap_sig_bdd_379.read() && esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it1.read())))) {
        mat_i_5_V_read = ap_const_logic_1;
    } else {
        mat_i_5_V_read = ap_const_logic_0;
    }
}

void fire2_copy::thread_mat_i_6_V_read() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_pp0_stg0_fsm_1.read()) && 
         esl_seteq<1,1,1>(exitcond_flatten_reg_891.read(), ap_const_lv1_0) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it1.read()) && 
         !(ap_sig_bdd_379.read() && esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it1.read())))) {
        mat_i_6_V_read = ap_const_logic_1;
    } else {
        mat_i_6_V_read = ap_const_logic_0;
    }
}

void fire2_copy::thread_mat_i_7_V_read() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_pp0_stg0_fsm_1.read()) && 
         esl_seteq<1,1,1>(exitcond_flatten_reg_891.read(), ap_const_lv1_0) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it1.read()) && 
         !(ap_sig_bdd_379.read() && esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it1.read())))) {
        mat_i_7_V_read = ap_const_logic_1;
    } else {
        mat_i_7_V_read = ap_const_logic_0;
    }
}

void fire2_copy::thread_mat_i_8_V_read() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_pp0_stg0_fsm_1.read()) && 
         esl_seteq<1,1,1>(exitcond_flatten_reg_891.read(), ap_const_lv1_0) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it1.read()) && 
         !(ap_sig_bdd_379.read() && esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it1.read())))) {
        mat_i_8_V_read = ap_const_logic_1;
    } else {
        mat_i_8_V_read = ap_const_logic_0;
    }
}

void fire2_copy::thread_mat_i_9_V_read() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_pp0_stg0_fsm_1.read()) && 
         esl_seteq<1,1,1>(exitcond_flatten_reg_891.read(), ap_const_lv1_0) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it1.read()) && 
         !(ap_sig_bdd_379.read() && esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it1.read())))) {
        mat_i_9_V_read = ap_const_logic_1;
    } else {
        mat_i_9_V_read = ap_const_logic_0;
    }
}

void fire2_copy::thread_ap_NS_fsm() {
    switch (ap_CS_fsm.read().to_uint64()) {
        case 1 : 
            if (!ap_sig_bdd_392.read()) {
                ap_NS_fsm = ap_ST_pp0_stg0_fsm_1;
            } else {
                ap_NS_fsm = ap_ST_st1_fsm_0;
            }
            break;
        case 2 : 
            if (!(esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it0.read()) && !(ap_sig_bdd_379.read() && esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it1.read())) && !esl_seteq<1,1,1>(exitcond_flatten_fu_879_p2.read(), ap_const_lv1_0))) {
                ap_NS_fsm = ap_ST_pp0_stg0_fsm_1;
            } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it0.read()) && !(ap_sig_bdd_379.read() && esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it1.read())) && !esl_seteq<1,1,1>(exitcond_flatten_fu_879_p2.read(), ap_const_lv1_0))) {
                ap_NS_fsm = ap_ST_st4_fsm_2;
            } else {
                ap_NS_fsm = ap_ST_pp0_stg0_fsm_1;
            }
            break;
        case 4 : 
            ap_NS_fsm = ap_ST_st1_fsm_0;
            break;
        default : 
            ap_NS_fsm = "XXX";
            break;
    }
}

}

